var group__devicetree =
[
    [ "\"For-each\" macros", "group__devicetree-generic-foreach.html", "group__devicetree-generic-foreach" ],
    [ "Bus helpers", "group__devicetree-generic-bus.html", "group__devicetree-generic-bus" ],
    [ "Chosen nodes", "group__devicetree-generic-chosen.html", "group__devicetree-generic-chosen" ],
    [ "Dependency tracking", "group__devicetree-dep-ord.html", "group__devicetree-dep-ord" ],
    [ "Devicetree CAN API", "group__devicetree-can.html", "group__devicetree-can" ],
    [ "Devicetree Clocks API", "group__devicetree-clocks.html", "group__devicetree-clocks" ],
    [ "Devicetree DMA API", "group__devicetree-dmas.html", "group__devicetree-dmas" ],
    [ "Devicetree Display API", "group__devicetree-display.html", "group__devicetree-display" ],
    [ "Devicetree Fixed Partition API", "group__devicetree-fixed-partition.html", "group__devicetree-fixed-partition" ],
    [ "Devicetree GPIO API", "group__devicetree-gpio.html", "group__devicetree-gpio" ],
    [ "Devicetree HW spinlock API", "group__devicetree-hwspinlock.html", "group__devicetree-hwspinlock" ],
    [ "Devicetree IO Channels API", "group__devicetree-io-channels.html", "group__devicetree-io-channels" ],
    [ "Devicetree Interrupt Controller API", "group__devicetree-interrupt__controller.html", "group__devicetree-interrupt__controller" ],
    [ "Devicetree MBOX API", "group__devicetree-mbox.html", "group__devicetree-mbox" ],
    [ "Devicetree Mapped Partition API", "group__devicetree-mapped-partition.html", "group__devicetree-mapped-partition" ],
    [ "Devicetree PWMs API", "group__devicetree-pwms.html", "group__devicetree-pwms" ],
    [ "Devicetree Partition API", "group__devicetree-partition.html", "group__devicetree-partition" ],
    [ "Devicetree Port Endpoint API", "group__devicetree-port-endpoint.html", "group__devicetree-port-endpoint" ],
    [ "Devicetree Reset Controller API", "group__devicetree-reset-controller.html", "group__devicetree-reset-controller" ],
    [ "Devicetree SPI API", "group__devicetree-spi.html", "group__devicetree-spi" ],
    [ "Devicetree WUC Controller API", "group__devicetree-wakeup-controller.html", "group__devicetree-wakeup-controller" ],
    [ "Devicetree battery helpers", "group__devicetree-battery.html", "group__devicetree-battery" ],
    [ "Existence checks", "group__devicetree-generic-exist.html", "group__devicetree-generic-exist" ],
    [ "Instance-based devicetree APIs", "group__devicetree-inst.html", "group__devicetree-inst" ],
    [ "Map helpers", "group__devicetree-map.html", "group__devicetree-map" ],
    [ "NVMEM Devicetree Helpers", "group__devicetree-nvmem.html", "group__devicetree-nvmem" ],
    [ "Node identifiers and helpers", "group__devicetree-generic-id.html", "group__devicetree-generic-id" ],
    [ "Pin control", "group__devicetree-pinctrl.html", "group__devicetree-pinctrl" ],
    [ "Property accessors", "group__devicetree-generic-prop.html", "group__devicetree-generic-prop" ],
    [ "Vendor and model name helpers", "group__devicetree-generic-vendor.html", "group__devicetree-generic-vendor" ],
    [ "interrupts property", "group__devicetree-interrupts-prop.html", "group__devicetree-interrupts-prop" ],
    [ "ranges property", "group__devicetree-ranges-prop.html", "group__devicetree-ranges-prop" ],
    [ "reg property", "group__devicetree-reg-prop.html", "group__devicetree-reg-prop" ]
];