var group__bluetooth =
[
    [ "Advanced Audio Distribution Profile (A2DP)", "group__bt__a2dp.html", "group__bt__a2dp" ],
    [ "Alert Notification Service (ANS)", "group__bt__ans.html", "group__bt__ans" ],
    [ "Assigned Numbers.", "group__bt__assigned__numbers.html", "group__bt__assigned__numbers" ],
    [ "Attribute Protocol (ATT)", "group__bt__att.html", "group__bt__att" ],
    [ "Audio Input Control Service (AICS)", "group__bt__aics.html", "group__bt__aics" ],
    [ "Audio Video Remote Control Profile (AVRCP)", "group__bt__avrcp.html", "group__bt__avrcp" ],
    [ "Basic Audio Profile (BAP) LC3 Presets", "group__bt__bap__lc3__preset.html", "group__bt__bap__lc3__preset" ],
    [ "Basic Imaging Profile (BIP)", "group__bt__bip.html", "group__bt__bip" ],
    [ "Battery Service (BAS)", "group__bt__bas.html", "group__bt__bas" ],
    [ "BlueNRG HCI driver extended API", "group__bluenrg__hci__driver.html", "group__bluenrg__hci__driver" ],
    [ "Bluetooth Audio", "group__bt__audio.html", "group__bt__audio" ],
    [ "Bluetooth Basic Audio Profile", "group__bt__bap.html", "group__bt__bap" ],
    [ "Bluetooth Content Control Identifier", "group__bt__ccid.html", "group__bt__ccid" ],
    [ "Bluetooth Controller", "group__bt__ctrl.html", "group__bt__ctrl" ],
    [ "Bluetooth Gaming Audio Profile", "group__bt__gmap.html", "group__bt__gmap" ],
    [ "Bluetooth HCI", "group__bt__hci__api.html", "group__bt__hci__api" ],
    [ "Bluetooth LC3 codec", "group__bt__lc3.html", "group__bt__lc3" ],
    [ "Bluetooth Logical Link Control and Adaptation Protocol (L2CAP) for BR/EDR", "group__bt__l2cap__br.html", "group__bt__l2cap__br" ],
    [ "Bluetooth Mesh", "group__bt__mesh.html", "group__bt__mesh" ],
    [ "Byteorder", "group__bt__byteorder.html", "group__bt__byteorder" ],
    [ "Call Control Profile (CCP)", "group__bt__ccp.html", "group__bt__ccp" ],
    [ "Channel Sounding (CS)", "group__bt__le__cs.html", "group__bt__le__cs" ],
    [ "Common Audio Profile (CAP)", "group__bt__cap.html", "group__bt__cap" ],
    [ "Connection management", "group__bt__conn.html", "group__bt__conn" ],
    [ "Coordinated Set Identification Profile (CSIP)", "group__bt__csip.html", "group__bt__csip" ],
    [ "Cryptography", "group__bt__crypto.html", "group__bt__crypto" ],
    [ "Current Time Service (CTS)", "group__bt__cts.html", "group__bt__cts" ],
    [ "Data buffers", "group__bt__buf.html", "group__bt__buf" ],
    [ "Device Address", "group__bt__addr.html", "group__bt__addr" ],
    [ "Elapsed Time Service (ETS)", "group__bt__ets.html", "group__bt__ets" ],
    [ "Encrypted Advertising Data (EAD)", "group__bt__ead.html", "group__bt__ead" ],
    [ "Gaming Audio Profile (GMAP) LC3 Presets", "group__bt__gmap__lc3__preset.html", "group__bt__gmap__lc3__preset" ],
    [ "Generic Access Profile (GAP)", "group__bt__gap.html", "group__bt__gap" ],
    [ "Generic Attribute Profile (GATT)", "group__bt__gatt.html", "group__bt__gatt" ],
    [ "Generic Object Exchange Profile (GOEP)", "group__bt__goep.html", "group__bt__goep" ],
    [ "HCI RAW channel", "group__hci__raw.html", "group__hci__raw" ],
    [ "Hands Free Profile (HFP)", "group__bt__hfp.html", "group__bt__hfp" ],
    [ "Hands Free Profile - Audio Gateway (HFP-AG)", "group__bt__hfp__ag.html", "group__bt__hfp__ag" ],
    [ "Hearing Access Service (HAS)", "group__bt__has.html", "group__bt__has" ],
    [ "Heart Rate Service (HRS)", "group__bt__hrs.html", "group__bt__hrs" ],
    [ "Immediate Alert Service (IAS)", "group__bt__ias.html", "group__bt__ias" ],
    [ "IrDA Oject Exchange Protocol (OBEX)", "group__bt__obex.html", "group__bt__obex" ],
    [ "Isochronous channels (ISO)", "group__bt__iso.html", "group__bt__iso" ],
    [ "L2CAP", "group__bt__l2cap.html", "group__bt__l2cap" ],
    [ "Media Control Client (MCC)", "group__bt__mcc.html", "group__bt__mcc" ],
    [ "Media Control Service (MCS)", "group__bt__mcs.html", "group__bt__mcs" ],
    [ "Media Proxy", "group__bt__media__proxy.html", "group__bt__media__proxy" ],
    [ "Microphone Control Profile (MICP)", "group__bt__micp.html", "group__bt__micp" ],
    [ "Object Transfer Service (OTS)", "group__bt__ots.html", "group__bt__ots" ],
    [ "Public Broadcast Profile (PBP)", "group__bt__pbp.html", "group__bt__pbp" ],
    [ "Published Audio Capabilities Service (PACS)", "group__bt__pacs.html", "group__bt__pacs" ],
    [ "RFCOMM", "group__bt__rfcomm.html", "group__bt__rfcomm" ],
    [ "Service Discovery Protocol (SDP)", "group__bt__sdp.html", "group__bt__sdp" ],
    [ "Telephone Bearer Service (TBS)", "group__bt__tbs.html", "group__bt__tbs" ],
    [ "Telephone and Media Audio Profile (TMAP)", "group__bt__tmap.html", "group__bt__tmap" ],
    [ "UUIDs", "group__bt__uuid.html", "group__bt__uuid" ],
    [ "Volume Control Profile (VCP)", "group__bt__vcp.html", "group__bt__vcp" ],
    [ "Volume Offset Control Service (VOCS)", "group__bt__vocs.html", "group__bt__vocs" ]
];