var group__subsys__tracing__apis =
[
    [ "Conditional variable", "group__subsys__tracing__apis__condvar.html", "group__subsys__tracing__apis__condvar" ],
    [ "Delayable work item", "group__subsys__tracing__apis__work__delayable.html", "group__subsys__tracing__apis__work__delayable" ],
    [ "Event", "group__subsys__tracing__apis__event.html", "group__subsys__tracing__apis__event" ],
    [ "FIFO", "group__subsys__tracing__apis__fifo.html", "group__subsys__tracing__apis__fifo" ],
    [ "GPIO", "group__subsys__tracing__apis__gpio.html", "group__subsys__tracing__apis__gpio" ],
    [ "Heap", "group__subsys__tracing__apis__heap.html", "group__subsys__tracing__apis__heap" ],
    [ "LIFO", "group__subsys__tracing__apis__lifo.html", "group__subsys__tracing__apis__lifo" ],
    [ "Mailbox", "group__subsys__tracing__apis__mbox.html", "group__subsys__tracing__apis__mbox" ],
    [ "Memory slab", "group__subsys__tracing__apis__mslab.html", "group__subsys__tracing__apis__mslab" ],
    [ "Message queue", "group__subsys__tracing__apis__msgq.html", "group__subsys__tracing__apis__msgq" ],
    [ "Mutex", "group__subsys__tracing__apis__mutex.html", "group__subsys__tracing__apis__mutex" ],
    [ "Network", "group__subsys__tracing__apis__net.html", "group__subsys__tracing__apis__net" ],
    [ "Network socket", "group__subsys__tracing__apis__socket.html", "group__subsys__tracing__apis__socket" ],
    [ "PM Device Runtime", "group__subsys__tracing__apis__pm__device__runtime.html", "group__subsys__tracing__apis__pm__device__runtime" ],
    [ "Pipe", "group__subsys__tracing__apis__pipe.html", "group__subsys__tracing__apis__pipe" ],
    [ "Polling", "group__subsys__tracing__apis__poll.html", "group__subsys__tracing__apis__poll" ],
    [ "Queue", "group__subsys__tracing__apis__queue.html", "group__subsys__tracing__apis__queue" ],
    [ "RTIO Tracing APIs", "group__subsys__tracing__apis__rtio.html", "group__subsys__tracing__apis__rtio" ],
    [ "Semaphore", "group__subsys__tracing__apis__sem.html", "group__subsys__tracing__apis__sem" ],
    [ "Stack", "group__subsys__tracing__apis__stack.html", "group__subsys__tracing__apis__stack" ],
    [ "Syscall Tracing", "group__subsys__tracing__apis__syscall.html", "group__subsys__tracing__apis__syscall" ],
    [ "System PM", "group__subsys__tracing__apis__pm__system.html", "group__subsys__tracing__apis__pm__system" ],
    [ "Thread", "group__subsys__tracing__apis__thread.html", "group__subsys__tracing__apis__thread" ],
    [ "Timer", "group__subsys__tracing__apis__timer.html", "group__subsys__tracing__apis__timer" ],
    [ "Triggered work item", "group__subsys__tracing__apis__work__poll.html", "group__subsys__tracing__apis__work__poll" ],
    [ "User-defined event", "group__subsys__tracing__apis__named.html", "group__subsys__tracing__apis__named" ],
    [ "Work item", "group__subsys__tracing__apis__work.html", "group__subsys__tracing__apis__work" ],
    [ "Work queue", "group__subsys__tracing__apis__work__q.html", "group__subsys__tracing__apis__work__q" ],
    [ "tracing.h", "tracing_8h.html", null ],
    [ "sys_trace_sys_init_enter", "group__subsys__tracing__apis.html#ga9b5a02fc57b86d38f857597c7a2553f6", null ],
    [ "sys_trace_sys_init_exit", "group__subsys__tracing__apis.html#gacd56f9b376b4639cbe21e12055ca74c7", null ],
    [ "sys_trace_idle", "group__subsys__tracing__apis.html#gac9b542f78ed796b4b572de19d295c824", null ],
    [ "sys_trace_idle_exit", "group__subsys__tracing__apis.html#gac7b7973acf38a440e88242aca52e424c", null ],
    [ "sys_trace_isr_enter", "group__subsys__tracing__apis.html#ga37f43a02961a847af3b7de6c474a8da4", null ],
    [ "sys_trace_isr_exit", "group__subsys__tracing__apis.html#ga7113e2760b1a7ffb1bfa108ad9bfb4be", null ],
    [ "sys_trace_isr_exit_to_scheduler", "group__subsys__tracing__apis.html#ga303fe60fd4de8ddcc02c6920656e326d", null ]
];