var group__os__services =
[
    [ "Asynchronous Notification APIs", "group__sys__notify__apis.html", "group__sys__notify__apis" ],
    [ "Binary Descriptors", "group__bindesc.html", "group__bindesc" ],
    [ "CPU Frequency (CPUFreq)", "group__subsys__cpu__freq.html", "group__subsys__cpu__freq" ],
    [ "CPU Load", "group__subsys__cpu__load.html", "group__subsys__cpu__load" ],
    [ "Cache Interface", "group__cache__interface.html", "group__cache__interface" ],
    [ "Checksum", "group__checksum.html", "group__checksum" ],
    [ "Cleanup Helper Interface", "group__cleanup__interface.html", "group__cleanup__interface" ],
    [ "Console API", "group__console__api.html", "group__console__api" ],
    [ "Crypto", "group__crypto.html", "group__crypto" ],
    [ "Debug", "group__debug.html", "group__debug" ],
    [ "Device Management", "group__device__mgmt.html", "group__device__mgmt" ],
    [ "File System APIs", "group__file__system__api.html", "group__file__system__api" ],
    [ "File System Storage", "group__file__system__storage.html", "group__file__system__storage" ],
    [ "Flash image API", "group__flash__img__api.html", "group__flash__img__api" ],
    [ "Heap Management", "group__heaps.html", "group__heaps" ],
    [ "IPC", "group__ipc.html", "group__ipc" ],
    [ "Instrumentation", "group__instrumentation__api.html", "group__instrumentation__api" ],
    [ "Iterable Sections APIs", "group__iterable__section__apis.html", "group__iterable__section__apis" ],
    [ "Linkable loadable extensions", "group__llext__apis.html", "group__llext__apis" ],
    [ "Logging", "group__logging.html", "group__logging" ],
    [ "Memory Management", "group__memory__management.html", "group__memory__management" ],
    [ "Network Buffer Library", "group__net__buf.html", "group__net__buf" ],
    [ "On-Off Service APIs", "group__resource__mgmt__onoff__apis.html", "group__resource__mgmt__onoff__apis" ],
    [ "PSA Secure Storage API", "group__psa__secure__storage.html", "group__psa__secure__storage" ],
    [ "Power Management (PM)", "group__subsys__pm.html", "group__subsys__pm" ],
    [ "RTIO", "group__rtio.html", "group__rtio" ],
    [ "Retention API", "group__retention__api.html", "group__retention__api" ],
    [ "Semihosting APIs", "group__semihost.html", "group__semihost" ],
    [ "Sensing", "group__sensing__api.html", "group__sensing__api" ],
    [ "Shell API", "group__shell__api.html", "group__shell__api" ],
    [ "State Machine Framework API", "group__smf.html", "group__smf" ],
    [ "Storage APIs", "group__storage__apis.html", "group__storage__apis" ],
    [ "System Initialization", "group__sys__init.html", "group__sys__init" ],
    [ "System power off", "group__sys__poweroff.html", "group__sys__poweroff" ],
    [ "Task Watchdog APIs", "group__task__wdt__api.html", "group__task__wdt__api" ],
    [ "Timing Measurement APIs", "group__timing__api.html", "group__timing__api" ],
    [ "Tracing", "group__subsys__tracing.html", "group__subsys__tracing" ],
    [ "Zbus APIs", "group__zbus__apis.html", "group__zbus__apis" ]
];