var group__io__interfaces =
[
    [ "1-Wire", "group__w1__interface.html", "group__w1__interface" ],
    [ "ADC", "group__adc__interface.html", "group__adc__interface" ],
    [ "Auxiliary (Text) Display", "group__auxdisplay__interface.html", "group__auxdisplay__interface" ],
    [ "BBRAM", "group__bbram__interface.html", "group__bbram__interface" ],
    [ "Battery Charger", "group__charger__interface.html", "group__charger__interface" ],
    [ "Biometrics", "group__biometrics__interface.html", "group__biometrics__interface" ],
    [ "CAN", "group__can__interface.html", "group__can__interface" ],
    [ "CRC driver APIs", "group__crc__interface.html", "group__crc__interface" ],
    [ "Cellular", "group__cellular__interface.html", "group__cellular__interface" ],
    [ "Clock Control", "group__clock__control__interface.html", "group__clock__control__interface" ],
    [ "Comparator", "group__comparator__interface.html", "group__comparator__interface" ],
    [ "Coredump pseudo-device", "group__coredump__device__interface.html", "group__coredump__device__interface" ],
    [ "Counter", "group__counter__interface.html", "group__counter__interface" ],
    [ "DAC", "group__dac__interface.html", "group__dac__interface" ],
    [ "DAI", "group__dai__interface.html", "group__dai__interface" ],
    [ "DAP Link", "group__dap__link__interface.html", "group__dap__link__interface" ],
    [ "DMA", "group__dma__interface.html", "group__dma__interface" ],
    [ "Disk Access", "group__disk__driver__interface.html", "group__disk__driver__interface" ],
    [ "Display", "group__display__interface.html", "group__display__interface" ],
    [ "EDAC", "group__edac__interface.html", "group__edac__interface" ],
    [ "EEPROM", "group__eeprom__interface.html", "group__eeprom__interface" ],
    [ "ESPI", "group__espi__interface.html", "group__espi__interface" ],
    [ "Entropy", "group__entropy__interface.html", "group__entropy__interface" ],
    [ "External Cache Controller", "group__cache__external__interface.html", "group__cache__external__interface" ],
    [ "FPGA", "group__fpga__interface.html", "group__fpga__interface" ],
    [ "Flash", "group__flash__interface.html", "group__flash__interface" ],
    [ "Fuel Gauge", "group__fuel__gauge__interface.html", "group__fuel__gauge__interface" ],
    [ "GNSS", "group__gnss__interface.html", "group__gnss__interface" ],
    [ "GPIO", "group__gpio__interface.html", "group__gpio__interface" ],
    [ "Haptics", "group__haptics__interface.html", "group__haptics__interface" ],
    [ "Hardware Info", "group__hwinfo__interface.html", "group__hwinfo__interface" ],
    [ "Hardware Spinlock", "group__hwspinlock__interface.html", "group__hwspinlock__interface" ],
    [ "I2C", "group__i2c__interface.html", "group__i2c__interface" ],
    [ "I2S", "group__i2s__interface.html", "group__i2s__interface" ],
    [ "I3C", "group__i3c__interface.html", "group__i3c__interface" ],
    [ "IPM", "group__ipm__interface.html", "group__ipm__interface" ],
    [ "Input", "group__input__interface.html", "group__input__interface" ],
    [ "Inter-VM Shared Memory", "group__ivshmem.html", "group__ivshmem" ],
    [ "LED", "group__led__interface.html", "group__led__interface" ],
    [ "LED Strip", "group__led__strip__interface.html", "group__led__strip__interface" ],
    [ "LoRa", "group__lora__interface.html", "group__lora__interface" ],
    [ "MBOX", "group__mbox__interface.html", "group__mbox__interface" ],
    [ "MDIO", "group__mdio__interface.html", "group__mdio__interface" ],
    [ "MSPI", "group__mspi__interface.html", "group__mspi__interface" ],
    [ "Miscellaneous Devices", "group__misc__interfaces.html", "group__misc__interfaces" ],
    [ "Multi-function Devices", "group__mfd__interfaces.html", "group__mfd__interfaces" ],
    [ "NVMEM", "group__nvmem__interface.html", "group__nvmem__interface" ],
    [ "OPAMP", "group__opamp__interface.html", "group__opamp__interface" ],
    [ "One Time Programmable Memory", "group__otp__interface.html", "group__otp__interface" ],
    [ "PCIe", "group__pcie__interface.html", "group__pcie__interface" ],
    [ "PECI", "group__peci__interface.html", "group__peci__interface" ],
    [ "PS/2", "group__ps2__interface.html", "group__ps2__interface" ],
    [ "PSI5", "group__psi5__interface.html", "group__psi5__interface" ],
    [ "PTP Clock", "group__ptp__clock__interface.html", "group__ptp__clock__interface" ],
    [ "PWM", "group__pwm__interface.html", "group__pwm__interface" ],
    [ "Pin Control", "group__pinctrl__interface.html", "group__pinctrl__interface" ],
    [ "QEMU fw_cfg", "group__qemu__fwcfg__interface.html", "group__qemu__fwcfg__interface" ],
    [ "RTC", "group__rtc__interface.html", "group__rtc__interface" ],
    [ "Regulator", "group__regulator__interface.html", "group__regulator__interface" ],
    [ "Reset Controller", "group__reset__controller__interface.html", "group__reset__controller__interface" ],
    [ "Retained memory", "group__retained__mem__interface.html", "group__retained__mem__interface" ],
    [ "SCMI", "group__scmi__interface.html", "group__scmi__interface" ],
    [ "SDHC", "group__sdhc__interface.html", "group__sdhc__interface" ],
    [ "SENT", "group__sent__interface.html", "group__sent__interface" ],
    [ "SMBus", "group__smbus__interface.html", "group__smbus__interface" ],
    [ "SPI", "group__spi__interface.html", "group__spi__interface" ],
    [ "SWDP", "group__swdp__interface.html", "group__swdp__interface" ],
    [ "Sensor", "group__sensor__interface.html", "group__sensor__interface" ],
    [ "Stepper", "group__stepper__interface.html", "group__stepper__interface" ],
    [ "System control (SYSCON)", "group__syscon__interface.html", "group__syscon__interface" ],
    [ "TEE", "group__tee__interface.html", "group__tee__interface" ],
    [ "Time-aware GPIO", "group__tgpio__interface.html", "group__tgpio__interface" ],
    [ "UART", "group__uart__interface.html", "group__uart__interface" ],
    [ "USB", "group__usb__interfaces.html", "group__usb__interfaces" ],
    [ "VIRTIO", "group__virtio__interface.html", "group__virtio__interface" ],
    [ "Video", "group__video__interface.html", "group__video__interface" ],
    [ "WUC", "group__wuc__interface.html", "group__wuc__interface" ],
    [ "Watchdog", "group__watchdog__interface.html", "group__watchdog__interface" ]
];