var searchData=
[
  ['s2ram_20apis_0',['S2RAM APIs',['../group__pm__s2ram.html',1,'']]],
  ['s3km1110_1',['Iclegend S3KM1110',['../group__s3km1110__interface.html',1,'']]],
  ['s50_2',['AFBR-S50',['../group__afbr__s50__interface.html',1,'']]],
  ['saf_3',['eSPI SAF',['../group__espi__saf__interface.html',1,'']]],
  ['sample_20count_4',['Temperature average sample count',['../group__tmp11x__os.html',1,'']]],
  ['sampling_20rate_20by_20provided_20rate_5',['decimate sampling rate by provided rate',['../group__mc3419__decimation__rates.html',1,'']]],
  ['sar_20configuration_20client_20model_6',['Bluetooth Mesh SAR Configuration Client Model',['../group__bt__mesh__sar__cfg__cli.html',1,'']]],
  ['sar_20configuration_20common_20header_7',['SAR Configuration common header',['../group__bt__mesh__sar__cfg.html',1,'']]],
  ['sar_20configuration_20server_20model_8',['Bluetooth Mesh SAR Configuration Server Model',['../group__bt__mesh__sar__cfg__srv.html',1,'']]],
  ['scale_9',['Vector Scale',['../group__math__dsp__basic__scale.html',1,'']]],
  ['scale_20options_10',['scale options',['../group__icm42688__accel__scale.html',1,'Accelerometer scale options'],['../group__ICM45686__ACCEL__SCALE.html',1,'Accelerometer scale options'],['../group__ICM42686__ACCEL__SCALE.html',1,'Accelerometer scale options'],['../group__ICM45686__GYRO__SCALE.html',1,'Gyroscope scale options'],['../group__icm42688__gyro__scale.html',1,'Gyroscope scale options'],['../group__ICM42686__GYRO__SCALE.html',1,'Gyroscope scale options']]],
  ['scanning_20configuration_11',['WIFI scanning configuration',['../group__st87mxx__wscan__configuration.html',1,'']]],
  ['scd4x_12',['SCD4X',['../group__scd4x__interface.html',1,'']]],
  ['scmi_13',['SCMI',['../group__scmi__interface.html',1,'']]],
  ['sdhc_14',['SDHC',['../group__sdhc__interface.html',1,'']]],
  ['sdmmc_15',['STM32 SDMMC',['../group__stm32__sdmmc__disk__interface.html',1,'']]],
  ['sdp_16',['Service Discovery Protocol (SDP)',['../group__bt__sdp.html',1,'']]],
  ['sections_20apis_17',['Iterable Sections APIs',['../group__iterable__section__apis.html',1,'']]],
  ['secure_20storage_20api_18',['PSA Secure Storage API',['../group__psa__secure__storage.html',1,'']]],
  ['select_20range_20options_19',['select range options',['../group__adxl355__range.html',1,'Select range options'],['../group__adxl345__range.html',1,'Select range options']]],
  ['selection_20',['Thermocouple type selection',['../group__mcp9600__thermocouple__type.html',1,'']]],
  ['semaphore_21',['Semaphore',['../group__subsys__tracing__apis__sem.html',1,'']]],
  ['semaphore_20apis_22',['semaphore apis',['../group__semaphore__apis.html',1,'Semaphore APIs'],['../group__user__semaphore__apis.html',1,'User mode semaphore APIs']]],
  ['semihosting_20apis_23',['Semihosting APIs',['../group__semihost.html',1,'']]],
  ['sense_20amplifier_24',['Current Sense Amplifier',['../group__adc__current__sense__amplifier__interface.html',1,'']]],
  ['sense_20shunt_25',['Current Sense Shunt',['../group__adc__current__sense__shunt__interface.html',1,'']]],
  ['sensing_26',['sensing',['../group__sensing__api.html',1,'Sensing'],['../group__sensing__sensor__types.html',1,'Sensor Types (Sensing)'],['../group__sensing__sensor.html',1,'Sensors (Sensing)']]],
  ['sensor_27',['Sensor',['../group__sensor__interface.html',1,'']]],
  ['sensor_20alignment_28',['sensor alignment',['../group__sensor__axis__align__index__dt.html',1,'Axis description for sensor alignment'],['../group__sensor__axis__align__dt.html',1,'Axis description for sensor alignment']]],
  ['sensor_20api_29',['1-Wire Sensor API',['../group__w1__sensor.html',1,'']]],
  ['sensor_20api_20extensions_30',['Device-specific Sensor API extensions',['../group__sensor__interface__ext.html',1,'']]],
  ['sensor_20axis_20alignment_20dt_20options_31',['Sensor axis alignment DT Options',['../group__sensor__axis__align.html',1,'']]],
  ['sensor_20driver_20backend_20api_32',['Sensor Driver Backend API',['../group__sensor__interface__backend.html',1,'']]],
  ['sensor_20emulator_20backend_20api_33',['Sensor emulator backend API',['../group__sensor__emulator__backend.html',1,'']]],
  ['sensor_20interface_34',['nPM10xx Sensor interface',['../group__sensor__interface__npm10xx.html',1,'']]],
  ['sensor_20power_20modes_35',['Sensor power modes',['../group__bmp581__power__modes.html',1,'']]],
  ['sensor_20types_20sensing_36',['Sensor Types (Sensing)',['../group__sensing__sensor__types.html',1,'']]],
  ['sensors_20sensing_37',['Sensors (Sensing)',['../group__sensing__sensor.html',1,'']]],
  ['sent_38',['SENT',['../group__sent__interface.html',1,'']]],
  ['serial_20transport_39',['Serial transport',['../group__mcumgr__transport__serial.html',1,'']]],
  ['series_202_20devicetree_20helpers_40',['Silicon Labs Series 2 Devicetree helpers',['../group__clock__control__silabs.html',1,'']]],
  ['server_41',['server',['../group__bt__mesh__od__priv__proxy__srv.html',1,'Bluetooth Mesh On-Demand Private GATT Proxy Server'],['../group__bt__mesh__priv__beacon__srv.html',1,'Bluetooth Mesh Private Beacon Server'],['../group__bt__mesh__sol__pdu__rpl__srv.html',1,'Bluetooth Mesh Solicitation PDU RPL Server'],['../group__dhcpv4__server.html',1,'DHCPv4 server'],['../group__bt__mesh__rpr__srv.html',1,'Remote provisioning server']]],
  ['server_20api_42',['HTTP server API',['../group__http__server.html',1,'']]],
  ['server_20apis_43',['server apis',['../group__bt__bap__unicast__server.html',1,'BAP Unicast Server APIs'],['../group__bt__ccp__call__control__server.html',1,'CCP Call Control Server APIs'],['../group__bt__gatt__server.html',1,'GATT Server APIs']]],
  ['server_20model_44',['server model',['../group__bt__mesh__sar__cfg__srv.html',1,'Bluetooth Mesh SAR Configuration Server Model'],['../group__bt__mesh__brg__cfg__srv.html',1,'Bridge Configuration Server Model'],['../group__bt__mesh__cfg__srv.html',1,'Configuration Server Model'],['../group__bt__mesh__dfd__srv.html',1,'Firmware Distribution Server model'],['../group__bt__mesh__dfu__srv.html',1,'Firmware Update Server model'],['../group__bt__mesh__health__srv.html',1,'Health Server Model'],['../group__bt__mesh__large__comp__data__srv.html',1,'Large Composition Data Server model'],['../group__bt__mesh__op__agg__srv.html',1,'Opcodes Aggregator Server model']]],
  ['server_20model_20api_45',['Bluetooth Mesh BLOB Transfer Server model API',['../group__bt__mesh__blob__srv.html',1,'']]],
  ['service_46',['service',['../group__min__heap__apis.html',1,'Min-Heap service'],['../group__wg__vpn__service.html',1,'Wireguard VPN service']]],
  ['service_20aics_47',['Audio Input Control Service (AICS)',['../group__bt__aics.html',1,'']]],
  ['service_20ans_48',['Alert Notification Service (ANS)',['../group__bt__ans.html',1,'']]],
  ['service_20api_49',['service api',['../group__bsd__socket__service.html',1,'BSD socket service API'],['../group__coap__service.html',1,'CoAP service API'],['../group__http__service.html',1,'HTTP service API']]],
  ['service_20apis_50',['service apis',['../group__ipc__service__api.html',1,'IPC service APIs'],['../group__resource__mgmt__onoff__apis.html',1,'On-Off Service APIs'],['../group__rpmsg__service__api.html',1,'RPMsg service APIs']]],
  ['service_20backend_51',['IPC service backend',['../group__ipc__service__backend.html',1,'']]],
  ['service_20bas_52',['Battery Service (BAS)',['../group__bt__bas.html',1,'']]],
  ['service_20cts_53',['Current Time Service (CTS)',['../group__bt__cts.html',1,'']]],
  ['service_20discovery_54',['DNS Service Discovery',['../group__dns__sd.html',1,'']]],
  ['service_20discovery_20protocol_20sdp_55',['Service Discovery Protocol (SDP)',['../group__bt__sdp.html',1,'']]],
  ['service_20ets_56',['Elapsed Time Service (ETS)',['../group__bt__ets.html',1,'']]],
  ['service_20has_57',['Hearing Access Service (HAS)',['../group__bt__has.html',1,'']]],
  ['service_20hrs_58',['Heart Rate Service (HRS)',['../group__bt__hrs.html',1,'']]],
  ['service_20ias_59',['Immediate Alert Service (IAS)',['../group__bt__ias.html',1,'']]],
  ['service_20mcs_60',['Media Control Service (MCS)',['../group__bt__mcs.html',1,'']]],
  ['service_20ots_61',['Object Transfer Service (OTS)',['../group__bt__ots.html',1,'']]],
  ['service_20pacs_62',['Published Audio Capabilities Service (PACS)',['../group__bt__pacs.html',1,'']]],
  ['service_20routine_20apis_63',['Interrupt Service Routine APIs',['../group__isr__apis.html',1,'']]],
  ['service_20rpmsg_20api_64',['IPC service RPMsg API',['../group__ipc__service__rpmsg__api.html',1,'']]],
  ['service_20static_20vrings_20api_65',['IPC service static VRINGs API',['../group__ipc__service__static__vrings__api.html',1,'']]],
  ['service_20tbs_66',['Telephone Bearer Service (TBS)',['../group__bt__tbs.html',1,'']]],
  ['service_20vocs_67',['Volume Offset Control Service (VOCS)',['../group__bt__vocs.html',1,'']]],
  ['services_68',['Operating System Services',['../group__os__services.html',1,'']]],
  ['services_20apis_69',['services apis',['../group__atomic__apis.html',1,'Atomic Services APIs'],['../group__barrier__apis.html',1,'Barrier Services APIs']]],
  ['set_70',['Disjoint-set',['../group__union__find__apis.html',1,'']]],
  ['set_20identification_20profile_20csip_71',['Coordinated Set Identification Profile (CSIP)',['../group__bt__csip.html',1,'']]],
  ['settings_72',['Settings',['../group__settings.html',1,'']]],
  ['settings_20backend_20interface_73',['Settings backend interface',['../group__settings__backend.html',1,'']]],
  ['settings_20management_74',['Settings Management',['../group__mcumgr__settings__mgmt.html',1,'']]],
  ['settings_20management_20callbacks_75',['Settings Management Callbacks',['../group__mcumgr__callback__api__settings__mgmt.html',1,'']]],
  ['settings_20name_20processing_76',['Settings name processing',['../group__settings__name__proc.html',1,'']]],
  ['settings_20subsystem_20runtime_77',['Settings subsystem runtime',['../group__settings__rt.html',1,'']]],
  ['sf32lb_20specifics_78',['sf32lb specifics',['../group__clock__control__sf32lb.html',1,'Clock Control (SF32LB specifics)'],['../group__dma__sf32lb.html',1,'DMA (SF32LB specifics)']]],
  ['sf32lb52x_20pin_20control_20helpers_79',['SiFli SF32LB52x pin control helpers',['../group__pinctrl__sf32lb52x.html',1,'']]],
  ['sgp40_80',['SGP40',['../group__sgp40__interface.html',1,'']]],
  ['shared_20memory_81',['shared memory',['../group__ivshmem.html',1,'Inter-VM Shared Memory'],['../group__scmi__shmem.html',1,'Shared Memory']]],
  ['shared_20multi_20heap_20interface_82',['Shared multi-heap interface',['../group__shared__multi__heap.html',1,'']]],
  ['shell_20api_83',['Shell API',['../group__shell__api.html',1,'']]],
  ['shell_20management_84',['Shell Management',['../group__mcumgr__shell__mgmt.html',1,'']]],
  ['shell_20transport_85',['Shell transport',['../group__mcumgr__transport__shell.html',1,'']]],
  ['shift_86',['Vector Shift',['../group__math__dsp__basic__shift.html',1,'']]],
  ['shift_20conversion_20functions_87',['Float/Fixed point shift conversion functions',['../group__math__dsp__utils__shifts.html',1,'']]],
  ['sht4x_88',['SHT4X',['../group__sht4x__interface.html',1,'']]],
  ['shunt_89',['Current Sense Shunt',['../group__adc__current__sense__shunt__interface.html',1,'']]],
  ['sifli_20pin_20control_20helpers_90',['SiFli pin control helpers',['../group__sifli__pinctrl.html',1,'']]],
  ['sifli_20sf32lb52x_20pin_20control_20helpers_91',['SiFli SF32LB52x pin control helpers',['../group__pinctrl__sf32lb52x.html',1,'']]],
  ['signal_20processing_92',['DSP (Digital Signal Processing)',['../group__math__dsp.html',1,'']]],
  ['silabs_20dcdc_20devicetree_20helpers_93',['Silabs DCDC devicetree helpers.',['../group__regulator__silabs__dcdc.html',1,'']]],
  ['silicon_20labs_20pin_20control_20helpers_94',['Silicon Labs pin control helpers',['../group__silabs__pinctrl.html',1,'']]],
  ['silicon_20labs_20series_202_20devicetree_20helpers_95',['Silicon Labs Series 2 Devicetree helpers',['../group__clock__control__silabs.html',1,'']]],
  ['silicon_20labs_20xg21_20pin_20control_20helpers_96',['Silicon Labs xG21 pin control helpers',['../group__pinctrl__xg21.html',1,'']]],
  ['silicon_20labs_20xg22_20pin_20control_20helpers_97',['Silicon Labs xG22 pin control helpers',['../group__pinctrl__xg22.html',1,'']]],
  ['silicon_20labs_20xg23_20pin_20control_20helpers_98',['Silicon Labs xG23 pin control helpers',['../group__pinctrl__xg23.html',1,'']]],
  ['silicon_20labs_20xg24_20pin_20control_20helpers_99',['Silicon Labs xG24 pin control helpers',['../group__pinctrl__xg24.html',1,'']]],
  ['silicon_20labs_20xg26_20pin_20control_20helpers_100',['Silicon Labs xG26 pin control helpers',['../group__pinctrl__xg26.html',1,'']]],
  ['silicon_20labs_20xg27_20pin_20control_20helpers_101',['Silicon Labs xG27 pin control helpers',['../group__pinctrl__xg27.html',1,'']]],
  ['silicon_20labs_20xg28_20pin_20control_20helpers_102',['Silicon Labs xG28 pin control helpers',['../group__pinctrl__xg28.html',1,'']]],
  ['silicon_20labs_20xg29_20pin_20control_20helpers_103',['Silicon Labs xG29 pin control helpers',['../group__pinctrl__xg29.html',1,'']]],
  ['simulator_104',['Simulator',['../group__ec__host__cmd__simulator.html',1,'']]],
  ['single_20consumer_20packet_20buffer_20api_105',['MPSC (Multi producer, single consumer) packet buffer API',['../group__mpsc__buf.html',1,'']]],
  ['single_20consumer_20packet_20header_106',['MPSC (Multi producer, single consumer) packet header',['../group__mpsc__packet.html',1,'']]],
  ['single_20linked_20list_107',['single linked list',['../group__flagged-single-linked-list__apis.html',1,'Flagged Single-linked list'],['../group__single-linked-list__apis.html',1,'Single-linked list']]],
  ['single_20mmio_20region_20macros_108',['Single MMIO region macros',['../group__device-mmio-single.html',1,'']]],
  ['single_20producer_20single_20consumer_20packet_20buffer_20api_109',['SPSC (Single producer, single consumer) packet buffer API',['../group__spsc__buf.html',1,'']]],
  ['sink_20apis_110',['BAP Broadcast Sink APIs',['../group__bt__bap__broadcast__sink.html',1,'']]],
  ['sink_5fcallbacks_111',['Sink_callbacks',['../group__sink__callbacks.html',1,'']]],
  ['slab_112',['Memory slab',['../group__subsys__tracing__apis__mslab.html',1,'']]],
  ['slab_20apis_113',['Memory Slab APIs',['../group__mem__slab__apis.html',1,'']]],
  ['smbus_114',['SMBus',['../group__smbus__interface.html',1,'']]],
  ['smp_20apis_115',['Architecture-specific SMP APIs',['../group__arch-smp.html',1,'']]],
  ['smp_20client_116',['SMP client',['../group__mcumgr__smp__client.html',1,'']]],
  ['smp_20transport_117',['SMP transport',['../group__mcumgr__transport__smp.html',1,'']]],
  ['sn_20client_20library_118',['MQTT-SN Client library',['../group__mqtt__sn__socket.html',1,'']]],
  ['sntp_119',['SNTP',['../group__sntp.html',1,'']]],
  ['soc_20specific_20timing_20measurement_20apis_120',['SoC specific Timing Measurement APIs',['../group__timing__api__soc.html',1,'']]],
  ['socket_121',['Network socket',['../group__subsys__tracing__apis__socket.html',1,'']]],
  ['socket_20net_5fmgmt_20library_122',['Socket NET_MGMT library',['../group__socket__net__mgmt.html',1,'']]],
  ['socket_20options_20for_20tls_123',['Socket options for TLS',['../group__secure__sockets__options.html',1,'']]],
  ['socket_20service_20api_124',['BSD socket service API',['../group__bsd__socket__service.html',1,'']]],
  ['socketcan_20library_125',['SocketCAN library',['../group__socket__can.html',1,'']]],
  ['sockets_20compatible_20api_126',['BSD Sockets compatible API',['../group__bsd__sockets.html',1,'']]],
  ['solicitation_20pdu_20rpl_20client_127',['Bluetooth Mesh Solicitation PDU RPL Client',['../group__bt__mesh__sol__pdu__rpl__cli.html',1,'']]],
  ['solicitation_20pdu_20rpl_20server_128',['Bluetooth Mesh Solicitation PDU RPL Server',['../group__bt__mesh__sol__pdu__rpl__srv.html',1,'']]],
  ['sounding_20cs_129',['Channel Sounding (CS)',['../group__bt__le__cs.html',1,'']]],
  ['source_20apis_130',['BAP Broadcast Source APIs',['../group__bt__bap__broadcast__source.html',1,'']]],
  ['source_20constants_131',['Renesas RA BSP Clock Source Constants',['../group__bsp__clock__source.html',1,'']]],
  ['source_5fcallbacks_132',['Source_callbacks',['../group__source__callbacks.html',1,'']]],
  ['specific_20adc_20api_20extensions_133',['Device-specific ADC API extensions',['../group__adc__interface__ext.html',1,'']]],
  ['specific_20cache_20controllers_134',['Architecture-specific cache controllers.',['../group__arch-cache.html',1,'']]],
  ['specific_20charger_20api_20extensions_135',['Device-specific Charger API extensions',['../group__charger__interface__ext.html',1,'']]],
  ['specific_20core_20dump_20apis_136',['Architecture-specific core dump APIs',['../group__arch-coredump.html',1,'']]],
  ['specific_20dac_20api_20extensions_137',['Device-specific DAC API extensions',['../group__dac__interface__ext.html',1,'']]],
  ['specific_20definitions_138',['HID class USB specific definitions',['../group__usb__hid__device__api.html',1,'']]],
  ['specific_20disk_20access_20api_20extensions_139',['Device-specific Disk Access API extensions',['../group__disk__driver__interface__ext.html',1,'']]],
  ['specific_20display_20api_20extensions_140',['Device-specific Display API extensions',['../group__display__interface__ext.html',1,'']]],
  ['specific_20edac_20api_20extensions_141',['Device-specific EDAC API extensions',['../group__edac__interface__ext.html',1,'']]],
  ['specific_20fields_142',['UMP Stream specific fields',['../group__midi__ump__stream.html',1,'']]],
  ['specific_20flags_143',['STM32 GPIO specific flags',['../group__gpio__interface__stm32.html',1,'']]],
  ['specific_20gdbstub_20apis_144',['Architecture-specific gdbstub APIs',['../group__arch-gdbstub.html',1,'']]],
  ['specific_20gpio_20api_20extensions_145',['Device-specific GPIO API extensions',['../group__gpio__interface__ext.html',1,'']]],
  ['specific_20gpio_20flags_146',['specific gpio flags',['../group__gpio__interface__max32.html',1,'MAX32-specific GPIO Flags'],['../group__gpio__interface__npm13xx.html',1,'nPM13xx-specific GPIO Flags'],['../group__gpio__interface__npm2100.html',1,'nPM2100-specific GPIO Flags'],['../group__gpio__interface__npm6001.html',1,'nPM6001-specific GPIO Flags'],['../group__gpio__interface__nrf.html',1,'nRF-specific GPIO Flags']]],
  ['specific_20haptics_20api_20extensions_147',['Device-specific Haptics API extensions',['../group__haptics__interface__ext.html',1,'']]],
  ['specific_20input_20api_20extensions_148',['Device-specific Input API extensions',['../group__input__interface__ext.html',1,'']]],
  ['specific_20irq_20apis_149',['Architecture-specific IRQ APIs',['../group__arch-irq.html',1,'']]],
  ['specific_20led_20strip_20api_20extensions_150',['Device-specific LED Strip API extensions',['../group__led__strip__interface__ext.html',1,'']]],
  ['specific_20memory_20mapping_20apis_151',['Architecture-specific memory-mapping APIs',['../group__arch-mmu.html',1,'']]],
  ['specific_20power_20management_20apis_152',['Architecture-specific power management APIs',['../group__arch-pm.html',1,'']]],
  ['specific_20pwm_20api_20extensions_153',['Device-specific PWM API extensions',['../group__pwm__interface__ext.html',1,'']]],
  ['specific_20sensor_20api_20extensions_154',['Device-specific Sensor API extensions',['../group__sensor__interface__ext.html',1,'']]],
  ['specific_20smp_20apis_155',['Architecture-specific SMP APIs',['../group__arch-smp.html',1,'']]],
  ['specific_20stack_20walk_20apis_156',['Architecture-specific Stack Walk APIs',['../group__arch-stackwalk.html',1,'']]],
  ['specific_20thread_20local_20storage_20apis_157',['Architecture-specific Thread Local Storage APIs',['../group__arch-tls.html',1,'']]],
  ['specific_20timing_20measurement_20apis_158',['specific timing measurement apis',['../group__timing__api__arch.html',1,'Arch specific Timing Measurement APIs'],['../group__timing__api__board.html',1,'Board specific Timing Measurement APIs'],['../group__timing__api__soc.html',1,'SoC specific Timing Measurement APIs']]],
  ['specific_20userspace_20apis_159',['Architecture-specific userspace APIs',['../group__arch-userspace.html',1,'']]],
  ['specification_20assigned_20numbers_160',['Core Specification Assigned Numbers',['../group__bt__assigned__numbers__core.html',1,'']]],
  ['specifics_161',['specifics',['../group__clock__control__sf32lb.html',1,'Clock Control (SF32LB specifics)'],['../group__dma__sf32lb.html',1,'DMA (SF32LB specifics)']]],
  ['spi_162',['SPI',['../group__spi__interface.html',1,'']]],
  ['spi_20api_163',['Devicetree SPI API',['../group__devicetree-spi.html',1,'']]],
  ['spi_20driver_20backend_20api_164',['SPI Driver Backend API',['../group__spi__interface__backend.html',1,'']]],
  ['spi_20emulation_20interface_165',['SPI Emulation Interface',['../group__spi__emul__interface.html',1,'']]],
  ['spinlock_166',['Hardware Spinlock',['../group__hwspinlock__interface.html',1,'']]],
  ['spinlock_20api_167',['Devicetree HW spinlock API',['../group__devicetree-hwspinlock.html',1,'']]],
  ['spinlock_20apis_168',['Spinlock APIs',['../group__spinlock__apis.html',1,'']]],
  ['spinlock_20driver_20backend_20api_169',['Hardware Spinlock Driver Backend API',['../group__hwspinlock__interface__backend.html',1,'']]],
  ['spsc_20api_170',['SPSC API',['../group__spsc__lockfree.html',1,'']]],
  ['spsc_20packet_20buffer_20flags_171',['SPSC packet buffer flags',['../group__SPSC__PBUF__FLAGS.html',1,'']]],
  ['spsc_20single_20producer_20single_20consumer_20packet_20buffer_20api_172',['SPSC (Single producer, single consumer) packet buffer API',['../group__spsc__buf.html',1,'']]],
  ['sqe_20flags_173',['RTIO SQE Flags',['../group__rtio__sqe__flags.html',1,'']]],
  ['ssd16xx_174',['SSD16xx',['../group__ssd16xx__interface.html',1,'']]],
  ['st_20morpho_20header_175',['ST Morpho header',['../group__st-morpho-header.html',1,'']]],
  ['st87mxx_20constants_176',['ST87Mxx Constants',['../group__st87mxx__constants.html',1,'']]],
  ['stack_177',['stack',['../group__openthread.html',1,'OpenThread stack'],['../group__subsys__tracing__apis__stack.html',1,'Stack']]],
  ['stack_20apis_178',['stack apis',['../group__stack__apis.html',1,'Stack APIs'],['../group__thread__stack__api.html',1,'Thread Stack APIs']]],
  ['stack_20walk_20apis_179',['Architecture-specific Stack Walk APIs',['../group__arch-stackwalk.html',1,'']]],
  ['standard_20interface_180',['Logger backend standard interface',['../group__log__backend__std.html',1,'']]],
  ['state_20machine_20framework_20api_181',['State Machine Framework API',['../group__smf.html',1,'']]],
  ['states_182',['States',['../group__subsys__pm__states.html',1,'']]],
  ['static_20vrings_20api_183',['IPC service static VRINGs API',['../group__ipc__service__static__vrings__api.html',1,'']]],
  ['statistic_184',['Statistic',['../group__bt__mesh__stat.html',1,'']]],
  ['statistics_20apis_185',['Object Core Statistics APIs',['../group__obj__core__stats__apis.html',1,'']]],
  ['statistics_20library_186',['Network Statistics Library',['../group__net__stats.html',1,'']]],
  ['statistics_20management_187',['Statistics Management',['../group__mcumgr__stat__mgmt.html',1,'']]],
  ['status_188',['status',['../group__midi__ump__sys.html',1,'System common and System Real Time message status'],['../group__midi__ump__stream__status.html',1,'UMP Stream status']]],
  ['status_20codes_189',['HTTP response status codes',['../group__http__status__codes.html',1,'']]],
  ['stepper_190',['Stepper',['../group__stepper__interface.html',1,'']]],
  ['stepper_20controller_191',['Trinamic Stepper Controller',['../group__trinamic__stepper__ctrl.html',1,'']]],
  ['stepper_20hardware_20driver_192',['Stepper Hardware Driver',['../group__stepper__hw__driver.html',1,'']]],
  ['stepper_20hardware_20driver_20driver_20backend_20api_193',['Stepper Hardware Driver Driver Backend API',['../group__stepper__hw__driver__backend.html',1,'']]],
  ['stepper_20motion_20controller_194',['Stepper Motion Controller',['../group__stepper__ctrl.html',1,'']]],
  ['stepper_20motion_20controller_20driver_20backend_20api_195',['Stepper Motion Controller Driver Backend API',['../group__stepper__ctrl__backend.html',1,'']]],
  ['stm32_196',['STM32',['../group__stm32__flash__ex__op.html',1,'']]],
  ['stm32_20gpio_20specific_20flags_197',['STM32 GPIO specific flags',['../group__gpio__interface__stm32.html',1,'']]],
  ['stm32_20sdmmc_198',['STM32 SDMMC',['../group__stm32__sdmmc__disk__interface.html',1,'']]],
  ['stmesp_199',['Coresight STMESP',['../group__stmsp__interface.html',1,'']]],
  ['stmesp_20demultiplexer_20api_200',['Logging frontend STMESP Demultiplexer API',['../group__log__frontend__stpesp__demux__apis.html',1,'']]],
  ['storage_201',['File System Storage',['../group__file__system__storage.html',1,'']]],
  ['storage_20api_202',['PSA Secure Storage API',['../group__psa__secure__storage.html',1,'']]],
  ['storage_20apis_203',['storage apis',['../group__arch-tls.html',1,'Architecture-specific Thread Local Storage APIs'],['../group__nvs__high__level__api.html',1,'Non-volatile Storage APIs'],['../group__storage__apis.html',1,'Storage APIs']]],
  ['storage_20class_20device_20api_204',['USB Mass Storage Class device API',['../group__usbd__msc__device.html',1,'']]],
  ['storage_20data_20structures_205',['Non-volatile Storage Data Structures',['../group__nvs__data__structures.html',1,'']]],
  ['storage_20nvs_206',['Non-volatile Storage (NVS)',['../group__nvs.html',1,'']]],
  ['storage_20zms_207',['Zephyr Memory Storage (ZMS)',['../group__zms.html',1,'']]],
  ['store_20apis_208',['Backing Store APIs',['../group__mem-demand-paging-backing-store.html',1,'']]],
  ['stp_20decoder_20api_209',['STP Decoder API',['../group__mipi__stp__decoder__apis.html',1,'']]],
  ['stream_210',['Bluetooth Mesh BLOB flash stream',['../group__bt__mesh__blob__io__flash.html',1,'']]],
  ['stream_20endpoint_20discovery_20message_20filter_20bits_211',['UMP Stream endpoint discovery message filter bits',['../group__midi__ump__ep__disc.html',1,'']]],
  ['stream_20format_212',['UMP Stream format',['../group__midi__ump__stream__format.html',1,'']]],
  ['stream_20function_20block_20discovery_20message_20filter_20bits_213',['UMP Stream Function Block discovery message filter bits',['../group__midi__ump__fb__disc.html',1,'']]],
  ['stream_20responder_214',['UMP Stream Responder',['../group__ump__stream__responder.html',1,'']]],
  ['stream_20specific_20fields_215',['UMP Stream specific fields',['../group__midi__ump__stream.html',1,'']]],
  ['stream_20status_216',['UMP Stream status',['../group__midi__ump__stream__status.html',1,'']]],
  ['stream_20to_20flash_20interface_217',['Stream to flash interface',['../group__stream__flash.html',1,'']]],
  ['string_20api_218',['Assigned numbers to string API',['../group__bt__audio__to__str.html',1,'']]],
  ['strip_219',['LED Strip',['../group__led__strip__interface.html',1,'']]],
  ['strip_20api_20extensions_220',['Device-specific LED Strip API extensions',['../group__led__strip__interface__ext.html',1,'']]],
  ['strip_20driver_20backend_20api_221',['LED Strip Driver Backend API',['../group__led__strip__interface__backend.html',1,'']]],
  ['structure_20apis_222',['Data Structure APIs',['../group__datastructure__apis.html',1,'']]],
  ['structures_223',['structures',['../group__fcb__data__structures.html',1,'Flash Circular Buffer Data Structures'],['../group__nvs__data__structures.html',1,'Non-volatile Storage Data Structures'],['../group__zms__data__structures.html',1,'ZMS data structures']]],
  ['stuffing_224',['COBS (Consistent Overhead Byte Stuffing)',['../group__cobs.html',1,'']]],
  ['subnet_20configuration_225',['Subnet Configuration',['../group__bt__mesh__cfg__subnet.html',1,'']]],
  ['subsystem_20runtime_226',['Settings subsystem runtime',['../group__settings__rt.html',1,'']]],
  ['subtraction_227',['Vector Subtraction',['../group__math__dsp__basic__sub.html',1,'']]],
  ['support_228',['support',['../group__gptp.html',1,'gPTP support'],['../group__ptp.html',1,'PTP support'],['../group__usb__bos.html',1,'USB BOS support'],['../group__ztest__mock.html',1,'Ztest mocking support']]],
  ['support_20functions_229',['support functions',['../group__dummy.html',1,'Dummy L2/driver Support Functions'],['../group__ethernet__mii.html',1,'Ethernet MII Support Functions'],['../group__ethernet.html',1,'Ethernet Support Functions'],['../group__ppp.html',1,'PPP L2/driver Support Functions'],['../group__virtual.html',1,'Virtual Network Interface Support Functions']]],
  ['swdp_230',['SWDP',['../group__swdp__interface.html',1,'']]],
  ['switch_20architecture_20dsa_231',['Distributed Switch Architecture (DSA)',['../group__dsa__core.html',1,'']]],
  ['sx1509b_232',['SX1509B',['../group__gpio__sx1509b__interface.html',1,'']]],
  ['symbol_20definitions_233',['Exported symbol definitions',['../group__llext__symbols.html',1,'']]],
  ['symbol_20table_20api_234',['Symbol Table API',['../group__symtab__apis.html',1,'']]],
  ['symbols_235',['Network namespace compatibility mode symbols',['../group__net__compat.html',1,'']]],
  ['sync_20options_236',['External Sync options',['../group__adxl355__ext__sync.html',1,'']]],
  ['synchronization_20apis_237',['Time Synchronization APIs',['../group__timeutil__sync__apis.html',1,'']]],
  ['synopsys_20ddr_20controller_20edac_238',['Synopsys DDR controller EDAC',['../group__edac__synopsys__interface.html',1,'']]],
  ['syscall_20apis_239',['User mode and Syscall APIs',['../group__syscall__apis.html',1,'']]],
  ['syscall_20tracing_240',['Syscall Tracing',['../group__subsys__tracing__apis__syscall.html',1,'']]],
  ['syscon_241',['System control (SYSCON)',['../group__syscon__interface.html',1,'']]],
  ['sysrstcr_20reset_20control_242',['SYSRSTCR Reset Control',['../group__focaltech__sysrstcr__resets.html',1,'']]],
  ['system_243',['system',['../group__logger.html',1,'Logger system'],['../group__subsys__pm__sys.html',1,'System']]],
  ['system_20api_244',['Internal and System API',['../group__internal__api.html',1,'']]],
  ['system_20apis_245',['File System APIs',['../group__file__system__api.html',1,'']]],
  ['system_20clock_20apis_246',['System Clock APIs',['../group__clock__apis.html',1,'']]],
  ['system_20common_20and_20system_20real_20time_20message_20status_247',['System common and System Real Time message status',['../group__midi__ump__sys.html',1,'']]],
  ['system_20control_20syscon_248',['System control (SYSCON)',['../group__syscon__interface.html',1,'']]],
  ['system_20initialization_249',['System Initialization',['../group__sys__init.html',1,'']]],
  ['system_20management_250',['File System Management',['../group__mcumgr__fs__mgmt.html',1,'']]],
  ['system_20management_20callbacks_251',['File System Management Callbacks',['../group__mcumgr__callback__api__fs__mgmt.html',1,'']]],
  ['system_20pm_252',['System PM',['../group__subsys__tracing__apis__pm__system.html',1,'']]],
  ['system_20power_20off_253',['System power off',['../group__sys__poweroff.html',1,'']]],
  ['system_20power_20protocol_254',['System Power Protocol',['../group__scmi__system.html',1,'']]],
  ['system_20services_255',['Operating System Services',['../group__os__services.html',1,'']]],
  ['system_20storage_256',['File System Storage',['../group__file__system__storage.html',1,'']]],
  ['system_20timer_20low_20power_20companion_20interface_257',['System Timer Low-power Companion Interface',['../group__clock__lpm.html',1,'']]]
];
