var searchData=
[
  ['handlers_0',['Handlers',['../group__mcumgr__handler__api.html',1,'']]],
  ['hands_20free_20profile_20audio_20gateway_20hfp_20ag_1',['Hands Free Profile - Audio Gateway (HFP-AG)',['../group__bt__hfp__ag.html',1,'']]],
  ['hands_20free_20profile_20hfp_2',['Hands Free Profile (HFP)',['../group__bt__hfp.html',1,'']]],
  ['haptics_3',['Haptics',['../group__haptics__interface.html',1,'']]],
  ['haptics_20api_20extensions_4',['Device-specific Haptics API extensions',['../group__haptics__interface__ext.html',1,'']]],
  ['haptics_20driver_20backend_20api_5',['Haptics Driver Backend API',['../group__haptics__interface__backend.html',1,'']]],
  ['hardware_20driver_6',['Stepper Hardware Driver',['../group__stepper__hw__driver.html',1,'']]],
  ['hardware_20driver_20driver_20backend_20api_7',['Stepper Hardware Driver Driver Backend API',['../group__stepper__hw__driver__backend.html',1,'']]],
  ['hardware_20info_8',['Hardware Info',['../group__hwinfo__interface.html',1,'']]],
  ['hardware_20spinlock_9',['Hardware Spinlock',['../group__hwspinlock__interface.html',1,'']]],
  ['hardware_20spinlock_20driver_20backend_20api_10',['Hardware Spinlock Driver Backend API',['../group__hwspinlock__interface__backend.html',1,'']]],
  ['has_11',['Hearing Access Service (HAS)',['../group__bt__has.html',1,'']]],
  ['hash_12',['Hash',['../group__crypto__hash.html',1,'']]],
  ['hash_20functions_13',['Hash Functions',['../group__hash__functions.html',1,'']]],
  ['hashmap_14',['Hashmap',['../group__hashmap__apis.html',1,'']]],
  ['hashmap_20implementations_15',['Hashmap Implementations',['../group__hashmap__implementations.html',1,'']]],
  ['hawkbit_20autohandler_20api_16',['hawkBit autohandler API',['../group__hawkbit__autohandler.html',1,'']]],
  ['hawkbit_20configuration_20api_17',['hawkBit configuration API',['../group__hawkbit__config.html',1,'']]],
  ['hawkbit_20event_20api_18',['hawkBit event API',['../group__hawkbit__event.html',1,'']]],
  ['hawkbit_20firmware_20over_20the_20air_19',['hawkBit Firmware Over-the-Air',['../group__hawkbit.html',1,'']]],
  ['hci_20',['Bluetooth HCI',['../group__bt__hci__api.html',1,'']]],
  ['hci_20driver_20backend_20api_21',['Bluetooth HCI Driver Backend API',['../group__bt__hci__api__backend.html',1,'']]],
  ['hci_20driver_20extended_20api_22',['BlueNRG HCI driver extended API',['../group__bluenrg__hci__driver.html',1,'']]],
  ['hci_20raw_20channel_23',['HCI RAW channel',['../group__hci__raw.html',1,'']]],
  ['hda_20log_20backend_20api_24',['Intel ADSP HDA log backend API',['../group__log__backend__adsp__hda.html',1,'']]],
  ['hdr_20ddr_20api_25',['I3C HDR DDR API',['../group__i3c__hdr__ddr.html',1,'']]],
  ['header_26',['header',['../group__arduino-mkr-header.html',1,'Arduino MKR header'],['../group__arduino-nano-header.html',1,'Arduino Nano header'],['../group__arduino-header-r3.html',1,'Arduino Uno (R3) header'],['../group__bt__mesh__brg__cfg.html',1,'Bridge Configuration common header'],['../group__mpsc__packet.html',1,'MPSC (Multi producer, single consumer) packet header'],['../group__bt__mesh__sar__cfg.html',1,'SAR Configuration common header'],['../group__st-morpho-header.html',1,'ST Morpho header']]],
  ['headers_27',['GPIO pin headers',['../group__devicetree-gpio-pin-headers.html',1,'']]],
  ['health_20client_20model_28',['Health Client Model',['../group__bt__mesh__health__cli.html',1,'']]],
  ['health_20faults_29',['Health faults',['../group__bt__mesh__health__faults.html',1,'']]],
  ['health_20server_20model_30',['Health Server Model',['../group__bt__mesh__health__srv.html',1,'']]],
  ['heap_31',['Heap',['../group__subsys__tracing__apis__heap.html',1,'']]],
  ['heap_20allocator_32',['Low Level Heap Allocator',['../group__low__level__heap__allocator.html',1,'']]],
  ['heap_20apis_33',['Heap APIs',['../group__heap__apis.html',1,'']]],
  ['heap_20interface_34',['Shared multi-heap interface',['../group__shared__multi__heap.html',1,'']]],
  ['heap_20listener_20apis_35',['Heap Listener APIs',['../group__heap__listener__apis.html',1,'']]],
  ['heap_20management_36',['Heap Management',['../group__heaps.html',1,'']]],
  ['heap_20service_37',['Min-Heap service',['../group__min__heap__apis.html',1,'']]],
  ['heap_20wrapper_38',['Multi-Heap Wrapper',['../group__multi__heap__wrapper.html',1,'']]],
  ['heaps_20based_20on_20memory_20attributes_39',['Memory heaps based on memory attributes',['../group__memory__attr__heap.html',1,'']]],
  ['hearing_20access_20service_20has_40',['Hearing Access Service (HAS)',['../group__bt__has.html',1,'']]],
  ['heart_20rate_20service_20hrs_41',['Heart Rate Service (HRS)',['../group__bt__hrs.html',1,'']]],
  ['heartbeat_42',['Heartbeat',['../group__bt__mesh__heartbeat.html',1,'']]],
  ['helper_20code_43',['I3C Address-related Helper Code',['../group__i3c__addresses.html',1,'']]],
  ['helper_20interface_44',['Cleanup Helper Interface',['../group__cleanup__interface.html',1,'']]],
  ['helper_20macros_45',['LwM2M path helper macros',['../group__lwm2m__path__helpers.html',1,'']]],
  ['helper_20macros_20for_20printing_20q_20values_46',['Helper macros for printing Q values.',['../group__math__printing.html',1,'']]],
  ['helpers_47',['helpers',['../group__regulator__adp5360.html',1,'ADP5360 Devicetree helpers.'],['../group__regulator__axp192.html',1,'AXP192 Devicetree helpers.'],['../group__biometrics__emulator.html',1,'Biometrics emulator test helpers'],['../group__devicetree-generic-bus.html',1,'Bus helpers'],['../group__devicetree-battery.html',1,'Devicetree battery helpers'],['../group__regulator__nxp__vref.html',1,'Devicetree helpers'],['../group__pinctrl__esp32.html',1,'Espressif ESP32 pin control helpers'],['../group__pinctrl__esp32c2.html',1,'Espressif ESP32C2 pin control helpers'],['../group__pinctrl__esp32c3.html',1,'Espressif ESP32C3 pin control helpers'],['../group__pinctrl__esp32c5.html',1,'Espressif ESP32C5 pin control helpers'],['../group__pinctrl__esp32c6.html',1,'Espressif ESP32C6 pin control helpers'],['../group__pinctrl__esp32h2.html',1,'Espressif ESP32H2 pin control helpers'],['../group__pinctrl__esp32s2.html',1,'Espressif ESP32S2 pin control helpers'],['../group__pinctrl__esp32s3.html',1,'Espressif ESP32S3 pin control helpers'],['../group__espressif__pinctrl.html',1,'Espressif pin control helpers'],['../group__ip__4__6.html',1,'IPv4/IPv6 primitives and helpers'],['../group__lldp.html',1,'Link Layer Discovery Protocol definitions and helpers'],['../group__log__backend__multidomain.html',1,'Logger multidomain backend helpers'],['../group__devicetree-map.html',1,'Map helpers'],['../group__regulator__max20335.html',1,'MAX20335 Devicetree helpers.'],['../group__net__timeout.html',1,'Network long timeout primitives and helpers'],['../group__devicetree-generic-id.html',1,'Node identifiers and helpers'],['../group__regulator__npm10xx.html',1,'nPM10xx Devicetree helpers.'],['../group__regulator__npm1100.html',1,'NPM1100 Devicetree helpers.'],['../group__regulator__npm13xx.html',1,'nPM13xx Devicetree helpers.'],['../group__regulator__npm2100.html',1,'NPM2100 Devicetree helpers.'],['../group__regulator__npm6001.html',1,'NPM6001 Devicetree helpers.'],['../group__regulator__nrf5x.html',1,'nRF5X regulator devicetree helpers.'],['../group__reset__controller__nuvoton__m48x.html',1,'Nuvoton M48X Reset controller Devicetree helpers'],['../group__clock__controller__nuvoton__m335x.html',1,'Nuvoton NuMaker controller Devicetree helpers'],['../group__reset__controller__nuvoton__m335x.html',1,'Nuvoton NuMaker controller Devicetree helpers'],['../group__devicetree-nvmem.html',1,'NVMEM Devicetree Helpers'],['../group__sifli__pinctrl.html',1,'SiFli pin control helpers'],['../group__pinctrl__sf32lb52x.html',1,'SiFli SF32LB52x pin control helpers'],['../group__regulator__silabs__dcdc.html',1,'Silabs DCDC devicetree helpers.'],['../group__silabs__pinctrl.html',1,'Silicon Labs pin control helpers'],['../group__clock__control__silabs.html',1,'Silicon Labs Series 2 Devicetree helpers'],['../group__pinctrl__xg21.html',1,'Silicon Labs xG21 pin control helpers'],['../group__pinctrl__xg22.html',1,'Silicon Labs xG22 pin control helpers'],['../group__pinctrl__xg23.html',1,'Silicon Labs xG23 pin control helpers'],['../group__pinctrl__xg24.html',1,'Silicon Labs xG24 pin control helpers'],['../group__pinctrl__xg26.html',1,'Silicon Labs xG26 pin control helpers'],['../group__pinctrl__xg27.html',1,'Silicon Labs xG27 pin control helpers'],['../group__pinctrl__xg28.html',1,'Silicon Labs xG28 pin control helpers'],['../group__pinctrl__xg29.html',1,'Silicon Labs xG29 pin control helpers'],['../group__timeutil__unit__apis.html',1,'Time Units Helpers'],['../group__usb__hid__items.html',1,'USB HID Item helpers'],['../group__devicetree-generic-vendor.html',1,'Vendor and model name helpers'],['../group__vlan__api.html',1,'Virtual LAN definitions and helpers']]],
  ['hfp_48',['Hands Free Profile (HFP)',['../group__bt__hfp.html',1,'']]],
  ['hfp_20ag_49',['Hands Free Profile - Audio Gateway (HFP-AG)',['../group__bt__hfp__ag.html',1,'']]],
  ['hid_20class_20api_50',['USB HID class API',['../group__usb__hid__class.html',1,'']]],
  ['hid_20class_20usb_20specific_20definitions_51',['HID class USB specific definitions',['../group__usb__hid__device__api.html',1,'']]],
  ['hid_20common_20definitions_52',['USB HID common definitions',['../group__usb__hid__definitions.html',1,'']]],
  ['hid_20device_20api_53',['USBD HID device API',['../group__usbd__hid__device.html',1,'']]],
  ['hid_20item_20helpers_54',['USB HID Item helpers',['../group__usb__hid__items.html',1,'']]],
  ['high_20level_20api_55',['LwM2M high-level API',['../group__lwm2m__api.html',1,'']]],
  ['high_20pass_20filter_20corner_20options_56',['High Pass Filter corner options',['../group__adxl355__hpf__corner.html',1,'']]],
  ['hl78xx_20constants_20and_20macros_57',['HL78xx Constants and Macros',['../group__hl78xx__constants.html',1,'']]],
  ['hooks_58',['hooks',['../group__subsys__pm__sys__hooks.html',1,'Hooks'],['../group__subsys__tracing__apis.html',1,'Tracing hooks']]],
  ['host_59',['PCIe Host',['../group__pcie__host__interface.html',1,'']]],
  ['host_20command_20interface_60',['EC Host Command Interface',['../group__ec__host__cmd__interface.html',1,'']]],
  ['host_20controller_61',['USB Host Controller',['../group__uhc__api.html',1,'']]],
  ['host_20core_20api_62',['USB Host Core API',['../group__usb__host__core__api.html',1,'']]],
  ['host_20interface_63',['PCIe Virtual Channel Host Interface',['../group__pcie__vc__host__interface.html',1,'']]],
  ['host_20msi_20interface_64',['PCIe Host MSI Interface',['../group__pcie__host__msi__interface.html',1,'']]],
  ['host_20ptm_20interface_65',['PCIe Host PTM Interface',['../group__pcie__host__ptm__interface.html',1,'']]],
  ['hostname_20library_66',['Network Hostname Library',['../group__net__hostname.html',1,'']]],
  ['hpack_67',['HTTP HPACK',['../group__http__hpack.html',1,'']]],
  ['hrs_68',['Heart Rate Service (HRS)',['../group__bt__hrs.html',1,'']]],
  ['http_20client_20api_69',['HTTP client API',['../group__http__client.html',1,'']]],
  ['http_20hpack_70',['HTTP HPACK',['../group__http__hpack.html',1,'']]],
  ['http_20request_20methods_71',['HTTP request methods',['../group__http__methods.html',1,'']]],
  ['http_20response_20status_20codes_72',['HTTP response status codes',['../group__http__status__codes.html',1,'']]],
  ['http_20server_20api_73',['HTTP server API',['../group__http__server.html',1,'']]],
  ['http_20service_20api_74',['HTTP service API',['../group__http__service.html',1,'']]],
  ['hw_20spinlock_20api_75',['Devicetree HW spinlock API',['../group__devicetree-hwspinlock.html',1,'']]],
  ['hx711_76',['HX711',['../group__hx711__interface.html',1,'']]]
];
