var searchData=
[
  ['i2c_0',['I2C',['../group__i2c__interface.html',1,'']]],
  ['i2c_20eeprom_20target_1',['I2C EEPROM Target',['../group__i2c__eeprom__target__api.html',1,'']]],
  ['i2c_20emulation_20interface_2',['I2C Emulation Interface',['../group__i2c__emul__interface.html',1,'']]],
  ['i2c_20iodev_20flags_3',['RTIO I2C IODEV Flags',['../group__rtio__i2c__flags.html',1,'']]],
  ['i2s_4',['I2S',['../group__i2s__interface.html',1,'']]],
  ['i3c_5',['I3C',['../group__i3c__interface.html',1,'']]],
  ['i3c_20address_20related_20helper_20code_6',['I3C Address-related Helper Code',['../group__i3c__addresses.html',1,'']]],
  ['i3c_20common_20command_20codes_7',['I3C Common Command Codes',['../group__i3c__ccc.html',1,'']]],
  ['i3c_20devicetree_20related_20bits_8',['I3C Devicetree related bits',['../group__i3c__devicetree.html',1,'']]],
  ['i3c_20hdr_20ddr_20api_9',['I3C HDR DDR API',['../group__i3c__hdr__ddr.html',1,'']]],
  ['i3c_20in_20band_20interrupts_10',['I3C In-Band Interrupts',['../group__i3c__ibi.html',1,'']]],
  ['i3c_20iodev_20flags_11',['RTIO I3C IODEV Flags',['../group__rtio__i3c__flags.html',1,'']]],
  ['i3c_20target_20device_20api_12',['I3C Target Device API',['../group__i3c__target__device.html',1,'']]],
  ['i3c_20transfer_20api_13',['I3C Transfer API',['../group__i3c__transfer__api.html',1,'']]],
  ['ias_14',['Immediate Alert Service (IAS)',['../group__bt__ias.html',1,'']]],
  ['iclegend_20s3km1110_15',['Iclegend S3KM1110',['../group__s3km1110__interface.html',1,'']]],
  ['icm42686_20dt_20options_16',['Invensense (TDK) ICM42686 DT Options',['../group__ICM42686.html',1,'']]],
  ['icm42688_20dt_20options_17',['Invensense (TDK) ICM42688 DT Options',['../group__icm42688.html',1,'']]],
  ['icm4268x_20dt_20options_18',['Invensense (TDK) ICM4268X DT Options',['../group__ICM4268X.html',1,'']]],
  ['icm45686_20dt_20options_19',['Invensense (TDK) ICM45686 DT Options',['../group__ICM45686.html',1,'']]],
  ['icmp_20',['ICMP',['../group__icmp.html',1,'']]],
  ['icmsg_20ipc_20library_20api_21',['Icmsg IPC library API',['../group__ipc__icmsg__api.html',1,'']]],
  ['icmsg_20multi_20endpoint_20ipc_20library_20api_22',['Icmsg multi-endpoint IPC library API',['../group__ipc__icmsg__me__api.html',1,'']]],
  ['identification_20profile_20csip_23',['Coordinated Set Identification Profile (CSIP)',['../group__bt__csip.html',1,'']]],
  ['identifier_24',['Bluetooth Content Control Identifier',['../group__bt__ccid.html',1,'']]],
  ['identifiers_25',['identifiers',['../group__focaltech__ft9001__clocks.html',1,'FocalTech FT9001 clock identifiers'],['../group__l2cap__cid.html',1,'L2CAP channel identifiers']]],
  ['identifiers_20and_20helpers_26',['Node identifiers and helpers',['../group__devicetree-generic-id.html',1,'']]],
  ['idling_20apis_27',['CPU Idling APIs',['../group__cpu__idle__apis.html',1,'']]],
  ['ieee_20802_2015_204_20and_20thread_20apis_28',['IEEE 802.15.4 and Thread APIs',['../group__ieee802154.html',1,'']]],
  ['ieee_20802_2015_204_20drivers_29',['IEEE 802.15.4 Drivers',['../group__ieee802154__driver.html',1,'']]],
  ['ieee_20802_2015_204_20l2_30',['IEEE 802.15.4 L2',['../group__ieee802154__l2.html',1,'']]],
  ['ieee_20802_2015_204_20net_20management_31',['IEEE 802.15.4 Net Management',['../group__ieee802154__mgmt.html',1,'']]],
  ['ieee_20802_203_20management_20interface_32',['IEEE 802.3 management interface',['../group__ethernet__mdio.html',1,'']]],
  ['igmp_20api_33',['IGMP API',['../group__igmp.html',1,'']]],
  ['iir_20filter_20options_34',['IIR Filter options.',['../group__bmp581__iir__filter.html',1,'']]],
  ['ilog2_20functions_35',['Math Ilog2 Functions',['../group__math__ilog2.html',1,'']]],
  ['image_20api_36',['Flash image API',['../group__flash__img__api.html',1,'']]],
  ['image_20control_20api_37',['MCUboot image control API',['../group__mcuboot__api.html',1,'']]],
  ['image_20management_38',['Image Management',['../group__mcumgr__img__mgmt.html',1,'']]],
  ['image_20management_20callbacks_39',['Image Management Callbacks',['../group__mcumgr__callback__api__img__mgmt.html',1,'']]],
  ['image_20management_20client_40',['Image Management Client',['../group__mcumgr__img__mgmt__client.html',1,'']]],
  ['imaging_20profile_20bip_41',['Basic Imaging Profile (BIP)',['../group__bt__bip.html',1,'']]],
  ['immediate_20alert_20service_20ias_42',['Immediate Alert Service (IAS)',['../group__bt__ias.html',1,'']]],
  ['implementation_20api_43',['Connection Manager Connectivity Implementation API',['../group__conn__mgr__connectivity__impl.html',1,'']]],
  ['implementations_44',['Hashmap Implementations',['../group__hashmap__implementations.html',1,'']]],
  ['in_20band_20interrupts_45',['I3C In-Band Interrupts',['../group__i3c__ibi.html',1,'']]],
  ['info_46',['Hardware Info',['../group__hwinfo__interface.html',1,'']]],
  ['info_20interface_47',['Bootloader info interface',['../group__bootloader__info__interface.html',1,'']]],
  ['initialization_48',['System Initialization',['../group__sys__init.html',1,'']]],
  ['input_49',['Input',['../group__input__interface.html',1,'']]],
  ['input_20api_20extensions_50',['Device-specific Input API extensions',['../group__input__interface__ext.html',1,'']]],
  ['input_20control_20service_20aics_51',['Audio Input Control Service (AICS)',['../group__bt__aics.html',1,'']]],
  ['input_20event_20definitions_52',['Input Event Definitions',['../group__input__events.html',1,'']]],
  ['inspection_20apis_53',['ELF inspection APIs',['../group__llext__inspect__apis.html',1,'']]],
  ['instance_20based_20devicetree_20apis_54',['Instance-based devicetree APIs',['../group__devicetree-inst.html',1,'']]],
  ['instrumentation_55',['Instrumentation',['../group__instrumentation__api.html',1,'']]],
  ['instruments_20ti_20tmp114_20dt_20options_56',['Texas Instruments (TI) TMP114 DT Options',['../group__tmp114.html',1,'']]],
  ['instruments_20ti_20tmp11x_20dt_20options_57',['Texas Instruments (TI) TMP11X DT Options',['../group__tmp11x.html',1,'']]],
  ['intel_20adsp_20hda_20log_20backend_20api_58',['Intel ADSP HDA log backend API',['../group__log__backend__adsp__hda.html',1,'']]],
  ['intel_20adsp_20mtrace_20log_20backend_20api_59',['Intel ADSP mtrace log backend API',['../group__log__backend__adsp__mtrace.html',1,'']]],
  ['inter_20vm_20shared_20memory_60',['Inter-VM Shared Memory',['../group__ivshmem.html',1,'']]],
  ['interface_61',['interface',['../group__arch-interface.html',1,'Architecture Interface'],['../group__audio__codec__interface.html',1,'Audio Codec Interface'],['../group__boot__mode__interface.html',1,'Boot mode interface'],['../group__bootloader__info__interface.html',1,'Bootloader info interface'],['../group__cache__interface.html',1,'Cache Interface'],['../group__cleanup__interface.html',1,'Cleanup Helper Interface'],['../group__audio__dmic__interface.html',1,'Digital Microphone Interface'],['../group__disk__access__interface.html',1,'Disk Access Interface'],['../group__ec__host__cmd__interface.html',1,'EC Host Command Interface'],['../group__espi__emul__interface.html',1,'eSPI Emulation Interface'],['../group__ethernet__phy.html',1,'Ethernet PHY Interface'],['../group__flash__area__api.html',1,'flash area Interface'],['../group__i2c__emul__interface.html',1,'I2C Emulation Interface'],['../group__ethernet__mdio.html',1,'IEEE 802.3 management interface'],['../group__lcd__interface.html',1,'LCD Interface'],['../group__clock__control__litex__interface.html',1,'LiteX Clock Control driver interface'],['../group__log__backend.html',1,'Logger backend interface'],['../group__log__backend__std.html',1,'Logger backend standard interface'],['../group__memory__attr__interface.html',1,'Memory Attribute Interface'],['../group__mdf__interface__ad559x.html',1,'MFD AD559X interface'],['../group__mdf__interface__axp192.html',1,'MFD AXP192 interface'],['../group__mdf__interface__bd8lb600fs.html',1,'MFD BD8LB600FS interface'],['../group__mdf__interface__max22017.html',1,'MFD MAX22017 interface'],['../group__mfd__interface__npm10xx.html',1,'MFD NPM10XX Interface'],['../group__mfd__interface__npm13xx.html',1,'MFD NPM13XX Interface'],['../group__mdf__interface__npm2100.html',1,'MFD NPM2100 Interface'],['../group__mdf__interface__pca9422.html',1,'MFD PCA9422 Interface'],['../group__mipi__interface.html',1,'MIPI Display interface'],['../group__mspi__emul__interface.html',1,'MSPI Emulation Interface'],['../group__net__offload.html',1,'Network Offloading Interface'],['../group__charger__interface__npm10xx.html',1,'nPM10xx Charger interface'],['../group__sensor__interface__npm10xx.html',1,'nPM10xx Sensor interface'],['../group__pcie__host__msi__interface.html',1,'PCIe Host MSI Interface'],['../group__pcie__host__ptm__interface.html',1,'PCIe Host PTM Interface'],['../group__pcie__vc__host__interface.html',1,'PCIe Virtual Channel Host Interface'],['../group__regulator__parent__interface.html',1,'Regulator Parent Interface'],['../group__settings__backend.html',1,'Settings backend interface'],['../group__shared__multi__heap.html',1,'Shared multi-heap interface'],['../group__spi__emul__interface.html',1,'SPI Emulation Interface'],['../group__stream__flash.html',1,'Stream to flash interface'],['../group__clock__lpm.html',1,'System Timer Low-power Companion Interface'],['../group__uart__emul__interface.html',1,'UART Emulation Interface'],['../group__virtqueue__interface.html',1,'Virtqueue Interface']]],
  ['interface_20abstraction_20layer_62',['Network Interface abstraction layer',['../group__net__if.html',1,'']]],
  ['interface_20library_63',['Virtual Interface Library',['../group__virtual__mgmt.html',1,'']]],
  ['interface_20support_20functions_64',['Virtual Network Interface Support Functions',['../group__virtual.html',1,'']]],
  ['interfaces_65',['Emulator interfaces',['../group__io__emulators.html',1,'']]],
  ['internal_66',['Flash Internal',['../group__flash__internal__interface.html',1,'']]],
  ['internal_20and_20system_20api_67',['Internal and System API',['../group__internal__api.html',1,'']]],
  ['internal_20apis_68',['internal apis',['../group__kernel__mm__internal__apis.html',1,'Kernel Memory Management Internal APIs'],['../group__usermode__internal__apis.html',1,'User Mode Internal APIs'],['../group__xtensa__internal__apis.html',1,'Xtensa Internal APIs']]],
  ['interpolation_20functions_69',['Math Interpolation Functions',['../group__math__interpolation.html',1,'']]],
  ['interrupt_20controller_20api_70',['Devicetree Interrupt Controller API',['../group__devicetree-interrupt__controller.html',1,'']]],
  ['interrupt_20driven_20uart_20api_71',['Interrupt-driven UART API',['../group__uart__interrupt.html',1,'']]],
  ['interrupt_20service_20routine_20apis_72',['Interrupt Service Routine APIs',['../group__isr__apis.html',1,'']]],
  ['interrupts_73',['I3C In-Band Interrupts',['../group__i3c__ibi.html',1,'']]],
  ['interrupts_20property_74',['interrupts property',['../group__devicetree-interrupts-prop.html',1,'']]],
  ['invensense_20tdk_20icm42686_20dt_20options_75',['Invensense (TDK) ICM42686 DT Options',['../group__ICM42686.html',1,'']]],
  ['invensense_20tdk_20icm42688_20dt_20options_76',['Invensense (TDK) ICM42688 DT Options',['../group__icm42688.html',1,'']]],
  ['invensense_20tdk_20icm4268x_20dt_20options_77',['Invensense (TDK) ICM4268X DT Options',['../group__ICM4268X.html',1,'']]],
  ['invensense_20tdk_20icm45686_20dt_20options_78',['Invensense (TDK) ICM45686 DT Options',['../group__ICM45686.html',1,'']]],
  ['io_20channels_20api_79',['Devicetree IO Channels API',['../group__devicetree-io-channels.html',1,'']]],
  ['io_20management_80',['Device memory-mapped IO management',['../group__device-mmio.html',1,'']]],
  ['ioctrl_20pin_20control_81',['FocalTech IOCTRL Pin Control',['../group__focaltech__pinctrl__macros.html',1,'']]],
  ['ioctrl_20register_20offsets_82',['IOCTRL Register Offsets',['../group__focaltech__pinctrl__regs.html',1,'']]],
  ['iodev_20flags_83',['iodev flags',['../group__rtio__i2c__flags.html',1,'RTIO I2C IODEV Flags'],['../group__rtio__i3c__flags.html',1,'RTIO I3C IODEV Flags']]],
  ['ipc_84',['IPC',['../group__ipc.html',1,'']]],
  ['ipc_20backend_85',['Zbus Proxy Agent IPC Backend',['../group__zbus__proxy__agent__ipc__backend.html',1,'']]],
  ['ipc_20library_20api_86',['ipc library api',['../group__ipc__icmsg__api.html',1,'Icmsg IPC library API'],['../group__ipc__icmsg__me__api.html',1,'Icmsg multi-endpoint IPC library API']]],
  ['ipc_20service_20apis_87',['IPC service APIs',['../group__ipc__service__api.html',1,'']]],
  ['ipc_20service_20backend_88',['IPC service backend',['../group__ipc__service__backend.html',1,'']]],
  ['ipc_20service_20rpmsg_20api_89',['IPC service RPMsg API',['../group__ipc__service__rpmsg__api.html',1,'']]],
  ['ipc_20service_20static_20vrings_20api_90',['IPC service static VRINGs API',['../group__ipc__service__static__vrings__api.html',1,'']]],
  ['ipm_91',['IPM',['../group__ipm__interface.html',1,'']]],
  ['ipm_20driver_20backend_20api_92',['IPM Driver Backend API',['../group__ipm__interface__backend.html',1,'']]],
  ['ipsrstcr_20reset_20control_93',['IPSRSTCR Reset Control',['../group__focaltech__ipsrstcr__resets.html',1,'']]],
  ['ipv4_20ipv6_20primitives_20and_20helpers_94',['IPv4/IPv6 primitives and helpers',['../group__ip__4__6.html',1,'']]],
  ['ipv6_20primitives_20and_20helpers_95',['IPv4/IPv6 primitives and helpers',['../group__ip__4__6.html',1,'']]],
  ['irda_20oject_20exchange_20protocol_20obex_96',['IrDA Oject Exchange Protocol (OBEX)',['../group__bt__obex.html',1,'']]],
  ['irq_20apis_97',['Architecture-specific IRQ APIs',['../group__arch-irq.html',1,'']]],
  ['iso_98',['Isochronous channels (ISO)',['../group__bt__iso.html',1,'']]],
  ['iso_20tp_20protocol_99',['CAN ISO-TP Protocol',['../group__can__isotp.html',1,'']]],
  ['isochronous_20channels_20iso_100',['Isochronous channels (ISO)',['../group__bt__iso.html',1,'']]],
  ['it51xxx_101',['IT51XXX',['../group__it51xxx__flash__ex__op.html',1,'']]],
  ['item_102',['item',['../group__subsys__tracing__apis__work__delayable.html',1,'Delayable work item'],['../group__subsys__tracing__apis__work__poll.html',1,'Triggered work item'],['../group__subsys__tracing__apis__work.html',1,'Work item']]],
  ['item_20helpers_103',['USB HID Item helpers',['../group__usb__hid__items.html',1,'']]],
  ['iterable_20sections_20apis_104',['Iterable Sections APIs',['../group__iterable__section__apis.html',1,'']]]
];
