var searchData=
[
  ['c_0',['USB Type-C',['../group__usb__type__c.html',1,'']]],
  ['c_20device_20api_1',['USB-C Device API',['../group____usbc__device__api.html',1,'']]],
  ['c_20port_20controller_20api_2',['USB Type-C Port Controller API',['../group__usb__type__c__port__controller__api.html',1,'']]],
  ['c_20port_20controller_20driver_20backend_20api_3',['USB Type-C Port Controller Driver Backend API',['../group__usb__type__c__port__controller__api__backend.html',1,'']]],
  ['c_20power_20path_20controller_4',['USB Type-C Power Path Controller',['../group__usb__type__c__power__path__controller.html',1,'']]],
  ['c_20vbus_20api_5',['USB-C VBUS API',['../group__usbc__vbus__api.html',1,'']]],
  ['cache_20controller_6',['External Cache Controller',['../group__cache__external__interface.html',1,'']]],
  ['cache_20controllers_7',['Architecture-specific cache controllers.',['../group__arch-cache.html',1,'']]],
  ['cache_20interface_8',['Cache Interface',['../group__cache__interface.html',1,'']]],
  ['call_20control_20client_20apis_9',['CCP Call Control Client APIs',['../group__bt__ccp__call__control__client.html',1,'']]],
  ['call_20control_20profile_20ccp_10',['Call Control Profile (CCP)',['../group__bt__ccp.html',1,'']]],
  ['call_20control_20server_20apis_11',['CCP Call Control Server APIs',['../group__bt__ccp__call__control__server.html',1,'']]],
  ['callback_20api_12',['MSPI callback API',['../group__mspi__callback__api.html',1,'']]],
  ['callbacks_13',['callbacks',['../group__mcumgr__callback__api.html',1,'Callbacks'],['../group__mcumgr__callback__api__enum__mgmt.html',1,'Enumeration Management Callbacks'],['../group__mcumgr__callback__api__fs__mgmt.html',1,'File System Management Callbacks'],['../group__mcumgr__callback__api__img__mgmt.html',1,'Image Management Callbacks'],['../group__mcumgr__callback__api__os__mgmt.html',1,'OS Management Callbacks'],['../group__mcumgr__callback__api__settings__mgmt.html',1,'Settings Management Callbacks']]],
  ['camera_20connector_14',['ArduCam FFC 40-pin camera connector.',['../group__arducam-ffc-40pin.html',1,'']]],
  ['can_15',['CAN',['../group__can__interface.html',1,'']]],
  ['can_20api_16',['Devicetree CAN API',['../group__devicetree-can.html',1,'']]],
  ['can_20controller_17',['CAN Controller',['../group__can__controller.html',1,'']]],
  ['can_20controller_20driver_20backend_20api_18',['CAN Controller Driver Backend API',['../group__can__controller__backend.html',1,'']]],
  ['can_20iso_20tp_20protocol_19',['CAN ISO-TP Protocol',['../group__can__isotp.html',1,'']]],
  ['can_20transceiver_20',['CAN Transceiver',['../group__can__transceiver.html',1,'']]],
  ['cap_21',['Common Audio Profile (CAP)',['../group__bt__cap.html',1,'']]],
  ['capabilities_22',['PCIe Capabilities',['../group__pcie__capabilities.html',1,'']]],
  ['capabilities_20service_20pacs_23',['Published Audio Capabilities Service (PACS)',['../group__bt__pacs.html',1,'']]],
  ['capability_20parsing_20apis_24',['Codec capability parsing APIs',['../group__bt__audio__codec__cap.html',1,'']]],
  ['capture_25',['Network packet capture',['../group__net__capture.html',1,'']]],
  ['cbvprintf_20processing_20flags_26',['cbvprintf processing flags.',['../group__Z__CBVPRINTF__PROCESS__FLAGS.html',1,'']]],
  ['ccp_27',['Call Control Profile (CCP)',['../group__bt__ccp.html',1,'']]],
  ['ccp_20call_20control_20client_20apis_28',['CCP Call Control Client APIs',['../group__bt__ccp__call__control__client.html',1,'']]],
  ['ccp_20call_20control_20server_20apis_29',['CCP Call Control Server APIs',['../group__bt__ccp__call__control__server.html',1,'']]],
  ['cellular_30',['Cellular',['../group__cellular__interface.html',1,'']]],
  ['channel_31',['HCI RAW channel',['../group__hci__raw.html',1,'']]],
  ['channel_20host_20interface_32',['PCIe Virtual Channel Host Interface',['../group__pcie__vc__host__interface.html',1,'']]],
  ['channel_20identifiers_33',['L2CAP channel identifiers',['../group__l2cap__cid.html',1,'']]],
  ['channel_20sounding_20cs_34',['Channel Sounding (CS)',['../group__bt__le__cs.html',1,'']]],
  ['channels_20api_35',['Devicetree IO Channels API',['../group__devicetree-io-channels.html',1,'']]],
  ['channels_20iso_36',['Isochronous channels (ISO)',['../group__bt__iso.html',1,'']]],
  ['character_20framebuffer_37',['Monochrome Character Framebuffer',['../group__monochrome__character__framebuffer.html',1,'']]],
  ['charger_38',['Battery Charger',['../group__charger__interface.html',1,'']]],
  ['charger_20api_20extensions_39',['Device-specific Charger API extensions',['../group__charger__interface__ext.html',1,'']]],
  ['charger_20driver_20backend_20api_40',['Charger Driver Backend API',['../group__charger__interface__backend.html',1,'']]],
  ['charger_20interface_41',['nPM10xx Charger interface',['../group__charger__interface__npm10xx.html',1,'']]],
  ['charging_20bc1_202_42',['Battery Charging (BC1.2)',['../group__b12__interface.html',1,'']]],
  ['chat_43',['Modem Chat',['../group__modem__chat.html',1,'']]],
  ['checks_44',['Existence checks',['../group__devicetree-generic-exist.html',1,'']]],
  ['checksum_45',['Checksum',['../group__checksum.html',1,'']]],
  ['chosen_20nodes_46',['Chosen nodes',['../group__devicetree-generic-chosen.html',1,'']]],
  ['cipher_47',['Cipher',['../group__crypto__cipher.html',1,'']]],
  ['circular_20buffer_20data_20structures_48',['Flash Circular Buffer Data Structures',['../group__fcb__data__structures.html',1,'']]],
  ['circular_20buffer_20fcb_49',['Flash Circular Buffer (FCB)',['../group__fcb.html',1,'']]],
  ['class_202_20device_20api_50',['USB Audio Class 2 device API',['../group__uac2__device.html',1,'']]],
  ['class_20api_51',['USB HID class API',['../group__usb__hid__class.html',1,'']]],
  ['class_20device_20api_52',['class device api',['../group__usbd__msc__device.html',1,'USB Mass Storage Class device API'],['../group__usbd__midi2.html',1,'USB MIDI 2.0 Class device API']]],
  ['class_20usb_20specific_20definitions_53',['HID class USB specific definitions',['../group__usb__hid__device__api.html',1,'']]],
  ['class_20uvc_20device_20api_54',['USB Video Class (UVC) device API',['../group__usbd__uvc.html',1,'']]],
  ['cleanup_20helper_20interface_55',['Cleanup Helper Interface',['../group__cleanup__interface.html',1,'']]],
  ['client_56',['client',['../group__bt__mesh__od__priv__proxy__cli.html',1,'Bluetooth Mesh On-Demand Private GATT Proxy Client'],['../group__bt__mesh__priv__beacon__cli.html',1,'Bluetooth Mesh Private Beacon Client'],['../group__bt__mesh__sol__pdu__rpl__cli.html',1,'Bluetooth Mesh Solicitation PDU RPL Client'],['../group__mcumgr__img__mgmt__client.html',1,'Image Management Client'],['../group__mcumgr__os__mgmt__client.html',1,'OS Management Client'],['../group__mcumgr__smp__client.html',1,'SMP client']]],
  ['client_20api_57',['client api',['../group__coap__client.html',1,'CoAP client API'],['../group__http__client.html',1,'HTTP client API']]],
  ['client_20apis_58',['client apis',['../group__bt__bap__unicast__client.html',1,'BAP Unicast Client APIs'],['../group__bt__ccp__call__control__client.html',1,'CCP Call Control Client APIs'],['../group__bt__gatt__client.html',1,'GATT Client APIs']]],
  ['client_20library_59',['client library',['../group__mqtt__socket.html',1,'MQTT Client library'],['../group__mqtt__sn__socket.html',1,'MQTT-SN Client library'],['../group__tftp__client.html',1,'TFTP Client library']]],
  ['client_20library_20api_60',['FTP client library API',['../group__ftp__client.html',1,'']]],
  ['client_20mcc_61',['Media Control Client (MCC)',['../group__bt__mcc.html',1,'']]],
  ['client_20model_62',['client model',['../group__bt__mesh__sar__cfg__cli.html',1,'Bluetooth Mesh SAR Configuration Client Model'],['../group__bt__mesh__brg__cfg__cli.html',1,'Bridge Configuration Client Model'],['../group__bt__mesh__cfg__cli.html',1,'Configuration Client Model'],['../group__bt__mesh__dfu__cli.html',1,'Firmware Uppdate Client model'],['../group__bt__mesh__health__cli.html',1,'Health Client Model'],['../group__bt__mesh__large__comp__data__cli.html',1,'Large Composition Data Client model'],['../group__bt__mesh__op__agg__cli.html',1,'Opcodes Aggregator Client model'],['../group__bt__mesh__rpr__cli.html',1,'Remote Provisioning Client model']]],
  ['client_20model_20api_63',['Bluetooth Mesh BLOB Transfer Client model API',['../group__bt__mesh__blob__cli.html',1,'']]],
  ['clipping_64',['Vector Clipping',['../group__math__dsp__basic__clip.html',1,'']]],
  ['clkout_20divider_20constants_65',['Renesas RA BSP Clock Clkout Divider Constants',['../group__bsp__clock__clkout.html',1,'']]],
  ['clock_66',['PTP Clock',['../group__ptp__clock__interface.html',1,'']]],
  ['clock_20apis_67',['System Clock APIs',['../group__clock__apis.html',1,'']]],
  ['clock_20clkout_20divider_20constants_68',['Renesas RA BSP Clock Clkout Divider Constants',['../group__bsp__clock__clkout.html',1,'']]],
  ['clock_20control_69',['Clock Control',['../group__clock__control__interface.html',1,'']]],
  ['clock_20control_20driver_20backend_20api_70',['Clock Control Driver Backend API',['../group__clock__control__interface__backend.html',1,'']]],
  ['clock_20control_20driver_20interface_71',['LiteX Clock Control driver interface',['../group__clock__control__litex__interface.html',1,'']]],
  ['clock_20control_20sf32lb_20specifics_72',['Clock Control (SF32LB specifics)',['../group__clock__control__sf32lb.html',1,'']]],
  ['clock_20divider_20generators_73',['Renesas RA Clock Divider Generators',['../group__ra__cgc__div.html',1,'']]],
  ['clock_20identifiers_74',['FocalTech FT9001 clock identifiers',['../group__focaltech__ft9001__clocks.html',1,'']]],
  ['clock_20options_75',['External Clock options',['../group__adxl355__ext__clk.html',1,'']]],
  ['clock_20protocol_76',['Clock Protocol',['../group__scmi__clk.html',1,'']]],
  ['clock_20source_20constants_77',['Renesas RA BSP Clock Source Constants',['../group__bsp__clock__source.html',1,'']]],
  ['clocks_20api_78',['Devicetree Clocks API',['../group__devicetree-clocks.html',1,'']]],
  ['cmux_79',['Modem CMUX',['../group__modem__cmux.html',1,'']]],
  ['co_20processor_80',['FT8xx co-processor',['../group__ft8xx__copro.html',1,'']]],
  ['coap_20client_20api_81',['CoAP client API',['../group__coap__client.html',1,'']]],
  ['coap_20library_82',['COAP Library',['../group__coap.html',1,'']]],
  ['coap_20manager_20events_83',['CoAP Manager Events',['../group__coap__mgmt.html',1,'']]],
  ['coap_20service_20api_84',['CoAP service API',['../group__coap__service.html',1,'']]],
  ['cobs_20consistent_20overhead_20byte_20stuffing_85',['COBS (Consistent Overhead Byte Stuffing)',['../group__cobs.html',1,'']]],
  ['code_86',['I3C Address-related Helper Code',['../group__i3c__addresses.html',1,'']]],
  ['codec_87',['Bluetooth LC3 codec',['../group__bt__lc3.html',1,'']]],
  ['codec_20capability_20parsing_20apis_88',['Codec capability parsing APIs',['../group__bt__audio__codec__cap.html',1,'']]],
  ['codec_20config_20parsing_20apis_89',['Codec config parsing APIs',['../group__bt__audio__codec__cfg.html',1,'']]],
  ['codec_20interface_90',['Audio Codec Interface',['../group__audio__codec__interface.html',1,'']]],
  ['codes_91',['codes',['../group__http__status__codes.html',1,'HTTP response status codes'],['../group__i3c__ccc.html',1,'I3C Common Command Codes'],['../group__rtio__ops.html',1,'RTIO Operation Codes']]],
  ['cold_20junction_20temperature_20resultion_92',['Cold junction temperature resultion',['../group__mcp9600__cold__junction__temp__resolution.html',1,'']]],
  ['command_20codes_93',['I3C Common Command Codes',['../group__i3c__ccc.html',1,'']]],
  ['command_20interface_94',['EC Host Command Interface',['../group__ec__host__cmd__interface.html',1,'']]],
  ['commands_95',['MIDI commands',['../group__midi__ump__cmd.html',1,'']]],
  ['common_20and_20system_20real_20time_20message_20status_96',['System common and System Real Time message status',['../group__midi__ump__sys.html',1,'']]],
  ['common_20audio_20profile_20cap_97',['Common Audio Profile (CAP)',['../group__bt__cap.html',1,'']]],
  ['common_20command_20codes_98',['I3C Common Command Codes',['../group__i3c__ccc.html',1,'']]],
  ['common_20definitions_99',['USB HID common definitions',['../group__usb__hid__definitions.html',1,'']]],
  ['common_20functions_100',['FT8xx common functions',['../group__ft8xx__common.html',1,'']]],
  ['common_20header_101',['common header',['../group__bt__mesh__brg__cfg.html',1,'Bridge Configuration common header'],['../group__bt__mesh__sar__cfg.html',1,'SAR Configuration common header']]],
  ['companion_20interface_102',['System Timer Low-power Companion Interface',['../group__clock__lpm.html',1,'']]],
  ['comparator_103',['Comparator',['../group__comparator__interface.html',1,'']]],
  ['compatibility_20mode_20symbols_104',['Network namespace compatibility mode symbols',['../group__net__compat.html',1,'']]],
  ['compatible_20api_105',['BSD Sockets compatible API',['../group__bsd__sockets.html',1,'']]],
  ['composition_20data_20client_20model_106',['Large Composition Data Client model',['../group__bt__mesh__large__comp__data__cli.html',1,'']]],
  ['composition_20data_20server_20model_107',['Large Composition Data Server model',['../group__bt__mesh__large__comp__data__srv.html',1,'']]],
  ['condition_20variables_20apis_108',['Condition Variables APIs',['../group__condvar__apis.html',1,'']]],
  ['conditional_20variable_109',['Conditional variable',['../group__subsys__tracing__apis__condvar.html',1,'']]],
  ['conditions_110',['conditions',['../group__npf__basic__cond.html',1,'Basic Filter Conditions'],['../group__npf__eth__cond.html',1,'Ethernet Filter Conditions']]],
  ['config_20parsing_20apis_111',['Codec config parsing APIs',['../group__bt__audio__codec__cfg.html',1,'']]],
  ['configuration_112',['configuration',['../group__bt__mesh__cfg__app.html',1,'Application Configuration'],['../group__st87mxx__gnss__configuration.html',1,'GNSS configuration'],['../group__bt__mesh__cfg.html',1,'Runtime Configuration'],['../group__bt__mesh__cfg__subnet.html',1,'Subnet Configuration'],['../group__st87mxx__wscan__configuration.html',1,'WIFI scanning configuration']]],
  ['configuration_20api_113',['hawkBit configuration API',['../group__hawkbit__config.html',1,'']]],
  ['configuration_20client_20model_114',['configuration client model',['../group__bt__mesh__sar__cfg__cli.html',1,'Bluetooth Mesh SAR Configuration Client Model'],['../group__bt__mesh__brg__cfg__cli.html',1,'Bridge Configuration Client Model'],['../group__bt__mesh__cfg__cli.html',1,'Configuration Client Model']]],
  ['configuration_20common_20header_115',['configuration common header',['../group__bt__mesh__brg__cfg.html',1,'Bridge Configuration common header'],['../group__bt__mesh__sar__cfg.html',1,'SAR Configuration common header']]],
  ['configuration_20library_116',['Network Configuration Library',['../group__net__config.html',1,'']]],
  ['configuration_20macros_117',['FocalTech Reset Configuration Macros',['../group__focaltech__reset__macros.html',1,'']]],
  ['configuration_20server_20model_118',['configuration server model',['../group__bt__mesh__sar__cfg__srv.html',1,'Bluetooth Mesh SAR Configuration Server Model'],['../group__bt__mesh__brg__cfg__srv.html',1,'Bridge Configuration Server Model'],['../group__bt__mesh__cfg__srv.html',1,'Configuration Server Model']]],
  ['configurations_119',['Lowe pass filter configurations',['../group__mc3419__lpf__configs.html',1,'']]],
  ['configure_20api_120',['MSPI Configure API',['../group__mspi__configure__api.html',1,'']]],
  ['connection_20management_121',['Connection management',['../group__bt__conn.html',1,'']]],
  ['connection_20manager_20api_122',['Connection Manager API',['../group__conn__mgr.html',1,'']]],
  ['connection_20manager_20connectivity_20api_123',['Connection Manager Connectivity API',['../group__conn__mgr__connectivity.html',1,'']]],
  ['connection_20manager_20connectivity_20bulk_20api_124',['Connection Manager Connectivity Bulk API',['../group__conn__mgr__connectivity__bulk.html',1,'']]],
  ['connection_20manager_20connectivity_20implementation_20api_125',['Connection Manager Connectivity Implementation API',['../group__conn__mgr__connectivity__impl.html',1,'']]],
  ['connectivity_126',['Connectivity',['../group__connectivity.html',1,'']]],
  ['connectivity_20api_127',['Connection Manager Connectivity API',['../group__conn__mgr__connectivity.html',1,'']]],
  ['connectivity_20bulk_20api_128',['Connection Manager Connectivity Bulk API',['../group__conn__mgr__connectivity__bulk.html',1,'']]],
  ['connectivity_20implementation_20api_129',['Connection Manager Connectivity Implementation API',['../group__conn__mgr__connectivity__impl.html',1,'']]],
  ['connector_130',['connector',['../group__dvp-20pin-connector.html',1,'Arducam DVP 20-pin connector'],['../group__arducam-ffc-40pin.html',1,'ArduCam FFC 40-pin camera connector.'],['../group__raspberrypi-csi-connector.html',1,'Raspberry Pi CSI connector']]],
  ['consistent_20overhead_20byte_20stuffing_131',['COBS (Consistent Overhead Byte Stuffing)',['../group__cobs.html',1,'']]],
  ['console_20api_132',['Console API',['../group__console__api.html',1,'']]],
  ['constants_133',['constants',['../group__bsp__clock__clkout.html',1,'Renesas RA BSP Clock Clkout Divider Constants'],['../group__bsp__clock__source.html',1,'Renesas RA BSP Clock Source Constants'],['../group__st87mxx__constants.html',1,'ST87Mxx Constants']]],
  ['constants_20and_20data_20types_134',['ELF constants and data types',['../group__llext__elf.html',1,'']]],
  ['constants_20and_20macros_135',['HL78xx Constants and Macros',['../group__hl78xx__constants.html',1,'']]],
  ['consumer_20packet_20buffer_20api_136',['consumer packet buffer api',['../group__mpsc__buf.html',1,'MPSC (Multi producer, single consumer) packet buffer API'],['../group__spsc__buf.html',1,'SPSC (Single producer, single consumer) packet buffer API']]],
  ['consumer_20packet_20header_137',['MPSC (Multi producer, single consumer) packet header',['../group__mpsc__packet.html',1,'']]],
  ['content_20control_20identifier_138',['Bluetooth Content Control Identifier',['../group__bt__ccid.html',1,'']]],
  ['context_139',['context',['../group__net__context.html',1,'Application network context'],['../group__llext__loader__apis.html',1,'ELF loader context']]],
  ['control_140',['control',['../group__focaltech__ahb3rstcr__resets.html',1,'AHB3RSTCR Reset Control'],['../group__focaltech__arithrstcr__resets.html',1,'ARITHRSTCR Reset Control'],['../group__clock__control__interface.html',1,'Clock Control'],['../group__pinctrl__interface__dynamic.html',1,'Dynamic Pin Control'],['../group__focaltech__eportrstr__resets.html',1,'EPORTRSTR Reset Control'],['../group__focaltech__pinctrl__macros.html',1,'FocalTech IOCTRL Pin Control'],['../group__focaltech__ipsrstcr__resets.html',1,'IPSRSTCR Reset Control'],['../group__focaltech__multirstcr__resets.html',1,'MULTIRSTCR Reset Control'],['../group__pinctrl__interface.html',1,'Pin Control'],['../group__devicetree-pinctrl.html',1,'Pin control'],['../group__focaltech__sysrstcr__resets.html',1,'SYSRSTCR Reset Control']]],
  ['control_20and_20adaptation_20protocol_20l2cap_20for_20br_20edr_141',['Bluetooth Logical Link Control and Adaptation Protocol (L2CAP) for BR/EDR',['../group__bt__l2cap__br.html',1,'']]],
  ['control_20api_142',['control api',['../group__log__ctrl.html',1,'Logger control API'],['../group__mcuboot__api.html',1,'MCUboot image control API']]],
  ['control_20client_20apis_143',['CCP Call Control Client APIs',['../group__bt__ccp__call__control__client.html',1,'']]],
  ['control_20client_20mcc_144',['Media Control Client (MCC)',['../group__bt__mcc.html',1,'']]],
  ['control_20cover_20art_20profile_145',['Audio Video Remote Control Cover Art Profile',['../group__bt__avrcp__cover__art.html',1,'']]],
  ['control_20driver_20backend_20api_146',['Clock Control Driver Backend API',['../group__clock__control__interface__backend.html',1,'']]],
  ['control_20driver_20interface_147',['LiteX Clock Control driver interface',['../group__clock__control__litex__interface.html',1,'']]],
  ['control_20helpers_148',['control helpers',['../group__pinctrl__esp32.html',1,'Espressif ESP32 pin control helpers'],['../group__pinctrl__esp32c2.html',1,'Espressif ESP32C2 pin control helpers'],['../group__pinctrl__esp32c3.html',1,'Espressif ESP32C3 pin control helpers'],['../group__pinctrl__esp32c5.html',1,'Espressif ESP32C5 pin control helpers'],['../group__pinctrl__esp32c6.html',1,'Espressif ESP32C6 pin control helpers'],['../group__pinctrl__esp32h2.html',1,'Espressif ESP32H2 pin control helpers'],['../group__pinctrl__esp32s2.html',1,'Espressif ESP32S2 pin control helpers'],['../group__pinctrl__esp32s3.html',1,'Espressif ESP32S3 pin control helpers'],['../group__espressif__pinctrl.html',1,'Espressif pin control helpers'],['../group__sifli__pinctrl.html',1,'SiFli pin control helpers'],['../group__pinctrl__sf32lb52x.html',1,'SiFli SF32LB52x pin control helpers'],['../group__silabs__pinctrl.html',1,'Silicon Labs pin control helpers'],['../group__pinctrl__xg21.html',1,'Silicon Labs xG21 pin control helpers'],['../group__pinctrl__xg22.html',1,'Silicon Labs xG22 pin control helpers'],['../group__pinctrl__xg23.html',1,'Silicon Labs xG23 pin control helpers'],['../group__pinctrl__xg24.html',1,'Silicon Labs xG24 pin control helpers'],['../group__pinctrl__xg26.html',1,'Silicon Labs xG26 pin control helpers'],['../group__pinctrl__xg27.html',1,'Silicon Labs xG27 pin control helpers'],['../group__pinctrl__xg28.html',1,'Silicon Labs xG28 pin control helpers'],['../group__pinctrl__xg29.html',1,'Silicon Labs xG29 pin control helpers']]],
  ['control_20identifier_149',['Bluetooth Content Control Identifier',['../group__bt__ccid.html',1,'']]],
  ['control_20module_20registers_150',['FocalTech Reset Control Module Registers',['../group__focaltech__reset__regs.html',1,'']]],
  ['control_20profile_20avrcp_151',['Audio Video Remote Control Profile (AVRCP)',['../group__bt__avrcp.html',1,'']]],
  ['control_20profile_20ccp_152',['Call Control Profile (CCP)',['../group__bt__ccp.html',1,'']]],
  ['control_20profile_20micp_153',['Microphone Control Profile (MICP)',['../group__bt__micp.html',1,'']]],
  ['control_20profile_20vcp_154',['Volume Control Profile (VCP)',['../group__bt__vcp.html',1,'']]],
  ['control_20protocol_155',['Pin Control Protocol',['../group__scmi__pinctrl.html',1,'']]],
  ['control_20server_20apis_156',['CCP Call Control Server APIs',['../group__bt__ccp__call__control__server.html',1,'']]],
  ['control_20service_20aics_157',['Audio Input Control Service (AICS)',['../group__bt__aics.html',1,'']]],
  ['control_20service_20mcs_158',['Media Control Service (MCS)',['../group__bt__mcs.html',1,'']]],
  ['control_20service_20vocs_159',['Volume Offset Control Service (VOCS)',['../group__bt__vocs.html',1,'']]],
  ['control_20sf32lb_20specifics_160',['Clock Control (SF32LB specifics)',['../group__clock__control__sf32lb.html',1,'']]],
  ['control_20syscon_161',['System control (SYSCON)',['../group__syscon__interface.html',1,'']]],
  ['controller_162',['controller',['../group__ac057tc1__display__interface.html',1,'AC057TC1 display controller'],['../group__bt__ctrl.html',1,'Bluetooth Controller'],['../group__can__controller.html',1,'CAN Controller'],['../group__cache__external__interface.html',1,'External Cache Controller'],['../group__pcie__controller__interface.html',1,'PCIe Controller'],['../group__reset__controller__interface.html',1,'Reset Controller'],['../group__stepper__ctrl.html',1,'Stepper Motion Controller'],['../group__trinamic__stepper__ctrl.html',1,'Trinamic Stepper Controller'],['../group__udc__api.html',1,'USB Device Controller'],['../group__uhc__api.html',1,'USB Host Controller'],['../group__usb__type__c__power__path__controller.html',1,'USB Type-C Power Path Controller']]],
  ['controller_20api_163',['controller api',['../group__devicetree-interrupt__controller.html',1,'Devicetree Interrupt Controller API'],['../group__devicetree-reset-controller.html',1,'Devicetree Reset Controller API'],['../group__devicetree-wakeup-controller.html',1,'Devicetree WUC Controller API'],['../group____usb__device__controller__api.html',1,'USB Device Controller API'],['../group__usb__type__c__port__controller__api.html',1,'USB Type-C Port Controller API']]],
  ['controller_20devicetree_20helpers_164',['controller devicetree helpers',['../group__reset__controller__nuvoton__m48x.html',1,'Nuvoton M48X Reset controller Devicetree helpers'],['../group__reset__controller__nuvoton__m335x.html',1,'Nuvoton NuMaker controller Devicetree helpers'],['../group__clock__controller__nuvoton__m335x.html',1,'Nuvoton NuMaker controller Devicetree helpers']]],
  ['controller_20driver_20backend_20api_165',['controller driver backend api',['../group__can__controller__backend.html',1,'CAN Controller Driver Backend API'],['../group__stepper__ctrl__backend.html',1,'Stepper Motion Controller Driver Backend API'],['../group__usb__type__c__port__controller__api__backend.html',1,'USB Type-C Port Controller Driver Backend API']]],
  ['controller_20edac_166',['Synopsys DDR controller EDAC',['../group__edac__synopsys__interface.html',1,'']]],
  ['controllers_167',['Architecture-specific cache controllers.',['../group__arch-cache.html',1,'']]],
  ['controls_168',['Video Controls',['../group__video__controls.html',1,'']]],
  ['conversion_20functions_169',['Float/Fixed point shift conversion functions',['../group__math__dsp__utils__shifts.html',1,'']]],
  ['conversions_170',['conversions',['../group__math__dsp__basic__conv__to__float.html',1,'Fixed to Float point conversions'],['../group__math__dsp__basic__conv__to__fixed.html',1,'Float to Fixed point conversions']]],
  ['convert_20flags_171',['Package convert flags',['../group__CBPRINTF__PACKAGE__CONVERT__FLAGS.html',1,'']]],
  ['coordinated_20set_20identification_20profile_20csip_172',['Coordinated Set Identification Profile (CSIP)',['../group__bt__csip.html',1,'']]],
  ['core_20api_173',['core api',['../group____usb__device__core__api.html',1,'USB Device Core API'],['../group__usbd__msg__api.html',1,'USB device core API'],['../group__usbd__api.html',1,'USB device core API'],['../group__usb__host__core__api.html',1,'USB Host Core API']]],
  ['core_20apis_174',['Object Core APIs',['../group__obj__core__apis.html',1,'']]],
  ['core_20dump_20apis_175',['Architecture-specific core dump APIs',['../group__arch-coredump.html',1,'']]],
  ['core_20library_176',['Network Core Library',['../group__net__core.html',1,'']]],
  ['core_20specification_20assigned_20numbers_177',['Core Specification Assigned Numbers',['../group__bt__assigned__numbers__core.html',1,'']]],
  ['core_20statistics_20apis_178',['Object Core Statistics APIs',['../group__obj__core__stats__apis.html',1,'']]],
  ['coredump_20apis_179',['Coredump APIs',['../group__coredump__apis.html',1,'']]],
  ['coredump_20pseudo_20device_180',['Coredump pseudo-device',['../group__coredump__device__interface.html',1,'']]],
  ['coresight_20apis_181',['Coresight APIs',['../group__coresight__apis.html',1,'']]],
  ['coresight_20stmesp_182',['Coresight STMESP',['../group__stmsp__interface.html',1,'']]],
  ['coresight_20trace_20deformatter_183',['Coresight Trace Deformatter',['../group__cs__trace__defmt.html',1,'']]],
  ['corner_20options_184',['High Pass Filter corner options',['../group__adxl355__hpf__corner.html',1,'']]],
  ['count_185',['Temperature average sample count',['../group__tmp11x__os.html',1,'']]],
  ['counter_186',['Counter',['../group__counter__interface.html',1,'']]],
  ['counter_20driver_20backend_20api_187',['Counter Driver Backend API',['../group__counter__interface__backend.html',1,'']]],
  ['cover_20art_20profile_188',['Audio Video Remote Control Cover Art Profile',['../group__bt__avrcp__cover__art.html',1,'']]],
  ['cpu_20frequency_20cpufreq_189',['CPU Frequency (CPUFreq)',['../group__subsys__cpu__freq.html',1,'']]],
  ['cpu_20frequency_20policy_190',['CPU Frequency Policy',['../group__subsys__cpu__freq__policy.html',1,'']]],
  ['cpu_20frequency_20pstate_191',['CPU Frequency pstate',['../group__subsys__cpu__freq__pstate.html',1,'']]],
  ['cpu_20idling_20apis_192',['CPU Idling APIs',['../group__cpu__idle__apis.html',1,'']]],
  ['cpu_20load_193',['CPU Load',['../group__subsys__cpu__load.html',1,'']]],
  ['cpu_20load_20monitor_194',['CPU load monitor',['../group__cpu__load.html',1,'']]],
  ['cpu_20power_20management_195',['CPU Power Management',['../group__power__management__cpu__api.html',1,'']]],
  ['cpufreq_196',['CPU Frequency (CPUFreq)',['../group__subsys__cpu__freq.html',1,'']]],
  ['cqe_20flags_197',['RTIO CQE Flags',['../group__rtio__cqe__flags.html',1,'']]],
  ['crc_198',['CRC',['../group__crc.html',1,'']]],
  ['crc_20driver_20apis_199',['CRC driver APIs',['../group__crc__interface.html',1,'']]],
  ['crc_20driver_20backend_20api_200',['CRC Driver Backend API',['../group__crc__interface__backend.html',1,'']]],
  ['credentials_20library_201',['Wi-Fi credentials library',['../group__wifi__credentials.html',1,'']]],
  ['credentials_20management_202',['TLS credentials management',['../group__tls__credentials.html',1,'']]],
  ['crypto_203',['Crypto',['../group__crypto.html',1,'']]],
  ['cryptography_204',['Cryptography',['../group__bt__crypto.html',1,'']]],
  ['cs_205',['Channel Sounding (CS)',['../group__bt__le__cs.html',1,'']]],
  ['cs40l5x_206',['CS40L5x',['../group__cs40l5x__interface.html',1,'']]],
  ['csi_20connector_207',['Raspberry Pi CSI connector',['../group__raspberrypi-csi-connector.html',1,'']]],
  ['csip_208',['Coordinated Set Identification Profile (CSIP)',['../group__bt__csip.html',1,'']]],
  ['cts_209',['Current Time Service (CTS)',['../group__bt__cts.html',1,'']]],
  ['ctsu_210',['ctsu',['../group__renesas__ra__ctsu__interface.html',1,'Renesas RA CTSU'],['../group__renesas__rx__ctsu__interface.html',1,'Renesas RX CTSU']]],
  ['current_20sense_20amplifier_211',['Current Sense Amplifier',['../group__adc__current__sense__amplifier__interface.html',1,'']]],
  ['current_20sense_20shunt_212',['Current Sense Shunt',['../group__adc__current__sense__shunt__interface.html',1,'']]],
  ['current_20time_20service_20cts_213',['Current Time Service (CTS)',['../group__bt__cts.html',1,'']]],
  ['cy8cmbr3xxx_214',['CY8CMBR3xxx',['../group__cy8cmbr3xxx__interface.html',1,'']]]
];
