var searchData=
[
  ['backed_20emulator_20apis_0',['BC1.2 backed emulator APIs',['../group__b12__emulator__backend.html',1,'']]],
  ['backend_1',['backend',['../group__ipc__service__backend.html',1,'IPC service backend'],['../group__zbus__proxy__agent__ipc__backend.html',1,'Zbus Proxy Agent IPC Backend']]],
  ['backend_20api_2',['backend api',['../group__auxdisplay__interface__backend.html',1,'Auxiliary Display Driver Backend API'],['../group__bbram__emulator__backend.html',1,'BBRAM emulator backend API'],['../group__biometrics__interface__backend.html',1,'Biometrics Driver Backend API'],['../group__bt__hci__api__backend.html',1,'Bluetooth HCI Driver Backend API'],['../group__log__backend__ble.html',1,'Bluetooth log backend API'],['../group__can__controller__backend.html',1,'CAN Controller Driver Backend API'],['../group__charger__interface__backend.html',1,'Charger Driver Backend API'],['../group__clock__control__interface__backend.html',1,'Clock Control Driver Backend API'],['../group__counter__interface__backend.html',1,'Counter Driver Backend API'],['../group__crc__interface__backend.html',1,'CRC Driver Backend API'],['../group__display__interface__backend.html',1,'Display Driver Backend API'],['../group__entropy__interface__backend.html',1,'Entropy Driver Backend API'],['../group__fpga__interface__backend.html',1,'FPGA Driver Backend API'],['../group__gnss__interface__backend.html',1,'GNSS Driver Backend API'],['../group__haptics__interface__backend.html',1,'Haptics Driver Backend API'],['../group__hwspinlock__interface__backend.html',1,'Hardware Spinlock Driver Backend API'],['../group__log__backend__adsp__hda.html',1,'Intel ADSP HDA log backend API'],['../group__log__backend__adsp__mtrace.html',1,'Intel ADSP mtrace log backend API'],['../group__ipm__interface__backend.html',1,'IPM Driver Backend API'],['../group__led__strip__interface__backend.html',1,'LED Strip Driver Backend API'],['../group__mipi__dbi__interface__backend.html',1,'MIPI-DBI Driver Backend API'],['../group__log__backend__mqtt.html',1,'MQTT log backend API'],['../group__log__backend__net.html',1,'Network log backend API'],['../group__opamp__interface__backend.html',1,'OPAMP Driver Backend API'],['../group__otp__interface__backend.html',1,'OTP Driver Backend API'],['../group__pwm__interface__backend.html',1,'PWM Driver Backend API'],['../group__retained__mem__interface__backend.html',1,'Retained Memory Driver Backend API'],['../group__rtc__interface__backend.html',1,'RTC Driver Backend API'],['../group__sensor__interface__backend.html',1,'Sensor Driver Backend API'],['../group__sensor__emulator__backend.html',1,'Sensor emulator backend API'],['../group__spi__interface__backend.html',1,'SPI Driver Backend API'],['../group__stepper__hw__driver__backend.html',1,'Stepper Hardware Driver Driver Backend API'],['../group__stepper__ctrl__backend.html',1,'Stepper Motion Controller Driver Backend API'],['../group__usb__type__c__port__controller__api__backend.html',1,'USB Type-C Port Controller Driver Backend API'],['../group__video__interface__backend.html',1,'Video Driver Backend API'],['../group__watchdog__interface__backend.html',1,'Watchdog Driver Backend API'],['../group__log__backend__ws.html',1,'Websocket log backend API'],['../group__wuc__interface__backend.html',1,'WUC Driver Backend API']]],
  ['backend_20emulator_20apis_3',['Fuel gauge backend emulator APIs',['../group__fuel__gauge__emulator__backend.html',1,'']]],
  ['backend_20helpers_4',['Logger multidomain backend helpers',['../group__log__backend__multidomain.html',1,'']]],
  ['backend_20interface_5',['backend interface',['../group__log__backend.html',1,'Logger backend interface'],['../group__settings__backend.html',1,'Settings backend interface']]],
  ['backend_20standard_20interface_6',['Logger backend standard interface',['../group__log__backend__std.html',1,'']]],
  ['backends_7',['Backends',['../group__ec__host__cmd__backend.html',1,'']]],
  ['backing_20store_20apis_8',['Backing Store APIs',['../group__mem-demand-paging-backing-store.html',1,'']]],
  ['balanced_20red_20black_20tree_9',['Balanced Red/Black Tree',['../group__rbtree__apis.html',1,'']]],
  ['band_20interrupts_10',['I3C In-Band Interrupts',['../group__i3c__ibi.html',1,'']]],
  ['banks_20driver_20apis_11',['Memory Banks Driver APIs',['../group__mm__drv__bank__apis.html',1,'']]],
  ['bap_20broadcast_20apis_12',['BAP Broadcast  APIs',['../group__bt__bap__broadcast.html',1,'']]],
  ['bap_20broadcast_20sink_20apis_13',['BAP Broadcast Sink APIs',['../group__bt__bap__broadcast__sink.html',1,'']]],
  ['bap_20broadcast_20source_20apis_14',['BAP Broadcast Source APIs',['../group__bt__bap__broadcast__source.html',1,'']]],
  ['bap_20lc3_20presets_15',['Basic Audio Profile (BAP) LC3 Presets',['../group__bt__bap__lc3__preset.html',1,'']]],
  ['bap_20unicast_20client_20apis_16',['BAP Unicast Client APIs',['../group__bt__bap__unicast__client.html',1,'']]],
  ['bap_20unicast_20server_20apis_17',['BAP Unicast Server APIs',['../group__bt__bap__unicast__server.html',1,'']]],
  ['barrier_20services_20apis_18',['Barrier Services APIs',['../group__barrier__apis.html',1,'']]],
  ['bas_19',['Battery Service (BAS)',['../group__bt__bas.html',1,'']]],
  ['base_20types_20',['Fatal error base types',['../group__fatal__types.html',1,'']]],
  ['base64_21',['Base64',['../group__base64.html',1,'']]],
  ['based_20devicetree_20apis_22',['Instance-based devicetree APIs',['../group__devicetree-inst.html',1,'']]],
  ['based_20on_20memory_20attributes_23',['Memory heaps based on memory attributes',['../group__memory__attr__heap.html',1,'']]],
  ['basic_20audio_20profile_24',['Bluetooth Basic Audio Profile',['../group__bt__bap.html',1,'']]],
  ['basic_20audio_20profile_20bap_20lc3_20presets_25',['Basic Audio Profile (BAP) LC3 Presets',['../group__bt__bap__lc3__preset.html',1,'']]],
  ['basic_20filter_20conditions_26',['Basic Filter Conditions',['../group__npf__basic__cond.html',1,'']]],
  ['basic_20imaging_20profile_20bip_27',['Basic Imaging Profile (BIP)',['../group__bt__bip.html',1,'']]],
  ['basic_20management_28',['Zephyr Basic Management',['../group__mcumgr__zephyr__basic__mgmt.html',1,'']]],
  ['basic_20math_20functions_29',['Basic Math Functions',['../group__math__dsp__basic.html',1,'']]],
  ['battery_20apis_30',['Battery APIs',['../group__battery__apis.html',1,'']]],
  ['battery_20charger_31',['Battery Charger',['../group__charger__interface.html',1,'']]],
  ['battery_20charging_20bc1_202_32',['Battery Charging (BC1.2)',['../group__b12__interface.html',1,'']]],
  ['battery_20helpers_33',['Devicetree battery helpers',['../group__devicetree-battery.html',1,'']]],
  ['battery_20service_20bas_34',['Battery Service (BAS)',['../group__bt__bas.html',1,'']]],
  ['bbc_20micro_3abit_20display_20apis_35',['BBC micro:bit display APIs',['../group__mb__display.html',1,'']]],
  ['bbram_36',['BBRAM',['../group__bbram__interface.html',1,'']]],
  ['bbram_20emulator_20backend_20api_37',['BBRAM emulator backend API',['../group__bbram__emulator__backend.html',1,'']]],
  ['bc1_202_38',['Battery Charging (BC1.2)',['../group__b12__interface.html',1,'']]],
  ['bc1_202_20backed_20emulator_20apis_39',['BC1.2 backed emulator APIs',['../group__b12__emulator__backend.html',1,'']]],
  ['bd8lb600fs_40',['BD8LB600FS',['../group__bd8lb600fs__interface.html',1,'']]],
  ['bd8lb600fs_20interface_41',['MFD BD8LB600FS interface',['../group__mdf__interface__bd8lb600fs.html',1,'']]],
  ['beacon_20client_42',['Bluetooth Mesh Private Beacon Client',['../group__bt__mesh__priv__beacon__cli.html',1,'']]],
  ['beacon_20server_43',['Bluetooth Mesh Private Beacon Server',['../group__bt__mesh__priv__beacon__srv.html',1,'']]],
  ['bearer_20service_20tbs_44',['Telephone Bearer Service (TBS)',['../group__bt__tbs.html',1,'']]],
  ['benchmarking_20framework_45',['Zephyr Benchmarking Framework',['../group__ztest__benchmark.html',1,'']]],
  ['binary_20descriptor_20definition_46',['Binary Descriptor Definition',['../group__bindesc__define.html',1,'']]],
  ['binary_20descriptor_20reading_47',['Binary Descriptor Reading',['../group__bindesc__read.html',1,'']]],
  ['binary_20descriptors_48',['Binary Descriptors',['../group__bindesc.html',1,'']]],
  ['biometrics_49',['Biometrics',['../group__biometrics__interface.html',1,'']]],
  ['biometrics_20driver_20backend_20api_50',['Biometrics Driver Backend API',['../group__biometrics__interface__backend.html',1,'']]],
  ['biometrics_20emulator_20test_20helpers_51',['Biometrics emulator test helpers',['../group__biometrics__emulator.html',1,'']]],
  ['bip_52',['Basic Imaging Profile (BIP)',['../group__bt__bip.html',1,'']]],
  ['bit_20array_53',['Bit array',['../group__bitarray__apis.html',1,'']]],
  ['bits_54',['bits',['../group__i3c__devicetree.html',1,'I3C Devicetree related bits'],['../group__midi__ump__ep__disc.html',1,'UMP Stream endpoint discovery message filter bits'],['../group__midi__ump__fb__disc.html',1,'UMP Stream Function Block discovery message filter bits']]],
  ['bitwise_20and_55',['Vector bitwise AND',['../group__math__dsp__basic__and.html',1,'']]],
  ['bitwise_20not_56',['Vector bitwise NOT',['../group__math__dsp__basic__not.html',1,'']]],
  ['bitwise_20or_57',['Vector bitwise OR',['../group__math__dsp__basic__or.html',1,'']]],
  ['bitwise_20xor_58',['Vector bitwise XOR',['../group__math__dsp__basic__xor.html',1,'']]],
  ['bl61x_20gpio_20fifo_20wire_20out_59',['Bouffalolab BL61x GPIO FIFO / Wire Out',['../group__gpio__bl61x__wo__interface.html',1,'']]],
  ['black_20tree_60',['Balanced Red/Black Tree',['../group__rbtree__apis.html',1,'']]],
  ['blob_20flash_20stream_61',['Bluetooth Mesh BLOB flash stream',['../group__bt__mesh__blob__io__flash.html',1,'']]],
  ['blob_20model_20api_62',['Bluetooth Mesh BLOB model API',['../group__bt__mesh__blob.html',1,'']]],
  ['blob_20transfer_20client_20model_20api_63',['Bluetooth Mesh BLOB Transfer Client model API',['../group__bt__mesh__blob__cli.html',1,'']]],
  ['blob_20transfer_20server_20model_20api_64',['Bluetooth Mesh BLOB Transfer Server model API',['../group__bt__mesh__blob__srv.html',1,'']]],
  ['block_20discovery_20message_20filter_20bits_65',['UMP Stream Function Block discovery message filter bits',['../group__midi__ump__fb__disc.html',1,'']]],
  ['blocks_20apis_66',['Memory Blocks APIs',['../group__mem__blocks__apis.html',1,'']]],
  ['bluenrg_20hci_20driver_20extended_20api_67',['BlueNRG HCI driver extended API',['../group__bluenrg__hci__driver.html',1,'']]],
  ['bluetooth_20apis_68',['Bluetooth APIs',['../group__bluetooth.html',1,'']]],
  ['bluetooth_20audio_69',['Bluetooth Audio',['../group__bt__audio.html',1,'']]],
  ['bluetooth_20basic_20audio_20profile_70',['Bluetooth Basic Audio Profile',['../group__bt__bap.html',1,'']]],
  ['bluetooth_20content_20control_20identifier_71',['Bluetooth Content Control Identifier',['../group__bt__ccid.html',1,'']]],
  ['bluetooth_20controller_72',['Bluetooth Controller',['../group__bt__ctrl.html',1,'']]],
  ['bluetooth_20gaming_20audio_20profile_73',['Bluetooth Gaming Audio Profile',['../group__bt__gmap.html',1,'']]],
  ['bluetooth_20hci_74',['Bluetooth HCI',['../group__bt__hci__api.html',1,'']]],
  ['bluetooth_20hci_20driver_20backend_20api_75',['Bluetooth HCI Driver Backend API',['../group__bt__hci__api__backend.html',1,'']]],
  ['bluetooth_20lc3_20codec_76',['Bluetooth LC3 codec',['../group__bt__lc3.html',1,'']]],
  ['bluetooth_20log_20backend_20api_77',['Bluetooth log backend API',['../group__log__backend__ble.html',1,'']]],
  ['bluetooth_20logical_20link_20control_20and_20adaptation_20protocol_20l2cap_20for_20br_20edr_78',['Bluetooth Logical Link Control and Adaptation Protocol (L2CAP) for BR/EDR',['../group__bt__l2cap__br.html',1,'']]],
  ['bluetooth_20mesh_79',['Bluetooth Mesh',['../group__bt__mesh.html',1,'']]],
  ['bluetooth_20mesh_20assigned_20numbers_80',['Bluetooth Mesh Assigned Numbers',['../group__bt__assigned__numbers__mesh.html',1,'']]],
  ['bluetooth_20mesh_20blob_20flash_20stream_81',['Bluetooth Mesh BLOB flash stream',['../group__bt__mesh__blob__io__flash.html',1,'']]],
  ['bluetooth_20mesh_20blob_20model_20api_82',['Bluetooth Mesh BLOB model API',['../group__bt__mesh__blob.html',1,'']]],
  ['bluetooth_20mesh_20blob_20transfer_20client_20model_20api_83',['Bluetooth Mesh BLOB Transfer Client model API',['../group__bt__mesh__blob__cli.html',1,'']]],
  ['bluetooth_20mesh_20blob_20transfer_20server_20model_20api_84',['Bluetooth Mesh BLOB Transfer Server model API',['../group__bt__mesh__blob__srv.html',1,'']]],
  ['bluetooth_20mesh_20device_20firmware_20update_85',['Bluetooth Mesh Device Firmware Update',['../group__bt__mesh__dfu.html',1,'']]],
  ['bluetooth_20mesh_20device_20firmware_20update_20dfu_20metadata_86',['Bluetooth Mesh Device Firmware Update (DFU) metadata',['../group__bt__mesh__dfu__metadata.html',1,'']]],
  ['bluetooth_20mesh_20on_20demand_20private_20gatt_20proxy_20client_87',['Bluetooth Mesh On-Demand Private GATT Proxy Client',['../group__bt__mesh__od__priv__proxy__cli.html',1,'']]],
  ['bluetooth_20mesh_20on_20demand_20private_20gatt_20proxy_20server_88',['Bluetooth Mesh On-Demand Private GATT Proxy Server',['../group__bt__mesh__od__priv__proxy__srv.html',1,'']]],
  ['bluetooth_20mesh_20private_20beacon_20client_89',['Bluetooth Mesh Private Beacon Client',['../group__bt__mesh__priv__beacon__cli.html',1,'']]],
  ['bluetooth_20mesh_20private_20beacon_20server_90',['Bluetooth Mesh Private Beacon Server',['../group__bt__mesh__priv__beacon__srv.html',1,'']]],
  ['bluetooth_20mesh_20sar_20configuration_20client_20model_91',['Bluetooth Mesh SAR Configuration Client Model',['../group__bt__mesh__sar__cfg__cli.html',1,'']]],
  ['bluetooth_20mesh_20sar_20configuration_20server_20model_92',['Bluetooth Mesh SAR Configuration Server Model',['../group__bt__mesh__sar__cfg__srv.html',1,'']]],
  ['bluetooth_20mesh_20solicitation_20pdu_20rpl_20client_93',['Bluetooth Mesh Solicitation PDU RPL Client',['../group__bt__mesh__sol__pdu__rpl__cli.html',1,'']]],
  ['bluetooth_20mesh_20solicitation_20pdu_20rpl_20server_94',['Bluetooth Mesh Solicitation PDU RPL Server',['../group__bt__mesh__sol__pdu__rpl__srv.html',1,'']]],
  ['bluetooth_20transport_95',['Bluetooth transport',['../group__mcumgr__transport__bt.html',1,'']]],
  ['bmm350_96',['BMM350',['../group__bmm350__interface.html',1,'']]],
  ['bmp581_97',['BMP581',['../group__bmp581__interface.html',1,'']]],
  ['board_20specific_20timing_20measurement_20apis_98',['Board specific Timing Measurement APIs',['../group__timing__api__board.html',1,'']]],
  ['boot_20mode_20interface_99',['Boot mode interface',['../group__boot__mode__interface.html',1,'']]],
  ['bootloader_20info_20interface_100',['Bootloader info interface',['../group__bootloader__info__interface.html',1,'']]],
  ['bos_20support_101',['USB BOS support',['../group__usb__bos.html',1,'']]],
  ['bouffalolab_20bl61x_20gpio_20fifo_20wire_20out_102',['Bouffalolab BL61x GPIO FIFO / Wire Out',['../group__gpio__bl61x__wo__interface.html',1,'']]],
  ['br_20edr_103',['Bluetooth Logical Link Control and Adaptation Protocol (L2CAP) for BR/EDR',['../group__bt__l2cap__br.html',1,'']]],
  ['bridge_20configuration_20client_20model_104',['Bridge Configuration Client Model',['../group__bt__mesh__brg__cfg__cli.html',1,'']]],
  ['bridge_20configuration_20common_20header_105',['Bridge Configuration common header',['../group__bt__mesh__brg__cfg.html',1,'']]],
  ['bridge_20configuration_20server_20model_106',['Bridge Configuration Server Model',['../group__bt__mesh__brg__cfg__srv.html',1,'']]],
  ['bridge_20fdb_107',['Ethernet bridge FDB',['../group__eth__bridge__fdb.html',1,'']]],
  ['bridging_20api_108',['Ethernet Bridging API',['../group__eth__bridge.html',1,'']]],
  ['broadcast_20apis_109',['BAP Broadcast  APIs',['../group__bt__bap__broadcast.html',1,'']]],
  ['broadcast_20profile_20pbp_110',['Public Broadcast Profile (PBP)',['../group__bt__pbp.html',1,'']]],
  ['broadcast_20sink_20apis_111',['BAP Broadcast Sink APIs',['../group__bt__bap__broadcast__sink.html',1,'']]],
  ['broadcast_20source_20apis_112',['BAP Broadcast Source APIs',['../group__bt__bap__broadcast__source.html',1,'']]],
  ['bsd_20socket_20service_20api_113',['BSD socket service API',['../group__bsd__socket__service.html',1,'']]],
  ['bsd_20sockets_20compatible_20api_114',['BSD Sockets compatible API',['../group__bsd__sockets.html',1,'']]],
  ['bsp_20clock_20clkout_20divider_20constants_115',['Renesas RA BSP Clock Clkout Divider Constants',['../group__bsp__clock__clkout.html',1,'']]],
  ['bsp_20clock_20source_20constants_116',['Renesas RA BSP Clock Source Constants',['../group__bsp__clock__source.html',1,'']]],
  ['buffer_20api_117',['buffer api',['../group__mpsc__buf.html',1,'MPSC (Multi producer, single consumer) packet buffer API'],['../group__pbuf.html',1,'Packed Buffer API'],['../group__spsc__buf.html',1,'SPSC (Single producer, single consumer) packet buffer API']]],
  ['buffer_20apis_118',['Ring Buffer APIs',['../group__ring__buffer__apis.html',1,'']]],
  ['buffer_20data_20structures_119',['Flash Circular Buffer Data Structures',['../group__fcb__data__structures.html',1,'']]],
  ['buffer_20fcb_120',['Flash Circular Buffer (FCB)',['../group__fcb.html',1,'']]],
  ['buffer_20flags_121',['buffer flags',['../group__MPSC__PBUF__FLAGS.html',1,'MPSC packet buffer flags'],['../group__SPSC__PBUF__FLAGS.html',1,'SPSC packet buffer flags']]],
  ['buffer_20library_122',['Network Buffer Library',['../group__net__buf.html',1,'']]],
  ['buffer_20macros_20and_20definitions_123',['USB buffer macros and definitions',['../group__usb__buf.html',1,'']]],
  ['buffers_124',['Data buffers',['../group__bt__buf.html',1,'']]],
  ['bulk_20api_125',['Connection Manager Connectivity Bulk API',['../group__conn__mgr__connectivity__bulk.html',1,'']]],
  ['bus_20helpers_126',['Bus helpers',['../group__devicetree-generic-bus.html',1,'']]],
  ['by_20provided_20rate_127',['decimate sampling rate by provided rate',['../group__mc3419__decimation__rates.html',1,'']]],
  ['byte_20stuffing_128',['COBS (Consistent Overhead Byte Stuffing)',['../group__cobs.html',1,'']]],
  ['byteorder_129',['Byteorder',['../group__bt__byteorder.html',1,'']]]
];
