var searchData=
[
  ['r3_20header_0',['Arduino Uno (R3) header',['../group__arduino-header-r3.html',1,'']]],
  ['r502a_1',['Grow R502A',['../group__grow__r502a__interface.html',1,'']]],
  ['ra_2',['Renesas RA',['../group__ra__flash__ex__op.html',1,'']]],
  ['ra_20bsp_20clock_20clkout_20divider_20constants_3',['Renesas RA BSP Clock Clkout Divider Constants',['../group__bsp__clock__clkout.html',1,'']]],
  ['ra_20bsp_20clock_20source_20constants_4',['Renesas RA BSP Clock Source Constants',['../group__bsp__clock__source.html',1,'']]],
  ['ra_20clock_20divider_20generators_5',['Renesas RA Clock Divider Generators',['../group__ra__cgc__div.html',1,'']]],
  ['ra_20ctsu_6',['Renesas RA CTSU',['../group__renesas__ra__ctsu__interface.html',1,'']]],
  ['random_20function_20apis_7',['Random Function APIs',['../group__random__api.html',1,'']]],
  ['range_8',['Linear Range',['../group__linear__range.html',1,'']]],
  ['range_20options_9',['range options',['../group__adxl355__range.html',1,'Select range options'],['../group__adxl345__range.html',1,'Select range options']]],
  ['ranges_20property_10',['ranges property',['../group__devicetree-ranges-prop.html',1,'']]],
  ['raspberry_20pi_20csi_20connector_11',['Raspberry Pi CSI connector',['../group__raspberrypi-csi-connector.html',1,'']]],
  ['raspberry_20pi_20pico_20pio_12',['Raspberry Pi Pico PIO',['../group__pio__rpi__pico__interface.html',1,'']]],
  ['rate_13',['rate',['../group__tmp11x__odr.html',1,'Temperature output data rate'],['../group__tmp114__odr.html',1,'Temperature output data rate']]],
  ['rate_20by_20provided_20rate_14',['decimate sampling rate by provided rate',['../group__mc3419__decimation__rates.html',1,'']]],
  ['rate_20options_15',['rate options',['../group__ICM42686__ACCEL__DATA__RATE.html',1,'Accelerometer data rate options'],['../group__ICM4268X__ACCEL__DATA__RATE.html',1,'Accelerometer data rate options'],['../group__ICM45686__ACCEL__DATA__RATE.html',1,'Accelerometer data rate options'],['../group__icm42688__accel__data__rate.html',1,'Accelerometer data rate options'],['../group__icm42688__gyro__data__rate.html',1,'Gyroscope data rate options'],['../group__ICM42686__GYRO__DATA__RATE.html',1,'Gyroscope data rate options'],['../group__ICM45686__GYRO__DATA__RATE.html',1,'Gyroscope data rate options'],['../group__ICM4268X__GYRO__DATA__RATE.html',1,'Gyroscope data rate options'],['../group__bmp581__output__data__rate.html',1,'Output data rate options'],['../group__RM3100__ODR.html',1,'Output data rate options'],['../group__adxl355__odr.html',1,'Output Rate options'],['../group__adxl345__odr.html',1,'Output Rate options']]],
  ['rate_20service_20hrs_16',['Heart Rate Service (HRS)',['../group__bt__hrs.html',1,'']]],
  ['raw_20channel_17',['HCI RAW channel',['../group__hci__raw.html',1,'']]],
  ['reading_18',['Binary Descriptor Reading',['../group__bindesc__read.html',1,'']]],
  ['real_20time_20message_20status_19',['System common and System Real Time message status',['../group__midi__ump__sys.html',1,'']]],
  ['realtek_20rts5912_20',['Realtek RTS5912',['../group__rts5912__flash__ex__op.html',1,'']]],
  ['red_20black_20tree_21',['Balanced Red/Black Tree',['../group__rbtree__apis.html',1,'']]],
  ['reference_20api_22',['FT8xx reference API',['../group__ft8xx__reference__api.html',1,'']]],
  ['reg_20property_23',['reg property',['../group__devicetree-reg-prop.html',1,'']]],
  ['region_20macros_24',['region macros',['../group__device-mmio-named.html',1,'Named MMIO region macros'],['../group__device-mmio-single.html',1,'Single MMIO region macros'],['../group__device-mmio-toplevel.html',1,'Top-level MMIO region macros']]],
  ['register_20offsets_25',['IOCTRL Register Offsets',['../group__focaltech__pinctrl__regs.html',1,'']]],
  ['registers_26',['FocalTech Reset Control Module Registers',['../group__focaltech__reset__regs.html',1,'']]],
  ['regulator_27',['Regulator',['../group__regulator__interface.html',1,'']]],
  ['regulator_20devicetree_20helpers_28',['nRF5X regulator devicetree helpers.',['../group__regulator__nrf5x.html',1,'']]],
  ['regulator_20parent_20interface_29',['Regulator Parent Interface',['../group__regulator__parent__interface.html',1,'']]],
  ['related_20bits_30',['I3C Devicetree related bits',['../group__i3c__devicetree.html',1,'']]],
  ['related_20helper_20code_31',['I3C Address-related Helper Code',['../group__i3c__addresses.html',1,'']]],
  ['related_20macros_32',['MSPI Devicetree related macros',['../group__mspi__devicetree.html',1,'']]],
  ['remote_20control_20cover_20art_20profile_33',['Audio Video Remote Control Cover Art Profile',['../group__bt__avrcp__cover__art.html',1,'']]],
  ['remote_20control_20profile_20avrcp_34',['Audio Video Remote Control Profile (AVRCP)',['../group__bt__avrcp.html',1,'']]],
  ['remote_20provisioning_20client_20model_35',['Remote Provisioning Client model',['../group__bt__mesh__rpr__cli.html',1,'']]],
  ['remote_20provisioning_20models_36',['Remote Provisioning models',['../group__bt__mesh__rpr.html',1,'']]],
  ['remote_20provisioning_20server_37',['Remote provisioning server',['../group__bt__mesh__rpr__srv.html',1,'']]],
  ['renesas_20elc_38',['Renesas ELC',['../group__renesas__elc__interface.html',1,'']]],
  ['renesas_20ra_39',['Renesas RA',['../group__ra__flash__ex__op.html',1,'']]],
  ['renesas_20ra_20bsp_20clock_20clkout_20divider_20constants_40',['Renesas RA BSP Clock Clkout Divider Constants',['../group__bsp__clock__clkout.html',1,'']]],
  ['renesas_20ra_20bsp_20clock_20source_20constants_41',['Renesas RA BSP Clock Source Constants',['../group__bsp__clock__source.html',1,'']]],
  ['renesas_20ra_20clock_20divider_20generators_42',['Renesas RA Clock Divider Generators',['../group__ra__cgc__div.html',1,'']]],
  ['renesas_20ra_20ctsu_43',['Renesas RA CTSU',['../group__renesas__ra__ctsu__interface.html',1,'']]],
  ['renesas_20rx_20ctsu_44',['Renesas RX CTSU',['../group__renesas__rx__ctsu__interface.html',1,'']]],
  ['report_20descriptors_45',['Mouse and keyboard report descriptors',['../group__usb__hid__mk__report__desc.html',1,'']]],
  ['representation_46',['Network time representation.',['../group__net__time.html',1,'']]],
  ['representation_20apis_47',['Time Representation APIs',['../group__timeutil__repr__apis.html',1,'']]],
  ['request_20methods_48',['HTTP request methods',['../group__http__methods.html',1,'']]],
  ['reset_20configuration_20macros_49',['FocalTech Reset Configuration Macros',['../group__focaltech__reset__macros.html',1,'']]],
  ['reset_20control_50',['reset control',['../group__focaltech__ahb3rstcr__resets.html',1,'AHB3RSTCR Reset Control'],['../group__focaltech__arithrstcr__resets.html',1,'ARITHRSTCR Reset Control'],['../group__focaltech__eportrstr__resets.html',1,'EPORTRSTR Reset Control'],['../group__focaltech__ipsrstcr__resets.html',1,'IPSRSTCR Reset Control'],['../group__focaltech__multirstcr__resets.html',1,'MULTIRSTCR Reset Control'],['../group__focaltech__sysrstcr__resets.html',1,'SYSRSTCR Reset Control']]],
  ['reset_20control_20module_20registers_51',['FocalTech Reset Control Module Registers',['../group__focaltech__reset__regs.html',1,'']]],
  ['reset_20controller_52',['Reset Controller',['../group__reset__controller__interface.html',1,'']]],
  ['reset_20controller_20api_53',['Devicetree Reset Controller API',['../group__devicetree-reset-controller.html',1,'']]],
  ['reset_20controller_20devicetree_20helpers_54',['Nuvoton M48X Reset controller Devicetree helpers',['../group__reset__controller__nuvoton__m48x.html',1,'']]],
  ['reset_20enable_20disable_20definitions_55',['FocalTech Reset Enable/Disable Definitions',['../group__focaltech__reset__enables.html',1,'']]],
  ['resolution_56',['ADC resolution',['../group__mcp9600__adc__resolution.html',1,'']]],
  ['resolve_20library_57',['DNS Resolve Library',['../group__dns__resolve.html',1,'']]],
  ['responder_58',['UMP Stream Responder',['../group__ump__stream__responder.html',1,'']]],
  ['response_20status_20codes_59',['HTTP response status codes',['../group__http__status__codes.html',1,'']]],
  ['resultion_60',['Cold junction temperature resultion',['../group__mcp9600__cold__junction__temp__resolution.html',1,'']]],
  ['retained_20memory_61',['Retained memory',['../group__retained__mem__interface.html',1,'']]],
  ['retained_20memory_20driver_20backend_20api_62',['Retained Memory Driver Backend API',['../group__retained__mem__interface__backend.html',1,'']]],
  ['retention_20api_63',['Retention API',['../group__retention__api.html',1,'']]],
  ['rfcomm_64',['rfcomm',['../group__bt__goep__transport__rfcomm.html',1,'GOEP transport RFCOMM'],['../group__bt__rfcomm.html',1,'RFCOMM']]],
  ['ring_20buffer_20apis_65',['Ring Buffer APIs',['../group__ring__buffer__apis.html',1,'']]],
  ['routine_20apis_66',['Interrupt Service Routine APIs',['../group__isr__apis.html',1,'']]],
  ['rpl_20client_67',['Bluetooth Mesh Solicitation PDU RPL Client',['../group__bt__mesh__sol__pdu__rpl__cli.html',1,'']]],
  ['rpl_20server_68',['Bluetooth Mesh Solicitation PDU RPL Server',['../group__bt__mesh__sol__pdu__rpl__srv.html',1,'']]],
  ['rpmsg_20api_69',['IPC service RPMsg API',['../group__ipc__service__rpmsg__api.html',1,'']]],
  ['rpmsg_20service_20apis_70',['RPMsg service APIs',['../group__rpmsg__service__api.html',1,'']]],
  ['rtc_71',['RTC',['../group__rtc__interface.html',1,'']]],
  ['rtc_20driver_20backend_20api_72',['RTC Driver Backend API',['../group__rtc__interface__backend.html',1,'']]],
  ['rtc_20ds3231_20legacy_73',['RTC DS3231 (legacy).',['../group__rtc__ds3231__interface.html',1,'']]],
  ['rtio_74',['RTIO',['../group__rtio.html',1,'']]],
  ['rtio_20cqe_20flags_75',['RTIO CQE Flags',['../group__rtio__cqe__flags.html',1,'']]],
  ['rtio_20i2c_20iodev_20flags_76',['RTIO I2C IODEV Flags',['../group__rtio__i2c__flags.html',1,'']]],
  ['rtio_20i3c_20iodev_20flags_77',['RTIO I3C IODEV Flags',['../group__rtio__i3c__flags.html',1,'']]],
  ['rtio_20operation_20codes_78',['RTIO Operation Codes',['../group__rtio__ops.html',1,'']]],
  ['rtio_20priorities_79',['RTIO Priorities',['../group__rtio__sqe__prio.html',1,'']]],
  ['rtio_20sqe_20flags_80',['RTIO SQE Flags',['../group__rtio__sqe__flags.html',1,'']]],
  ['rtio_20tracing_20apis_81',['RTIO Tracing APIs',['../group__subsys__tracing__apis__rtio.html',1,'']]],
  ['rts5912_82',['Realtek RTS5912',['../group__rts5912__flash__ex__op.html',1,'']]],
  ['runtime_83',['runtime',['../group__subsys__pm__device__runtime.html',1,'Device Runtime'],['../group__subsys__tracing__apis__pm__device__runtime.html',1,'PM Device Runtime'],['../group__settings__rt.html',1,'Settings subsystem runtime']]],
  ['runtime_20configuration_84',['Runtime Configuration',['../group__bt__mesh__cfg.html',1,'']]],
  ['rx_20ctsu_85',['Renesas RX CTSU',['../group__renesas__rx__ctsu__interface.html',1,'']]]
];
