var searchData=
[
  ['table_20api_0',['Symbol Table API',['../group__symtab__apis.html',1,'']]],
  ['tag_20protocol_1',['DSA tag protocol',['../group__dsa__tag.html',1,'']]],
  ['target_2',['I2C EEPROM Target',['../group__i2c__eeprom__target__api.html',1,'']]],
  ['target_20device_20api_3',['I3C Target Device API',['../group__i3c__target__device.html',1,'']]],
  ['task_20watchdog_20apis_4',['Task Watchdog APIs',['../group__task__wdt__api.html',1,'']]],
  ['tbs_5',['Telephone Bearer Service (TBS)',['../group__bt__tbs.html',1,'']]],
  ['tcs3400_6',['TCS3400',['../group__tcs3400__interface.html',1,'']]],
  ['tdk_20icm42686_20dt_20options_7',['Invensense (TDK) ICM42686 DT Options',['../group__ICM42686.html',1,'']]],
  ['tdk_20icm42688_20dt_20options_8',['Invensense (TDK) ICM42688 DT Options',['../group__icm42688.html',1,'']]],
  ['tdk_20icm4268x_20dt_20options_9',['Invensense (TDK) ICM4268X DT Options',['../group__ICM4268X.html',1,'']]],
  ['tdk_20icm45686_20dt_20options_10',['Invensense (TDK) ICM45686 DT Options',['../group__ICM45686.html',1,'']]],
  ['tee_11',['TEE',['../group__tee__interface.html',1,'']]],
  ['telephone_20and_20media_20audio_20profile_20tmap_12',['Telephone and Media Audio Profile (TMAP)',['../group__bt__tmap.html',1,'']]],
  ['telephone_20bearer_20service_20tbs_13',['Telephone Bearer Service (TBS)',['../group__bt__tbs.html',1,'']]],
  ['temperature_20average_20sample_20count_14',['Temperature average sample count',['../group__tmp11x__os.html',1,'']]],
  ['temperature_20output_20data_20rate_15',['temperature output data rate',['../group__tmp114__odr.html',1,'Temperature output data rate'],['../group__tmp11x__odr.html',1,'Temperature output data rate']]],
  ['temperature_20resultion_16',['Cold junction temperature resultion',['../group__mcp9600__cold__junction__temp__resolution.html',1,'']]],
  ['test_20helpers_17',['Biometrics emulator test helpers',['../group__biometrics__emulator.html',1,'']]],
  ['testing_18',['Testing',['../group__testing.html',1,'']]],
  ['testing_20framework_20ztest_19',['Zephyr Testing Framework (ZTest)',['../group__ztest.html',1,'']]],
  ['testing_20macros_20',['Ztest testing macros',['../group__ztest__test.html',1,'']]],
  ['texas_20instruments_20ti_20tmp114_20dt_20options_21',['Texas Instruments (TI) TMP114 DT Options',['../group__tmp114.html',1,'']]],
  ['texas_20instruments_20ti_20tmp11x_20dt_20options_22',['Texas Instruments (TI) TMP11X DT Options',['../group__tmp11x.html',1,'']]],
  ['text_20display_23',['Auxiliary (Text) Display',['../group__auxdisplay__interface.html',1,'']]],
  ['tftp_20client_20library_24',['TFTP Client library',['../group__tftp__client.html',1,'']]],
  ['the_20air_25',['the air',['../group__hawkbit.html',1,'hawkBit Firmware Over-the-Air'],['../group__updatehub.html',1,'UpdateHub Firmware Over-the-Air']]],
  ['thermocouple_20type_20selection_26',['Thermocouple type selection',['../group__mcp9600__thermocouple__type.html',1,'']]],
  ['third_20party_27',['Third-party',['../group__third__party.html',1,'']]],
  ['thread_28',['Thread',['../group__subsys__tracing__apis__thread.html',1,'']]],
  ['thread_20analyzer_29',['Thread analyzer',['../group__thread__analyzer.html',1,'']]],
  ['thread_20apis_30',['thread apis',['../group__arch-threads.html',1,'Architecture thread APIs'],['../group__ieee802154.html',1,'IEEE 802.15.4 and Thread APIs'],['../group__thread__apis.html',1,'Thread APIs']]],
  ['thread_20local_20storage_20apis_31',['Architecture-specific Thread Local Storage APIs',['../group__arch-tls.html',1,'']]],
  ['thread_20stack_20apis_32',['Thread Stack APIs',['../group__thread__stack__api.html',1,'']]],
  ['ti_20tmp114_20dt_20options_33',['Texas Instruments (TI) TMP114 DT Options',['../group__tmp114.html',1,'']]],
  ['ti_20tmp11x_20dt_20options_34',['Texas Instruments (TI) TMP11X DT Options',['../group__tmp11x.html',1,'']]],
  ['time_35',['PTP time',['../group__ptp__time.html',1,'']]],
  ['time_20aware_20gpio_36',['Time-aware GPIO',['../group__tgpio__interface.html',1,'']]],
  ['time_20message_20status_37',['System common and System Real Time message status',['../group__midi__ump__sys.html',1,'']]],
  ['time_20programmable_20memory_38',['One Time Programmable Memory',['../group__otp__interface.html',1,'']]],
  ['time_20representation_39',['Network time representation.',['../group__net__time.html',1,'']]],
  ['time_20representation_20apis_40',['Time Representation APIs',['../group__timeutil__repr__apis.html',1,'']]],
  ['time_20service_20cts_41',['Current Time Service (CTS)',['../group__bt__cts.html',1,'']]],
  ['time_20service_20ets_42',['Elapsed Time Service (ETS)',['../group__bt__ets.html',1,'']]],
  ['time_20synchronization_20apis_43',['Time Synchronization APIs',['../group__timeutil__sync__apis.html',1,'']]],
  ['time_20units_20helpers_44',['Time Units Helpers',['../group__timeutil__unit__apis.html',1,'']]],
  ['time_20utility_20apis_45',['Time Utility APIs',['../group__timeutil__apis.html',1,'']]],
  ['timeout_20primitives_20and_20helpers_46',['Network long timeout primitives and helpers',['../group__net__timeout.html',1,'']]],
  ['timer_47',['Timer',['../group__subsys__tracing__apis__timer.html',1,'']]],
  ['timer_20apis_48',['Timer APIs',['../group__timer__apis.html',1,'']]],
  ['timer_20low_20power_20companion_20interface_49',['System Timer Low-power Companion Interface',['../group__clock__lpm.html',1,'']]],
  ['timespec_20utility_20apis_50',['Timespec Utility APIs',['../group__timeutil__timespec__apis.html',1,'']]],
  ['timing_20apis_51',['Architecture timing APIs',['../group__arch-timing.html',1,'']]],
  ['timing_20measurement_20apis_52',['timing measurement apis',['../group__timing__api__arch.html',1,'Arch specific Timing Measurement APIs'],['../group__timing__api__board.html',1,'Board specific Timing Measurement APIs'],['../group__timing__api__soc.html',1,'SoC specific Timing Measurement APIs'],['../group__timing__api.html',1,'Timing Measurement APIs']]],
  ['tlc5971_53',['TLC5971',['../group__tlc5971__interface.html',1,'']]],
  ['tle9104_54',['TLE9104',['../group__tle9104__interface.html',1,'']]],
  ['tls_55',['Socket options for TLS',['../group__secure__sockets__options.html',1,'']]],
  ['tls_20credentials_20management_56',['TLS credentials management',['../group__tls__credentials.html',1,'']]],
  ['tmag5273_57',['TMAG5273',['../group__tmag5273__interface.html',1,'']]],
  ['tmap_58',['Telephone and Media Audio Profile (TMAP)',['../group__bt__tmap.html',1,'']]],
  ['tmp114_20dt_20options_59',['Texas Instruments (TI) TMP114 DT Options',['../group__tmp114.html',1,'']]],
  ['tmp11x_60',['TMP11X',['../group__tmp11x__interface.html',1,'']]],
  ['tmp11x_20dt_20options_61',['Texas Instruments (TI) TMP11X DT Options',['../group__tmp11x.html',1,'']]],
  ['to_20fixed_20point_20conversions_62',['Float to Fixed point conversions',['../group__math__dsp__basic__conv__to__fixed.html',1,'']]],
  ['to_20flash_20interface_63',['Stream to flash interface',['../group__stream__flash.html',1,'']]],
  ['to_20float_20point_20conversions_64',['Fixed to Float point conversions',['../group__math__dsp__basic__conv__to__float.html',1,'']]],
  ['to_20string_20api_65',['Assigned numbers to string API',['../group__bt__audio__to__str.html',1,'']]],
  ['token_20jwt_66',['JSON Web Token (JWT)',['../group__jwt.html',1,'']]],
  ['top_20level_20mmio_20region_20macros_67',['Top-level MMIO region macros',['../group__device-mmio-toplevel.html',1,'']]],
  ['touchscreen_20events_68',['Touchscreen Events',['../group__touch__events.html',1,'']]],
  ['tp_20protocol_69',['CAN ISO-TP Protocol',['../group__can__isotp.html',1,'']]],
  ['trace_20and_20debug_20domain_20apis_70',['Trace and Debug Domain APIs',['../group__log__frontend__stmesp__apis.html',1,'']]],
  ['trace_20deformatter_71',['Coresight Trace Deformatter',['../group__cs__trace__defmt.html',1,'']]],
  ['tracing_72',['tracing',['../group__subsys__tracing__apis__syscall.html',1,'Syscall Tracing'],['../group__subsys__tracing.html',1,'Tracing']]],
  ['tracing_20apis_73',['RTIO Tracing APIs',['../group__subsys__tracing__apis__rtio.html',1,'']]],
  ['tracing_20format_74',['Tracing format',['../group__subsys__tracing__format__apis.html',1,'']]],
  ['tracing_20hooks_75',['Tracing hooks',['../group__subsys__tracing__apis.html',1,'']]],
  ['tracing_20utility_20macros_76',['Tracing utility macros',['../group__subsys__tracing__macros.html',1,'']]],
  ['tracking_77',['tracking',['../group__devicetree-dep-ord.html',1,'Dependency tracking'],['../group__subsys__tracing__object__tracking.html',1,'Object tracking']]],
  ['transceiver_78',['CAN Transceiver',['../group__can__transceiver.html',1,'']]],
  ['transfer_20api_79',['transfer api',['../group__i3c__transfer__api.html',1,'I3C Transfer API'],['../group__mspi__transfer__api.html',1,'MSPI Transfer API']]],
  ['transfer_20client_20model_20api_80',['Bluetooth Mesh BLOB Transfer Client model API',['../group__bt__mesh__blob__cli.html',1,'']]],
  ['transfer_20server_20model_20api_81',['Bluetooth Mesh BLOB Transfer Server model API',['../group__bt__mesh__blob__srv.html',1,'']]],
  ['transfer_20service_20ots_82',['Object Transfer Service (OTS)',['../group__bt__ots.html',1,'']]],
  ['transport_83',['transport',['../group__mcumgr__transport__bt.html',1,'Bluetooth transport'],['../group__mcumgr__transport__dummy.html',1,'Dummy transport'],['../group__mcumgr__transport__serial.html',1,'Serial transport'],['../group__mcumgr__transport__shell.html',1,'Shell transport'],['../group__mcumgr__transport__smp.html',1,'SMP transport'],['../group__scmi__transport.html',1,'Transport'],['../group__mcumgr__transport__udp.html',1,'UDP transport']]],
  ['transport_20l2cap_84',['GOEP transport L2CAP',['../group__bt__goep__transport__l2cap.html',1,'']]],
  ['transport_20layers_85',['Transport layers',['../group__mcumgr__transport.html',1,'']]],
  ['transport_20rfcomm_86',['GOEP transport RFCOMM',['../group__bt__goep__transport__rfcomm.html',1,'']]],
  ['tree_87',['Balanced Red/Black Tree',['../group__rbtree__apis.html',1,'']]],
  ['trickle_20algorithm_20library_88',['Trickle Algorithm Library',['../group__trickle.html',1,'']]],
  ['triggered_20work_20item_89',['Triggered work item',['../group__subsys__tracing__apis__work__poll.html',1,'']]],
  ['trinamic_20stepper_20controller_90',['Trinamic Stepper Controller',['../group__trinamic__stepper__ctrl.html',1,'']]],
  ['type_20c_91',['USB Type-C',['../group__usb__type__c.html',1,'']]],
  ['type_20c_20port_20controller_20api_92',['USB Type-C Port Controller API',['../group__usb__type__c__port__controller__api.html',1,'']]],
  ['type_20c_20port_20controller_20driver_20backend_20api_93',['USB Type-C Port Controller Driver Backend API',['../group__usb__type__c__port__controller__api__backend.html',1,'']]],
  ['type_20c_20power_20path_20controller_94',['USB Type-C Power Path Controller',['../group__usb__type__c__power__path__controller.html',1,'']]],
  ['type_20selection_95',['Thermocouple type selection',['../group__mcp9600__thermocouple__type.html',1,'']]],
  ['types_96',['types',['../group__sensing__datatypes.html',1,'Data Types'],['../group__llext__elf.html',1,'ELF constants and data types'],['../group__fatal__types.html',1,'Fatal error base types'],['../group__midi__ump__mt.html',1,'Message types']]],
  ['types_20sensing_97',['Sensor Types (Sensing)',['../group__sensing__sensor__types.html',1,'']]]
];
