var searchData=
[
  ['value_0',['Vector Absolute Value',['../group__math__dsp__basic__abs.html',1,'']]],
  ['values_1',['Helper macros for printing Q values.',['../group__math__printing.html',1,'']]],
  ['variable_2',['Conditional variable',['../group__subsys__tracing__apis__condvar.html',1,'']]],
  ['variables_20apis_3',['Condition Variables APIs',['../group__condvar__apis.html',1,'']]],
  ['vbus_20api_4',['USB-C VBUS API',['../group__usbc__vbus__api.html',1,'']]],
  ['vcp_5',['Volume Control Profile (VCP)',['../group__bt__vcp.html',1,'']]],
  ['veaa_20x_203_6',['VEAA X-3',['../group__veaa__x__3__interface.html',1,'']]],
  ['vector_20absolute_20value_7',['Vector Absolute Value',['../group__math__dsp__basic__abs.html',1,'']]],
  ['vector_20addition_8',['Vector Addition',['../group__math__dsp__basic__add.html',1,'']]],
  ['vector_20bitwise_20and_9',['Vector bitwise AND',['../group__math__dsp__basic__and.html',1,'']]],
  ['vector_20bitwise_20not_10',['Vector bitwise NOT',['../group__math__dsp__basic__not.html',1,'']]],
  ['vector_20bitwise_20or_11',['Vector bitwise OR',['../group__math__dsp__basic__or.html',1,'']]],
  ['vector_20bitwise_20xor_12',['Vector bitwise XOR',['../group__math__dsp__basic__xor.html',1,'']]],
  ['vector_20clipping_13',['Vector Clipping',['../group__math__dsp__basic__clip.html',1,'']]],
  ['vector_20dot_20product_14',['Vector Dot Product',['../group__math__dsp__basic__dot.html',1,'']]],
  ['vector_20multiplication_15',['Vector Multiplication',['../group__math__dsp__basic__mult.html',1,'']]],
  ['vector_20negate_16',['Vector Negate',['../group__math__dsp__basic__negate.html',1,'']]],
  ['vector_20offset_17',['Vector Offset',['../group__math__dsp__basic__offset.html',1,'']]],
  ['vector_20scale_18',['Vector Scale',['../group__math__dsp__basic__scale.html',1,'']]],
  ['vector_20shift_19',['Vector Shift',['../group__math__dsp__basic__shift.html',1,'']]],
  ['vector_20subtraction_20',['Vector Subtraction',['../group__math__dsp__basic__sub.html',1,'']]],
  ['veml6031_21',['VEML6031',['../group__veml6031__interface.html',1,'']]],
  ['veml6046_22',['VEML6046',['../group__veml6046__interface.html',1,'']]],
  ['veml60xx_23',['VEML60XX',['../group__veml60xx__interface.html',1,'']]],
  ['vendor_20and_20model_20name_20helpers_24',['Vendor and model name helpers',['../group__devicetree-generic-vendor.html',1,'']]],
  ['version_20apis_25',['Version APIs',['../group__version__apis.html',1,'']]],
  ['video_26',['Video',['../group__video__interface.html',1,'']]],
  ['video_20apis_27',['Video APIs',['../group__video__api.html',1,'']]],
  ['video_20class_20uvc_20device_20api_28',['USB Video Class (UVC) device API',['../group__usbd__uvc.html',1,'']]],
  ['video_20controls_29',['Video Controls',['../group__video__controls.html',1,'']]],
  ['video_20driver_20backend_20api_30',['Video Driver Backend API',['../group__video__interface__backend.html',1,'']]],
  ['video_20pixel_20formats_31',['Video pixel formats',['../group__video__pixel__formats.html',1,'']]],
  ['video_20remote_20control_20cover_20art_20profile_32',['Audio Video Remote Control Cover Art Profile',['../group__bt__avrcp__cover__art.html',1,'']]],
  ['video_20remote_20control_20profile_20avrcp_33',['Audio Video Remote Control Profile (AVRCP)',['../group__bt__avrcp.html',1,'']]],
  ['virtio_34',['VIRTIO',['../group__virtio__interface.html',1,'']]],
  ['virtqueue_20interface_35',['Virtqueue Interface',['../group__virtqueue__interface.html',1,'']]],
  ['virtual_20channel_20host_20interface_36',['PCIe Virtual Channel Host Interface',['../group__pcie__vc__host__interface.html',1,'']]],
  ['virtual_20interface_20library_37',['Virtual Interface Library',['../group__virtual__mgmt.html',1,'']]],
  ['virtual_20lan_20definitions_20and_20helpers_38',['Virtual LAN definitions and helpers',['../group__vlan__api.html',1,'']]],
  ['virtual_20network_20interface_20support_20functions_39',['Virtual Network Interface Support Functions',['../group__virtual.html',1,'']]],
  ['vm_20shared_20memory_40',['Inter-VM Shared Memory',['../group__ivshmem.html',1,'']]],
  ['vocs_41',['Volume Offset Control Service (VOCS)',['../group__bt__vocs.html',1,'']]],
  ['volatile_20storage_20apis_42',['Non-volatile Storage APIs',['../group__nvs__high__level__api.html',1,'']]],
  ['volatile_20storage_20data_20structures_43',['Non-volatile Storage Data Structures',['../group__nvs__data__structures.html',1,'']]],
  ['volatile_20storage_20nvs_44',['Non-volatile Storage (NVS)',['../group__nvs.html',1,'']]],
  ['voltage_20divider_45',['Voltage Divider',['../group__adc__voltage__divider__interface.html',1,'']]],
  ['volume_20control_20profile_20vcp_46',['Volume Control Profile (VCP)',['../group__bt__vcp.html',1,'']]],
  ['volume_20offset_20control_20service_20vocs_47',['Volume Offset Control Service (VOCS)',['../group__bt__vocs.html',1,'']]],
  ['vpn_20service_48',['Wireguard VPN service',['../group__wg__vpn__service.html',1,'']]],
  ['vrings_20api_49',['IPC service static VRINGs API',['../group__ipc__service__static__vrings__api.html',1,'']]]
];
