var searchData=
[
  ['dac_0',['DAC',['../group__dac__interface.html',1,'']]],
  ['dac_20api_20extensions_1',['Device-specific DAC API extensions',['../group__dac__interface__ext.html',1,'']]],
  ['dac161s997_2',['DAC161S997',['../group__dac161s997__interface.html',1,'']]],
  ['dai_3',['DAI',['../group__dai__interface.html',1,'']]],
  ['dap_20link_4',['DAP Link',['../group__dap__link__interface.html',1,'']]],
  ['data_20buffers_5',['Data buffers',['../group__bt__buf.html',1,'']]],
  ['data_20client_20model_6',['Large Composition Data Client model',['../group__bt__mesh__large__comp__data__cli.html',1,'']]],
  ['data_20ead_7',['Encrypted Advertising Data (EAD)',['../group__bt__ead.html',1,'']]],
  ['data_20link_20layer_8',['1-Wire data link layer',['../group__w1__data__link.html',1,'']]],
  ['data_20rate_9',['data rate',['../group__tmp11x__odr.html',1,'Temperature output data rate'],['../group__tmp114__odr.html',1,'Temperature output data rate']]],
  ['data_20rate_20options_10',['data rate options',['../group__ICM45686__ACCEL__DATA__RATE.html',1,'Accelerometer data rate options'],['../group__ICM4268X__ACCEL__DATA__RATE.html',1,'Accelerometer data rate options'],['../group__ICM42686__ACCEL__DATA__RATE.html',1,'Accelerometer data rate options'],['../group__icm42688__accel__data__rate.html',1,'Accelerometer data rate options'],['../group__ICM4268X__GYRO__DATA__RATE.html',1,'Gyroscope data rate options'],['../group__icm42688__gyro__data__rate.html',1,'Gyroscope data rate options'],['../group__ICM42686__GYRO__DATA__RATE.html',1,'Gyroscope data rate options'],['../group__ICM45686__GYRO__DATA__RATE.html',1,'Gyroscope data rate options'],['../group__bmp581__output__data__rate.html',1,'Output data rate options'],['../group__RM3100__ODR.html',1,'Output data rate options']]],
  ['data_20server_20model_11',['Large Composition Data Server model',['../group__bt__mesh__large__comp__data__srv.html',1,'']]],
  ['data_20structure_20apis_12',['Data Structure APIs',['../group__datastructure__apis.html',1,'']]],
  ['data_20structures_13',['data structures',['../group__fcb__data__structures.html',1,'Flash Circular Buffer Data Structures'],['../group__nvs__data__structures.html',1,'Non-volatile Storage Data Structures'],['../group__zms__data__structures.html',1,'ZMS data structures']]],
  ['data_20types_14',['data types',['../group__sensing__datatypes.html',1,'Data Types'],['../group__llext__elf.html',1,'ELF constants and data types']]],
  ['datagram_20protocol_20for_20universal_20midi_20packets_15',['User Datagram Protocol for Universal MIDI Packets',['../group__netmidi10.html',1,'']]],
  ['dbi_16',['MIPI-DBI',['../group__mipi__dbi__interface.html',1,'']]],
  ['dbi_20driver_20backend_20api_17',['MIPI-DBI Driver Backend API',['../group__mipi__dbi__interface__backend.html',1,'']]],
  ['dcdc_20devicetree_20helpers_18',['Silabs DCDC devicetree helpers.',['../group__regulator__silabs__dcdc.html',1,'']]],
  ['ddr_20api_19',['I3C HDR DDR API',['../group__i3c__hdr__ddr.html',1,'']]],
  ['ddr_20controller_20edac_20',['Synopsys DDR controller EDAC',['../group__edac__synopsys__interface.html',1,'']]],
  ['debug_21',['Debug',['../group__debug.html',1,'']]],
  ['debug_20domain_20apis_22',['Trace and Debug Domain APIs',['../group__log__frontend__stmesp__apis.html',1,'']]],
  ['decimate_20sampling_20rate_20by_20provided_20rate_23',['decimate sampling rate by provided rate',['../group__mc3419__decimation__rates.html',1,'']]],
  ['decoder_20api_24',['STP Decoder API',['../group__mipi__stp__decoder__apis.html',1,'']]],
  ['defined_20event_25',['User-defined event',['../group__subsys__tracing__apis__named.html',1,'']]],
  ['defines_20and_20assigned_20numbers_26',['Defines and Assigned Numbers',['../group__bt__gap__defines.html',1,'']]],
  ['definition_27',['Binary Descriptor Definition',['../group__bindesc__define.html',1,'']]],
  ['definitions_28',['definitions',['../group__llext__symbols.html',1,'Exported symbol definitions'],['../group__focaltech__reset__enables.html',1,'FocalTech Reset Enable/Disable Definitions'],['../group__usb__hid__device__api.html',1,'HID class USB specific definitions'],['../group__input__events.html',1,'Input Event Definitions'],['../group__midi__ump.html',1,'MIDI2 Universal MIDI Packet definitions'],['../group__usb__buf.html',1,'USB buffer macros and definitions'],['../group__usb__hid__definitions.html',1,'USB HID common definitions']]],
  ['definitions_20and_20helpers_29',['definitions and helpers',['../group__lldp.html',1,'Link Layer Discovery Protocol definitions and helpers'],['../group__vlan__api.html',1,'Virtual LAN definitions and helpers']]],
  ['deformatter_30',['Coresight Trace Deformatter',['../group__cs__trace__defmt.html',1,'']]],
  ['delayable_20work_20item_31',['Delayable work item',['../group__subsys__tracing__apis__work__delayable.html',1,'']]],
  ['delivery_32',['USB Power Delivery',['../group__usb__power__delivery.html',1,'']]],
  ['demand_20paging_33',['Demand Paging',['../group__demand__paging.html',1,'']]],
  ['demand_20paging_20apis_34',['Demand Paging APIs',['../group__mem-demand-paging.html',1,'']]],
  ['demand_20private_20gatt_20proxy_20client_35',['Bluetooth Mesh On-Demand Private GATT Proxy Client',['../group__bt__mesh__od__priv__proxy__cli.html',1,'']]],
  ['demand_20private_20gatt_20proxy_20server_36',['Bluetooth Mesh On-Demand Private GATT Proxy Server',['../group__bt__mesh__od__priv__proxy__srv.html',1,'']]],
  ['demultiplexer_20api_37',['Logging frontend STMESP Demultiplexer API',['../group__log__frontend__stpesp__demux__apis.html',1,'']]],
  ['dependency_20tracking_38',['Dependency tracking',['../group__devicetree-dep-ord.html',1,'']]],
  ['description_20for_20sensor_20alignment_39',['description for sensor alignment',['../group__sensor__axis__align__index__dt.html',1,'Axis description for sensor alignment'],['../group__sensor__axis__align__dt.html',1,'Axis description for sensor alignment']]],
  ['descriptor_20definition_40',['Binary Descriptor Definition',['../group__bindesc__define.html',1,'']]],
  ['descriptor_20reading_41',['Binary Descriptor Reading',['../group__bindesc__read.html',1,'']]],
  ['descriptors_42',['descriptors',['../group__bindesc.html',1,'Binary Descriptors'],['../group__usb__hid__mk__report__desc.html',1,'Mouse and keyboard report descriptors']]],
  ['device_43',['device',['../group__coredump__device__interface.html',1,'Coredump pseudo-device'],['../group__subsys__pm__device.html',1,'Device']]],
  ['device_20address_44',['Device Address',['../group__bt__addr.html',1,'']]],
  ['device_20api_45',['device api',['../group__i3c__target__device.html',1,'I3C Target Device API'],['../group__uac2__device.html',1,'USB Audio Class 2 device API'],['../group__usbd__msc__device.html',1,'USB Mass Storage Class device API'],['../group__usbd__midi2.html',1,'USB MIDI 2.0 Class device API'],['../group__usbd__uvc.html',1,'USB Video Class (UVC) device API'],['../group____usbc__device__api.html',1,'USB-C Device API'],['../group__usbd__hid__device.html',1,'USBD HID device API']]],
  ['device_20controller_46',['USB Device Controller',['../group__udc__api.html',1,'']]],
  ['device_20controller_20api_47',['USB Device Controller API',['../group____usb__device__controller__api.html',1,'']]],
  ['device_20core_20api_48',['device core api',['../group____usb__device__core__api.html',1,'USB Device Core API'],['../group__usbd__api.html',1,'USB device core API'],['../group__usbd__msg__api.html',1,'USB device core API']]],
  ['device_20drivers_49',['Device Drivers',['../group__io__interfaces.html',1,'']]],
  ['device_20firmware_20update_50',['Bluetooth Mesh Device Firmware Update',['../group__bt__mesh__dfu.html',1,'']]],
  ['device_20firmware_20update_20dfu_20metadata_51',['Bluetooth Mesh Device Firmware Update (DFU) metadata',['../group__bt__mesh__dfu__metadata.html',1,'']]],
  ['device_20management_52',['Device Management',['../group__device__mgmt.html',1,'']]],
  ['device_20memory_20mapped_20io_20management_53',['Device memory-mapped IO management',['../group__device-mmio.html',1,'']]],
  ['device_20model_54',['Device Model',['../group__device__model.html',1,'']]],
  ['device_20runtime_55',['device runtime',['../group__subsys__pm__device__runtime.html',1,'Device Runtime'],['../group__subsys__tracing__apis__pm__device__runtime.html',1,'PM Device Runtime']]],
  ['device_20specific_20adc_20api_20extensions_56',['Device-specific ADC API extensions',['../group__adc__interface__ext.html',1,'']]],
  ['device_20specific_20charger_20api_20extensions_57',['Device-specific Charger API extensions',['../group__charger__interface__ext.html',1,'']]],
  ['device_20specific_20dac_20api_20extensions_58',['Device-specific DAC API extensions',['../group__dac__interface__ext.html',1,'']]],
  ['device_20specific_20disk_20access_20api_20extensions_59',['Device-specific Disk Access API extensions',['../group__disk__driver__interface__ext.html',1,'']]],
  ['device_20specific_20display_20api_20extensions_60',['Device-specific Display API extensions',['../group__display__interface__ext.html',1,'']]],
  ['device_20specific_20edac_20api_20extensions_61',['Device-specific EDAC API extensions',['../group__edac__interface__ext.html',1,'']]],
  ['device_20specific_20gpio_20api_20extensions_62',['Device-specific GPIO API extensions',['../group__gpio__interface__ext.html',1,'']]],
  ['device_20specific_20haptics_20api_20extensions_63',['Device-specific Haptics API extensions',['../group__haptics__interface__ext.html',1,'']]],
  ['device_20specific_20input_20api_20extensions_64',['Device-specific Input API extensions',['../group__input__interface__ext.html',1,'']]],
  ['device_20specific_20led_20strip_20api_20extensions_65',['Device-specific LED Strip API extensions',['../group__led__strip__interface__ext.html',1,'']]],
  ['device_20specific_20pwm_20api_20extensions_66',['Device-specific PWM API extensions',['../group__pwm__interface__ext.html',1,'']]],
  ['device_20specific_20sensor_20api_20extensions_67',['Device-specific Sensor API extensions',['../group__sensor__interface__ext.html',1,'']]],
  ['device_20update_20api_68',['USB DFU device update API',['../group__usbd__dfu.html',1,'']]],
  ['devices_69',['devices',['../group__misc__interfaces.html',1,'Miscellaneous Devices'],['../group__mfd__interfaces.html',1,'Multi-function Devices'],['../group__offloaded__netdev.html',1,'Offloaded Net Devices']]],
  ['devicetree_70',['Devicetree',['../group__devicetree.html',1,'']]],
  ['devicetree_20apis_71',['Instance-based devicetree APIs',['../group__devicetree-inst.html',1,'']]],
  ['devicetree_20battery_20helpers_72',['Devicetree battery helpers',['../group__devicetree-battery.html',1,'']]],
  ['devicetree_20can_20api_73',['Devicetree CAN API',['../group__devicetree-can.html',1,'']]],
  ['devicetree_20clocks_20api_74',['Devicetree Clocks API',['../group__devicetree-clocks.html',1,'']]],
  ['devicetree_20display_20api_75',['Devicetree Display API',['../group__devicetree-display.html',1,'']]],
  ['devicetree_20dma_20api_76',['Devicetree DMA API',['../group__devicetree-dmas.html',1,'']]],
  ['devicetree_20fixed_20partition_20api_77',['Devicetree Fixed Partition API',['../group__devicetree-fixed-partition.html',1,'']]],
  ['devicetree_20gpio_20api_78',['Devicetree GPIO API',['../group__devicetree-gpio.html',1,'']]],
  ['devicetree_20helpers_79',['devicetree helpers',['../group__regulator__adp5360.html',1,'ADP5360 Devicetree helpers.'],['../group__regulator__axp192.html',1,'AXP192 Devicetree helpers.'],['../group__regulator__nxp__vref.html',1,'Devicetree helpers'],['../group__regulator__max20335.html',1,'MAX20335 Devicetree helpers.'],['../group__regulator__npm10xx.html',1,'nPM10xx Devicetree helpers.'],['../group__regulator__npm1100.html',1,'NPM1100 Devicetree helpers.'],['../group__regulator__npm13xx.html',1,'nPM13xx Devicetree helpers.'],['../group__regulator__npm2100.html',1,'NPM2100 Devicetree helpers.'],['../group__regulator__npm6001.html',1,'NPM6001 Devicetree helpers.'],['../group__regulator__nrf5x.html',1,'nRF5X regulator devicetree helpers.'],['../group__reset__controller__nuvoton__m48x.html',1,'Nuvoton M48X Reset controller Devicetree helpers'],['../group__reset__controller__nuvoton__m335x.html',1,'Nuvoton NuMaker controller Devicetree helpers'],['../group__clock__controller__nuvoton__m335x.html',1,'Nuvoton NuMaker controller Devicetree helpers'],['../group__devicetree-nvmem.html',1,'NVMEM Devicetree Helpers'],['../group__regulator__silabs__dcdc.html',1,'Silabs DCDC devicetree helpers.'],['../group__clock__control__silabs.html',1,'Silicon Labs Series 2 Devicetree helpers']]],
  ['devicetree_20hw_20spinlock_20api_80',['Devicetree HW spinlock API',['../group__devicetree-hwspinlock.html',1,'']]],
  ['devicetree_20interrupt_20controller_20api_81',['Devicetree Interrupt Controller API',['../group__devicetree-interrupt__controller.html',1,'']]],
  ['devicetree_20io_20channels_20api_82',['Devicetree IO Channels API',['../group__devicetree-io-channels.html',1,'']]],
  ['devicetree_20mapped_20partition_20api_83',['Devicetree Mapped Partition API',['../group__devicetree-mapped-partition.html',1,'']]],
  ['devicetree_20mbox_20api_84',['Devicetree MBOX API',['../group__devicetree-mbox.html',1,'']]],
  ['devicetree_20partition_20api_85',['Devicetree Partition API',['../group__devicetree-partition.html',1,'']]],
  ['devicetree_20port_20endpoint_20api_86',['Devicetree Port Endpoint API',['../group__devicetree-port-endpoint.html',1,'']]],
  ['devicetree_20pwms_20api_87',['Devicetree PWMs API',['../group__devicetree-pwms.html',1,'']]],
  ['devicetree_20related_20bits_88',['I3C Devicetree related bits',['../group__i3c__devicetree.html',1,'']]],
  ['devicetree_20related_20macros_89',['MSPI Devicetree related macros',['../group__mspi__devicetree.html',1,'']]],
  ['devicetree_20reset_20controller_20api_90',['Devicetree Reset Controller API',['../group__devicetree-reset-controller.html',1,'']]],
  ['devicetree_20spi_20api_91',['Devicetree SPI API',['../group__devicetree-spi.html',1,'']]],
  ['devicetree_20wuc_20controller_20api_92',['Devicetree WUC Controller API',['../group__devicetree-wakeup-controller.html',1,'']]],
  ['devmux_93',['Devmux',['../group__demux__interface.html',1,'']]],
  ['dfu_20device_20update_20api_94',['USB DFU device update API',['../group__usbd__dfu.html',1,'']]],
  ['dfu_20metadata_95',['Bluetooth Mesh Device Firmware Update (DFU) metadata',['../group__bt__mesh__dfu__metadata.html',1,'']]],
  ['dhcpv4_96',['DHCPv4',['../group__dhcpv4.html',1,'']]],
  ['dhcpv4_20server_97',['DHCPv4 server',['../group__dhcpv4__server.html',1,'']]],
  ['dhcpv6_98',['DHCPv6',['../group__dhcpv6.html',1,'']]],
  ['digital_20microphone_20interface_99',['Digital Microphone Interface',['../group__audio__dmic__interface.html',1,'']]],
  ['digital_20signal_20processing_100',['DSP (Digital Signal Processing)',['../group__math__dsp.html',1,'']]],
  ['disable_20definitions_101',['FocalTech Reset Enable/Disable Definitions',['../group__focaltech__reset__enables.html',1,'']]],
  ['discovery_102',['DNS Service Discovery',['../group__dns__sd.html',1,'']]],
  ['discovery_20api_103',['Multicast Listener Discovery API',['../group__mld.html',1,'']]],
  ['discovery_20message_20filter_20bits_104',['discovery message filter bits',['../group__midi__ump__ep__disc.html',1,'UMP Stream endpoint discovery message filter bits'],['../group__midi__ump__fb__disc.html',1,'UMP Stream Function Block discovery message filter bits']]],
  ['discovery_20protocol_20definitions_20and_20helpers_105',['Link Layer Discovery Protocol definitions and helpers',['../group__lldp.html',1,'']]],
  ['discovery_20protocol_20sdp_106',['Service Discovery Protocol (SDP)',['../group__bt__sdp.html',1,'']]],
  ['disjoint_20set_107',['Disjoint-set',['../group__union__find__apis.html',1,'']]],
  ['disk_20access_108',['Disk Access',['../group__disk__driver__interface.html',1,'']]],
  ['disk_20access_20api_20extensions_109',['Device-specific Disk Access API extensions',['../group__disk__driver__interface__ext.html',1,'']]],
  ['disk_20access_20interface_110',['Disk Access Interface',['../group__disk__access__interface.html',1,'']]],
  ['display_111',['display',['../group__auxdisplay__interface.html',1,'Auxiliary (Text) Display'],['../group__display__interface.html',1,'Display'],['../group__grove__display.html',1,'Grove display']]],
  ['display_20api_112',['Devicetree Display API',['../group__devicetree-display.html',1,'']]],
  ['display_20api_20extensions_113',['Device-specific Display API extensions',['../group__display__interface__ext.html',1,'']]],
  ['display_20apis_114',['BBC micro:bit display APIs',['../group__mb__display.html',1,'']]],
  ['display_20controller_115',['AC057TC1 display controller',['../group__ac057tc1__display__interface.html',1,'']]],
  ['display_20driver_20backend_20api_116',['display driver backend api',['../group__auxdisplay__interface__backend.html',1,'Auxiliary Display Driver Backend API'],['../group__display__interface__backend.html',1,'Display Driver Backend API']]],
  ['display_20interface_117',['MIPI Display interface',['../group__mipi__interface.html',1,'']]],
  ['display_20list_118',['FT8xx display list',['../group__ft8xx__dl.html',1,'']]],
  ['distributed_20switch_20architecture_20dsa_119',['Distributed Switch Architecture (DSA)',['../group__dsa__core.html',1,'']]],
  ['distribution_20models_120',['Firmware Distribution models',['../group__bt__mesh__dfd.html',1,'']]],
  ['distribution_20profile_20a2dp_121',['Advanced Audio Distribution Profile (A2DP)',['../group__bt__a2dp.html',1,'']]],
  ['distribution_20server_20model_122',['Firmware Distribution Server model',['../group__bt__mesh__dfd__srv.html',1,'']]],
  ['divider_123',['Voltage Divider',['../group__adc__voltage__divider__interface.html',1,'']]],
  ['divider_20constants_124',['Renesas RA BSP Clock Clkout Divider Constants',['../group__bsp__clock__clkout.html',1,'']]],
  ['divider_20generators_125',['Renesas RA Clock Divider Generators',['../group__ra__cgc__div.html',1,'']]],
  ['dma_126',['DMA',['../group__dma__interface.html',1,'']]],
  ['dma_20api_127',['Devicetree DMA API',['../group__devicetree-dmas.html',1,'']]],
  ['dma_20sf32lb_20specifics_128',['DMA (SF32LB specifics)',['../group__dma__sf32lb.html',1,'']]],
  ['dns_20resolve_20library_129',['DNS Resolve Library',['../group__dns__resolve.html',1,'']]],
  ['dns_20service_20discovery_130',['DNS Service Discovery',['../group__dns__sd.html',1,'']]],
  ['domain_20apis_131',['domain apis',['../group__mem__domain__apis__app.html',1,'Application memory domain APIs'],['../group__mem__domain__apis.html',1,'Memory domain APIs'],['../group__log__frontend__stmesp__apis.html',1,'Trace and Debug Domain APIs']]],
  ['domain_20protocol_132',['Power Domain Protocol',['../group__scmi__power.html',1,'']]],
  ['dot_20product_133',['Vector Dot Product',['../group__math__dsp__basic__dot.html',1,'']]],
  ['doubly_20linked_20list_134',['Doubly-linked list',['../group__doubly-linked-list__apis.html',1,'']]],
  ['driven_20uart_20api_135',['Interrupt-driven UART API',['../group__uart__interrupt.html',1,'']]],
  ['driver_136',['Stepper Hardware Driver',['../group__stepper__hw__driver.html',1,'']]],
  ['driver_20apis_137',['driver apis',['../group__crc__interface.html',1,'CRC driver APIs'],['../group__mm__drv__bank__apis.html',1,'Memory Banks Driver APIs'],['../group__mm__drv__apis.html',1,'Memory Management Driver APIs']]],
  ['driver_20backend_20api_138',['driver backend api',['../group__auxdisplay__interface__backend.html',1,'Auxiliary Display Driver Backend API'],['../group__biometrics__interface__backend.html',1,'Biometrics Driver Backend API'],['../group__bt__hci__api__backend.html',1,'Bluetooth HCI Driver Backend API'],['../group__can__controller__backend.html',1,'CAN Controller Driver Backend API'],['../group__charger__interface__backend.html',1,'Charger Driver Backend API'],['../group__clock__control__interface__backend.html',1,'Clock Control Driver Backend API'],['../group__counter__interface__backend.html',1,'Counter Driver Backend API'],['../group__crc__interface__backend.html',1,'CRC Driver Backend API'],['../group__display__interface__backend.html',1,'Display Driver Backend API'],['../group__entropy__interface__backend.html',1,'Entropy Driver Backend API'],['../group__fpga__interface__backend.html',1,'FPGA Driver Backend API'],['../group__gnss__interface__backend.html',1,'GNSS Driver Backend API'],['../group__haptics__interface__backend.html',1,'Haptics Driver Backend API'],['../group__hwspinlock__interface__backend.html',1,'Hardware Spinlock Driver Backend API'],['../group__ipm__interface__backend.html',1,'IPM Driver Backend API'],['../group__led__strip__interface__backend.html',1,'LED Strip Driver Backend API'],['../group__mipi__dbi__interface__backend.html',1,'MIPI-DBI Driver Backend API'],['../group__opamp__interface__backend.html',1,'OPAMP Driver Backend API'],['../group__otp__interface__backend.html',1,'OTP Driver Backend API'],['../group__pwm__interface__backend.html',1,'PWM Driver Backend API'],['../group__retained__mem__interface__backend.html',1,'Retained Memory Driver Backend API'],['../group__rtc__interface__backend.html',1,'RTC Driver Backend API'],['../group__sensor__interface__backend.html',1,'Sensor Driver Backend API'],['../group__spi__interface__backend.html',1,'SPI Driver Backend API'],['../group__stepper__ctrl__backend.html',1,'Stepper Motion Controller Driver Backend API'],['../group__usb__type__c__port__controller__api__backend.html',1,'USB Type-C Port Controller Driver Backend API'],['../group__video__interface__backend.html',1,'Video Driver Backend API'],['../group__watchdog__interface__backend.html',1,'Watchdog Driver Backend API'],['../group__wuc__interface__backend.html',1,'WUC Driver Backend API']]],
  ['driver_20driver_20backend_20api_139',['Stepper Hardware Driver Driver Backend API',['../group__stepper__hw__driver__backend.html',1,'']]],
  ['driver_20extended_20api_140',['BlueNRG HCI driver extended API',['../group__bluenrg__hci__driver.html',1,'']]],
  ['driver_20interface_141',['LiteX Clock Control driver interface',['../group__clock__control__litex__interface.html',1,'']]],
  ['driver_20support_20functions_142',['driver support functions',['../group__dummy.html',1,'Dummy L2/driver Support Functions'],['../group__ppp.html',1,'PPP L2/driver Support Functions']]],
  ['drivers_143',['drivers',['../group__io__interfaces.html',1,'Device Drivers'],['../group__ieee802154__driver.html',1,'IEEE 802.15.4 Drivers']]],
  ['drv2605_144',['DRV2605',['../group__drv2605__interface.html',1,'']]],
  ['ds3231_20legacy_145',['RTC DS3231 (legacy).',['../group__rtc__ds3231__interface.html',1,'']]],
  ['dsa_146',['Distributed Switch Architecture (DSA)',['../group__dsa__core.html',1,'']]],
  ['dsa_20tag_20protocol_147',['DSA tag protocol',['../group__dsa__tag.html',1,'']]],
  ['dsi_148',['MIPI-DSI',['../group__mipi__dsi__interface.html',1,'']]],
  ['dsp_20digital_20signal_20processing_149',['DSP (Digital Signal Processing)',['../group__math__dsp.html',1,'']]],
  ['dt_20options_150',['dt options',['../group__adxl345.html',1,'ADXL345 DT Options'],['../group__adxl355.html',1,'ADXL355 DT Options'],['../group__adxl362.html',1,'ADXL362 DT Options'],['../group__adxl367.html',1,'ADXL367 DT Options'],['../group__adxl372.html',1,'ADXL372 DT Options'],['../group__ICM42686.html',1,'Invensense (TDK) ICM42686 DT Options'],['../group__icm42688.html',1,'Invensense (TDK) ICM42688 DT Options'],['../group__ICM4268X.html',1,'Invensense (TDK) ICM4268X DT Options'],['../group__ICM45686.html',1,'Invensense (TDK) ICM45686 DT Options'],['../group__mcp9600.html',1,'MCP9600 DT Options'],['../group__mc3419.html',1,'Memsic DT Options'],['../group__RM3100.html',1,'PNI DT Options'],['../group__sensor__axis__align.html',1,'Sensor axis alignment DT Options'],['../group__tmp114.html',1,'Texas Instruments (TI) TMP114 DT Options'],['../group__tmp11x.html',1,'Texas Instruments (TI) TMP11X DT Options']]],
  ['dummy_20l2_20driver_20support_20functions_151',['Dummy L2/driver Support Functions',['../group__dummy.html',1,'']]],
  ['dummy_20transport_152',['Dummy transport',['../group__mcumgr__transport__dummy.html',1,'']]],
  ['dump_20apis_153',['Architecture-specific core dump APIs',['../group__arch-coredump.html',1,'']]],
  ['dvp_2020_20pin_20connector_154',['Arducam DVP 20-pin connector',['../group__dvp-20pin-connector.html',1,'']]],
  ['dynamic_20pin_20control_155',['Dynamic Pin Control',['../group__pinctrl__interface__dynamic.html',1,'']]]
];
