var searchData=
[
  ['each_20macros_0',['&quot;For-each&quot; macros',['../group__devicetree-generic-foreach.html',1,'']]],
  ['ead_1',['Encrypted Advertising Data (EAD)',['../group__bt__ead.html',1,'']]],
  ['ec_20host_20command_20interface_2',['EC Host Command Interface',['../group__ec__host__cmd__interface.html',1,'']]],
  ['edac_3',['edac',['../group__edac__interface.html',1,'EDAC'],['../group__edac__nxp__erm__interface.html',1,'NXP ERM EDAC'],['../group__edac__synopsys__interface.html',1,'Synopsys DDR controller EDAC']]],
  ['edac_20api_20extensions_4',['Device-specific EDAC API extensions',['../group__edac__interface__ext.html',1,'']]],
  ['edr_5',['Bluetooth Logical Link Control and Adaptation Protocol (L2CAP) for BR/EDR',['../group__bt__l2cap__br.html',1,'']]],
  ['eeprom_6',['EEPROM',['../group__eeprom__interface.html',1,'']]],
  ['eeprom_20target_7',['I2C EEPROM Target',['../group__i2c__eeprom__target__api.html',1,'']]],
  ['elapsed_20time_20service_20ets_8',['Elapsed Time Service (ETS)',['../group__bt__ets.html',1,'']]],
  ['elc_9',['Renesas ELC',['../group__renesas__elc__interface.html',1,'']]],
  ['elf_20constants_20and_20data_20types_10',['ELF constants and data types',['../group__llext__elf.html',1,'']]],
  ['elf_20inspection_20apis_11',['ELF inspection APIs',['../group__llext__inspect__apis.html',1,'']]],
  ['elf_20loader_20context_12',['ELF loader context',['../group__llext__loader__apis.html',1,'']]],
  ['emulated_20adc_13',['Emulated ADC',['../group__adc__emul.html',1,'']]],
  ['emulated_20gpio_14',['Emulated GPIO',['../group__gpio__emul.html',1,'']]],
  ['emulation_20interface_15',['emulation interface',['../group__espi__emul__interface.html',1,'eSPI Emulation Interface'],['../group__i2c__emul__interface.html',1,'I2C Emulation Interface'],['../group__mspi__emul__interface.html',1,'MSPI Emulation Interface'],['../group__spi__emul__interface.html',1,'SPI Emulation Interface'],['../group__uart__emul__interface.html',1,'UART Emulation Interface']]],
  ['emulator_20apis_16',['emulator apis',['../group__b12__emulator__backend.html',1,'BC1.2 backed emulator APIs'],['../group__fuel__gauge__emulator__backend.html',1,'Fuel gauge backend emulator APIs']]],
  ['emulator_20backend_20api_17',['emulator backend api',['../group__bbram__emulator__backend.html',1,'BBRAM emulator backend API'],['../group__sensor__emulator__backend.html',1,'Sensor emulator backend API']]],
  ['emulator_20interfaces_18',['Emulator interfaces',['../group__io__emulators.html',1,'']]],
  ['emulator_20test_20helpers_19',['Biometrics emulator test helpers',['../group__biometrics__emulator.html',1,'']]],
  ['enable_20disable_20definitions_20',['FocalTech Reset Enable/Disable Definitions',['../group__focaltech__reset__enables.html',1,'']]],
  ['encrypted_20advertising_20data_20ead_21',['Encrypted Advertising Data (EAD)',['../group__bt__ead.html',1,'']]],
  ['endpoint_20api_22',['Devicetree Port Endpoint API',['../group__devicetree-port-endpoint.html',1,'']]],
  ['endpoint_20discovery_20message_20filter_20bits_23',['UMP Stream endpoint discovery message filter bits',['../group__midi__ump__ep__disc.html',1,'']]],
  ['endpoint_20ipc_20library_20api_24',['Icmsg multi-endpoint IPC library API',['../group__ipc__icmsg__me__api.html',1,'']]],
  ['ens160_25',['ENS160',['../group__ens160__interface.html',1,'']]],
  ['entropy_26',['Entropy',['../group__entropy__interface.html',1,'']]],
  ['entropy_20driver_20backend_20api_27',['Entropy Driver Backend API',['../group__entropy__interface__backend.html',1,'']]],
  ['enumeration_20management_28',['Enumeration Management',['../group__mcumgr__enum__mgmt.html',1,'']]],
  ['enumeration_20management_20callbacks_29',['Enumeration Management Callbacks',['../group__mcumgr__callback__api__enum__mgmt.html',1,'']]],
  ['eportrstr_20reset_20control_30',['EPORTRSTR Reset Control',['../group__focaltech__eportrstr__resets.html',1,'']]],
  ['erm_20edac_31',['NXP ERM EDAC',['../group__edac__nxp__erm__interface.html',1,'']]],
  ['error_20apis_32',['Fatal error APIs',['../group__fatal__apis.html',1,'']]],
  ['error_20base_20types_33',['Fatal error base types',['../group__fatal__types.html',1,'']]],
  ['error_20numbers_34',['Error numbers',['../group__system__errno.html',1,'']]],
  ['esp32_20pin_20control_20helpers_35',['Espressif ESP32 pin control helpers',['../group__pinctrl__esp32.html',1,'']]],
  ['esp32c2_20pin_20control_20helpers_36',['Espressif ESP32C2 pin control helpers',['../group__pinctrl__esp32c2.html',1,'']]],
  ['esp32c3_20pin_20control_20helpers_37',['Espressif ESP32C3 pin control helpers',['../group__pinctrl__esp32c3.html',1,'']]],
  ['esp32c5_20pin_20control_20helpers_38',['Espressif ESP32C5 pin control helpers',['../group__pinctrl__esp32c5.html',1,'']]],
  ['esp32c6_20pin_20control_20helpers_39',['Espressif ESP32C6 pin control helpers',['../group__pinctrl__esp32c6.html',1,'']]],
  ['esp32h2_20pin_20control_20helpers_40',['Espressif ESP32H2 pin control helpers',['../group__pinctrl__esp32h2.html',1,'']]],
  ['esp32s2_20pin_20control_20helpers_41',['Espressif ESP32S2 pin control helpers',['../group__pinctrl__esp32s2.html',1,'']]],
  ['esp32s3_20pin_20control_20helpers_42',['Espressif ESP32S3 pin control helpers',['../group__pinctrl__esp32s3.html',1,'']]],
  ['espi_43',['ESPI',['../group__espi__interface.html',1,'']]],
  ['espi_20emulation_20interface_44',['eSPI Emulation Interface',['../group__espi__emul__interface.html',1,'']]],
  ['espi_20saf_45',['eSPI SAF',['../group__espi__saf__interface.html',1,'']]],
  ['espressif_20esp32_20pin_20control_20helpers_46',['Espressif ESP32 pin control helpers',['../group__pinctrl__esp32.html',1,'']]],
  ['espressif_20esp32c2_20pin_20control_20helpers_47',['Espressif ESP32C2 pin control helpers',['../group__pinctrl__esp32c2.html',1,'']]],
  ['espressif_20esp32c3_20pin_20control_20helpers_48',['Espressif ESP32C3 pin control helpers',['../group__pinctrl__esp32c3.html',1,'']]],
  ['espressif_20esp32c5_20pin_20control_20helpers_49',['Espressif ESP32C5 pin control helpers',['../group__pinctrl__esp32c5.html',1,'']]],
  ['espressif_20esp32c6_20pin_20control_20helpers_50',['Espressif ESP32C6 pin control helpers',['../group__pinctrl__esp32c6.html',1,'']]],
  ['espressif_20esp32h2_20pin_20control_20helpers_51',['Espressif ESP32H2 pin control helpers',['../group__pinctrl__esp32h2.html',1,'']]],
  ['espressif_20esp32s2_20pin_20control_20helpers_52',['Espressif ESP32S2 pin control helpers',['../group__pinctrl__esp32s2.html',1,'']]],
  ['espressif_20esp32s3_20pin_20control_20helpers_53',['Espressif ESP32S3 pin control helpers',['../group__pinctrl__esp32s3.html',1,'']]],
  ['espressif_20pin_20control_20helpers_54',['Espressif pin control helpers',['../group__espressif__pinctrl.html',1,'']]],
  ['ethernet_20bridge_20fdb_55',['Ethernet bridge FDB',['../group__eth__bridge__fdb.html',1,'']]],
  ['ethernet_20bridging_20api_56',['Ethernet Bridging API',['../group__eth__bridge.html',1,'']]],
  ['ethernet_20filter_20conditions_57',['Ethernet Filter Conditions',['../group__npf__eth__cond.html',1,'']]],
  ['ethernet_20library_58',['Ethernet Library',['../group__ethernet__mgmt.html',1,'']]],
  ['ethernet_20mii_20support_20functions_59',['Ethernet MII Support Functions',['../group__ethernet__mii.html',1,'']]],
  ['ethernet_20phy_20interface_60',['Ethernet PHY Interface',['../group__ethernet__phy.html',1,'']]],
  ['ethernet_20support_20functions_61',['Ethernet Support Functions',['../group__ethernet.html',1,'']]],
  ['ets_62',['Elapsed Time Service (ETS)',['../group__bt__ets.html',1,'']]],
  ['event_63',['event',['../group__subsys__tracing__apis__event.html',1,'Event'],['../group__subsys__tracing__apis__named.html',1,'User-defined event']]],
  ['event_20api_64',['hawkBit event API',['../group__hawkbit__event.html',1,'']]],
  ['event_20apis_65',['Event APIs',['../group__event__apis.html',1,'']]],
  ['event_20definitions_66',['Input Event Definitions',['../group__input__events.html',1,'']]],
  ['events_67',['events',['../group__coap__mgmt.html',1,'CoAP Manager Events'],['../group__touch__events.html',1,'Touchscreen Events']]],
  ['eviction_20algorithm_20apis_68',['Eviction Algorithm APIs',['../group__mem-demand-paging-eviction.html',1,'']]],
  ['exchange_20profile_20goep_69',['Generic Object Exchange Profile (GOEP)',['../group__bt__goep.html',1,'']]],
  ['exchange_20protocol_20obex_70',['IrDA Oject Exchange Protocol (OBEX)',['../group__bt__obex.html',1,'']]],
  ['existence_20checks_71',['Existence checks',['../group__devicetree-generic-exist.html',1,'']]],
  ['expectation_20macros_72',['Ztest expectation macros',['../group__ztest__expect.html',1,'']]],
  ['explorir_20m_73',['ExplorIR-M',['../group__explorir__m__interface.html',1,'']]],
  ['exported_20symbol_20definitions_74',['Exported symbol definitions',['../group__llext__symbols.html',1,'']]],
  ['extended_20api_75',['BlueNRG HCI driver extended API',['../group__bluenrg__hci__driver.html',1,'']]],
  ['extended_20operations_76',['Extended Operations',['../group__flash__ex__op.html',1,'']]],
  ['extensions_77',['extensions',['../group__adc__interface__ext.html',1,'Device-specific ADC API extensions'],['../group__charger__interface__ext.html',1,'Device-specific Charger API extensions'],['../group__dac__interface__ext.html',1,'Device-specific DAC API extensions'],['../group__disk__driver__interface__ext.html',1,'Device-specific Disk Access API extensions'],['../group__display__interface__ext.html',1,'Device-specific Display API extensions'],['../group__edac__interface__ext.html',1,'Device-specific EDAC API extensions'],['../group__gpio__interface__ext.html',1,'Device-specific GPIO API extensions'],['../group__haptics__interface__ext.html',1,'Device-specific Haptics API extensions'],['../group__input__interface__ext.html',1,'Device-specific Input API extensions'],['../group__led__strip__interface__ext.html',1,'Device-specific LED Strip API extensions'],['../group__pwm__interface__ext.html',1,'Device-specific PWM API extensions'],['../group__sensor__interface__ext.html',1,'Device-specific Sensor API extensions'],['../group__fff__extensions.html',1,'FFF extensions'],['../group__llext__apis.html',1,'Linkable loadable extensions']]],
  ['external_20cache_20controller_78',['External Cache Controller',['../group__cache__external__interface.html',1,'']]],
  ['external_20clock_20options_79',['External Clock options',['../group__adxl355__ext__clk.html',1,'']]],
  ['external_20sync_20options_80',['External Sync options',['../group__adxl355__ext__sync.html',1,'']]],
  ['extras_81',['Math extras',['../group__math__extras.html',1,'']]]
];
