var searchData=
[
  ['l2_0',['IEEE 802.15.4 L2',['../group__ieee802154__l2.html',1,'']]],
  ['l2_20abstraction_20layer_1',['Network L2 Abstraction Layer',['../group__net__l2.html',1,'']]],
  ['l2_20driver_20support_20functions_2',['l2 driver support functions',['../group__dummy.html',1,'Dummy L2/driver Support Functions'],['../group__ppp.html',1,'PPP L2/driver Support Functions']]],
  ['l2cap_3',['l2cap',['../group__bt__goep__transport__l2cap.html',1,'GOEP transport L2CAP'],['../group__bt__l2cap.html',1,'L2CAP']]],
  ['l2cap_20channel_20identifiers_4',['L2CAP channel identifiers',['../group__l2cap__cid.html',1,'']]],
  ['l2cap_20for_20br_20edr_5',['Bluetooth Logical Link Control and Adaptation Protocol (L2CAP) for BR/EDR',['../group__bt__l2cap__br.html',1,'']]],
  ['labs_20pin_20control_20helpers_6',['Silicon Labs pin control helpers',['../group__silabs__pinctrl.html',1,'']]],
  ['labs_20series_202_20devicetree_20helpers_7',['Silicon Labs Series 2 Devicetree helpers',['../group__clock__control__silabs.html',1,'']]],
  ['labs_20xg21_20pin_20control_20helpers_8',['Silicon Labs xG21 pin control helpers',['../group__pinctrl__xg21.html',1,'']]],
  ['labs_20xg22_20pin_20control_20helpers_9',['Silicon Labs xG22 pin control helpers',['../group__pinctrl__xg22.html',1,'']]],
  ['labs_20xg23_20pin_20control_20helpers_10',['Silicon Labs xG23 pin control helpers',['../group__pinctrl__xg23.html',1,'']]],
  ['labs_20xg24_20pin_20control_20helpers_11',['Silicon Labs xG24 pin control helpers',['../group__pinctrl__xg24.html',1,'']]],
  ['labs_20xg26_20pin_20control_20helpers_12',['Silicon Labs xG26 pin control helpers',['../group__pinctrl__xg26.html',1,'']]],
  ['labs_20xg27_20pin_20control_20helpers_13',['Silicon Labs xG27 pin control helpers',['../group__pinctrl__xg27.html',1,'']]],
  ['labs_20xg28_20pin_20control_20helpers_14',['Silicon Labs xG28 pin control helpers',['../group__pinctrl__xg28.html',1,'']]],
  ['labs_20xg29_20pin_20control_20helpers_15',['Silicon Labs xG29 pin control helpers',['../group__pinctrl__xg29.html',1,'']]],
  ['lan_20definitions_20and_20helpers_16',['Virtual LAN definitions and helpers',['../group__vlan__api.html',1,'']]],
  ['large_20composition_20data_20client_20model_17',['Large Composition Data Client model',['../group__bt__mesh__large__comp__data__cli.html',1,'']]],
  ['large_20composition_20data_20server_20model_18',['Large Composition Data Server model',['../group__bt__mesh__large__comp__data__srv.html',1,'']]],
  ['latency_20monitor_19',['Latency Monitor',['../group__latmon.html',1,'']]],
  ['layer_20',['layer',['../group__w1__data__link.html',1,'1-Wire data link layer'],['../group__w1__network.html',1,'1-Wire network layer'],['../group__bt__mesh__access.html',1,'Access layer'],['../group__net__if.html',1,'Network Interface abstraction layer'],['../group__net__l2.html',1,'Network L2 Abstraction Layer']]],
  ['layer_20discovery_20protocol_20definitions_20and_20helpers_21',['Link Layer Discovery Protocol definitions and helpers',['../group__lldp.html',1,'']]],
  ['layers_22',['Transport layers',['../group__mcumgr__transport.html',1,'']]],
  ['lc3_20codec_23',['Bluetooth LC3 codec',['../group__bt__lc3.html',1,'']]],
  ['lc3_20presets_24',['lc3 presets',['../group__bt__bap__lc3__preset.html',1,'Basic Audio Profile (BAP) LC3 Presets'],['../group__bt__gmap__lc3__preset.html',1,'Gaming Audio Profile (GMAP) LC3 Presets']]],
  ['lcd_20interface_25',['LCD Interface',['../group__lcd__interface.html',1,'']]],
  ['led_26',['LED',['../group__led__interface.html',1,'']]],
  ['led_20strip_27',['LED Strip',['../group__led__strip__interface.html',1,'']]],
  ['led_20strip_20api_20extensions_28',['Device-specific LED Strip API extensions',['../group__led__strip__interface__ext.html',1,'']]],
  ['led_20strip_20driver_20backend_20api_29',['LED Strip Driver Backend API',['../group__led__strip__interface__backend.html',1,'']]],
  ['legacy_30',['RTC DS3231 (legacy).',['../group__rtc__ds3231__interface.html',1,'']]],
  ['level_20api_31',['LwM2M high-level API',['../group__lwm2m__api.html',1,'']]],
  ['level_20heap_20allocator_32',['Low Level Heap Allocator',['../group__low__level__heap__allocator.html',1,'']]],
  ['level_20mmio_20region_20macros_33',['Top-level MMIO region macros',['../group__device-mmio-toplevel.html',1,'']]],
  ['library_34',['library',['../group__coap.html',1,'COAP Library'],['../group__dns__resolve.html',1,'DNS Resolve Library'],['../group__ethernet__mgmt.html',1,'Ethernet Library'],['../group__mqtt__socket.html',1,'MQTT Client library'],['../group__mqtt__sn__socket.html',1,'MQTT-SN Client library'],['../group__net__buf.html',1,'Network Buffer Library'],['../group__net__config.html',1,'Network Configuration Library'],['../group__net__core.html',1,'Network Core Library'],['../group__net__hostname.html',1,'Network Hostname Library'],['../group__net__linkaddr.html',1,'Network Link Address Library'],['../group__net__pkt.html',1,'Network Packet Library'],['../group__net__stats.html',1,'Network Statistics Library'],['../group__ocpp__api.html',1,'OCPP library'],['../group__socket__net__mgmt.html',1,'Socket NET_MGMT library'],['../group__socket__can.html',1,'SocketCAN library'],['../group__tftp__client.html',1,'TFTP Client library'],['../group__trickle.html',1,'Trickle Algorithm Library'],['../group__virtual__mgmt.html',1,'Virtual Interface Library'],['../group__wifi__credentials.html',1,'Wi-Fi credentials library']]],
  ['library_20api_35',['library api',['../group__ftp__client.html',1,'FTP client library API'],['../group__ipc__icmsg__api.html',1,'Icmsg IPC library API'],['../group__ipc__icmsg__me__api.html',1,'Icmsg multi-endpoint IPC library API']]],
  ['lifo_36',['LIFO',['../group__subsys__tracing__apis__lifo.html',1,'']]],
  ['lifo_20apis_37',['LIFO APIs',['../group__lifo__apis.html',1,'']]],
  ['linear_20range_38',['Linear Range',['../group__linear__range.html',1,'']]],
  ['link_39',['DAP Link',['../group__dap__link__interface.html',1,'']]],
  ['link_20address_20library_40',['Network Link Address Library',['../group__net__linkaddr.html',1,'']]],
  ['link_20api_41',['Log link API',['../group__log__link.html',1,'']]],
  ['link_20control_20and_20adaptation_20protocol_20l2cap_20for_20br_20edr_42',['Bluetooth Logical Link Control and Adaptation Protocol (L2CAP) for BR/EDR',['../group__bt__l2cap__br.html',1,'']]],
  ['link_20layer_43',['1-Wire data link layer',['../group__w1__data__link.html',1,'']]],
  ['link_20layer_20discovery_20protocol_20definitions_20and_20helpers_44',['Link Layer Discovery Protocol definitions and helpers',['../group__lldp.html',1,'']]],
  ['linkable_20loadable_20extensions_45',['Linkable loadable extensions',['../group__llext__apis.html',1,'']]],
  ['linked_20list_46',['linked list',['../group__doubly-linked-list__apis.html',1,'Doubly-linked list'],['../group__flagged-single-linked-list__apis.html',1,'Flagged Single-linked list'],['../group__single-linked-list__apis.html',1,'Single-linked list']]],
  ['lis2dh_47',['LIS2DH',['../group__lis2dh__interface.html',1,'']]],
  ['list_48',['list',['../group__doubly-linked-list__apis.html',1,'Doubly-linked list'],['../group__flagged-single-linked-list__apis.html',1,'Flagged Single-linked list'],['../group__ft8xx__dl.html',1,'FT8xx display list'],['../group__single-linked-list__apis.html',1,'Single-linked list']]],
  ['listener_20apis_49',['Heap Listener APIs',['../group__heap__listener__apis.html',1,'']]],
  ['listener_20discovery_20api_50',['Multicast Listener Discovery API',['../group__mld.html',1,'']]],
  ['litex_20clock_20control_20driver_20interface_51',['LiteX Clock Control driver interface',['../group__clock__control__litex__interface.html',1,'']]],
  ['lm95234_52',['LM95234',['../group__lm95234__interface.html',1,'']]],
  ['lmp90xxx_53',['LMP90xxx',['../group__lmp90xxx__interface.html',1,'']]],
  ['load_54',['CPU Load',['../group__subsys__cpu__load.html',1,'']]],
  ['load_20monitor_55',['CPU load monitor',['../group__cpu__load.html',1,'']]],
  ['loadable_20extensions_56',['Linkable loadable extensions',['../group__llext__apis.html',1,'']]],
  ['loader_20context_57',['ELF loader context',['../group__llext__loader__apis.html',1,'']]],
  ['local_20storage_20apis_58',['Architecture-specific Thread Local Storage APIs',['../group__arch-tls.html',1,'']]],
  ['lockfree_20queue_20api_59',['MPSC Lockfree Queue API',['../group__mpsc__lockfree.html',1,'']]],
  ['log_20backend_20api_60',['log backend api',['../group__log__backend__ble.html',1,'Bluetooth log backend API'],['../group__log__backend__adsp__hda.html',1,'Intel ADSP HDA log backend API'],['../group__log__backend__adsp__mtrace.html',1,'Intel ADSP mtrace log backend API'],['../group__log__backend__mqtt.html',1,'MQTT log backend API'],['../group__log__backend__net.html',1,'Network log backend API'],['../group__log__backend__ws.html',1,'Websocket log backend API']]],
  ['log_20link_20api_61',['Log link API',['../group__log__link.html',1,'']]],
  ['log_20message_20api_62',['Log message API',['../group__log__msg.html',1,'']]],
  ['log_20output_20api_63',['Log output API',['../group__log__output.html',1,'']]],
  ['log_20output_20formatting_20flags_64',['Log output formatting flags.',['../group__LOG__OUTPUT__FLAGS.html',1,'']]],
  ['logger_20backend_20interface_65',['Logger backend interface',['../group__log__backend.html',1,'']]],
  ['logger_20backend_20standard_20interface_66',['Logger backend standard interface',['../group__log__backend__std.html',1,'']]],
  ['logger_20control_20api_67',['Logger control API',['../group__log__ctrl.html',1,'']]],
  ['logger_20multidomain_20backend_20helpers_68',['Logger multidomain backend helpers',['../group__log__backend__multidomain.html',1,'']]],
  ['logger_20system_69',['Logger system',['../group__logger.html',1,'']]],
  ['logging_70',['Logging',['../group__logging.html',1,'']]],
  ['logging_20api_71',['Logging API',['../group__log__api.html',1,'']]],
  ['logging_20frontend_20stmesp_20demultiplexer_20api_72',['Logging frontend STMESP Demultiplexer API',['../group__log__frontend__stpesp__demux__apis.html',1,'']]],
  ['logical_20link_20control_20and_20adaptation_20protocol_20l2cap_20for_20br_20edr_73',['Bluetooth Logical Link Control and Adaptation Protocol (L2CAP) for BR/EDR',['../group__bt__l2cap__br.html',1,'']]],
  ['long_20timeout_20primitives_20and_20helpers_74',['Network long timeout primitives and helpers',['../group__net__timeout.html',1,'']]],
  ['lora_75',['LoRa',['../group__lora__interface.html',1,'']]],
  ['lorawan_20apis_76',['LoRaWAN APIs',['../group__lorawan__api.html',1,'']]],
  ['low_20level_20heap_20allocator_77',['Low Level Heap Allocator',['../group__low__level__heap__allocator.html',1,'']]],
  ['low_20pass_20filtering_20options_78',['low pass filtering options',['../group__ICM45686__ACCEL__LPF.html',1,'Accelerometer Low-pass Filtering options'],['../group__ICM45686__GYRO__LPF.html',1,'Gyroscope Low-pass Filtering options']]],
  ['low_20power_20companion_20interface_79',['System Timer Low-power Companion Interface',['../group__clock__lpm.html',1,'']]],
  ['lowe_20pass_20filter_20configurations_80',['Lowe pass filter configurations',['../group__mc3419__lpf__configs.html',1,'']]],
  ['lpc_81',['NXP MCUX LPC',['../group__gpio__mcux__lpc__interface.html',1,'']]],
  ['lsm6dsvxxx_82',['LSM6DSVXXX',['../group__lsm6dsvxxx__interface.html',1,'']]],
  ['lwm2m_20high_20level_20api_83',['LwM2M high-level API',['../group__lwm2m__api.html',1,'']]],
  ['lwm2m_20path_20helper_20macros_84',['LwM2M path helper macros',['../group__lwm2m__path__helpers.html',1,'']]]
];
