var searchData=
[
  ['obex_0',['IrDA Oject Exchange Protocol (OBEX)',['../group__bt__obex.html',1,'']]],
  ['object_20core_20apis_1',['Object Core APIs',['../group__obj__core__apis.html',1,'']]],
  ['object_20core_20statistics_20apis_2',['Object Core Statistics APIs',['../group__obj__core__stats__apis.html',1,'']]],
  ['object_20exchange_20profile_20goep_3',['Generic Object Exchange Profile (GOEP)',['../group__bt__goep.html',1,'']]],
  ['object_20tracking_4',['Object tracking',['../group__subsys__tracing__object__tracking.html',1,'']]],
  ['object_20transfer_20service_20ots_5',['Object Transfer Service (OTS)',['../group__bt__ots.html',1,'']]],
  ['ocpp_20library_6',['OCPP library',['../group__ocpp__api.html',1,'']]],
  ['off_7',['System power off',['../group__sys__poweroff.html',1,'']]],
  ['off_20service_20apis_8',['On-Off Service APIs',['../group__resource__mgmt__onoff__apis.html',1,'']]],
  ['offloaded_20net_20devices_9',['Offloaded Net Devices',['../group__offloaded__netdev.html',1,'']]],
  ['offloading_20interface_10',['Network Offloading Interface',['../group__net__offload.html',1,'']]],
  ['offset_11',['Vector Offset',['../group__math__dsp__basic__offset.html',1,'']]],
  ['offset_20control_20service_20vocs_12',['Volume Offset Control Service (VOCS)',['../group__bt__vocs.html',1,'']]],
  ['offsets_13',['IOCTRL Register Offsets',['../group__focaltech__pinctrl__regs.html',1,'']]],
  ['oject_20exchange_20protocol_20obex_14',['IrDA Oject Exchange Protocol (OBEX)',['../group__bt__obex.html',1,'']]],
  ['on_20demand_20private_20gatt_20proxy_20client_15',['Bluetooth Mesh On-Demand Private GATT Proxy Client',['../group__bt__mesh__od__priv__proxy__cli.html',1,'']]],
  ['on_20demand_20private_20gatt_20proxy_20server_16',['Bluetooth Mesh On-Demand Private GATT Proxy Server',['../group__bt__mesh__od__priv__proxy__srv.html',1,'']]],
  ['on_20memory_20attributes_17',['Memory heaps based on memory attributes',['../group__memory__attr__heap.html',1,'']]],
  ['on_20off_20service_20apis_18',['On-Off Service APIs',['../group__resource__mgmt__onoff__apis.html',1,'']]],
  ['one_20time_20programmable_20memory_19',['One Time Programmable Memory',['../group__otp__interface.html',1,'']]],
  ['opamp_20',['OPAMP',['../group__opamp__interface.html',1,'']]],
  ['opamp_20driver_20backend_20api_21',['OPAMP Driver Backend API',['../group__opamp__interface__backend.html',1,'']]],
  ['opcodes_20aggregator_20client_20model_22',['Opcodes Aggregator Client model',['../group__bt__mesh__op__agg__cli.html',1,'']]],
  ['opcodes_20aggregator_20server_20model_23',['Opcodes Aggregator Server model',['../group__bt__mesh__op__agg__srv.html',1,'']]],
  ['openthread_20stack_24',['OpenThread stack',['../group__openthread.html',1,'']]],
  ['operating_20system_20services_25',['Operating System Services',['../group__os__services.html',1,'']]],
  ['operation_20codes_26',['RTIO Operation Codes',['../group__rtio__ops.html',1,'']]],
  ['operations_27',['Extended Operations',['../group__flash__ex__op.html',1,'']]],
  ['options_28',['options',['../group__ICM42686__ACCEL__DATA__RATE.html',1,'Accelerometer data rate options'],['../group__ICM4268X__ACCEL__DATA__RATE.html',1,'Accelerometer data rate options'],['../group__ICM45686__ACCEL__DATA__RATE.html',1,'Accelerometer data rate options'],['../group__icm42688__accel__data__rate.html',1,'Accelerometer data rate options'],['../group__ICM45686__ACCEL__LPF.html',1,'Accelerometer Low-pass Filtering options'],['../group__icm42688__accel__scale.html',1,'Accelerometer scale options'],['../group__ICM42686__ACCEL__SCALE.html',1,'Accelerometer scale options'],['../group__ICM45686__ACCEL__SCALE.html',1,'Accelerometer scale options'],['../group__adxl345.html',1,'ADXL345 DT Options'],['../group__adxl355.html',1,'ADXL355 DT Options'],['../group__adxl362.html',1,'ADXL362 DT Options'],['../group__adxl367.html',1,'ADXL367 DT Options'],['../group__adxl372.html',1,'ADXL372 DT Options'],['../group__adxl355__ext__clk.html',1,'External Clock options'],['../group__adxl355__ext__sync.html',1,'External Sync options'],['../group__adxl362__fifo__mode.html',1,'FIFO mode options'],['../group__adxl367__fifo__mode.html',1,'FIFO mode options'],['../group__ADXL372__FIFO__MODE.html',1,'FIFO mode options'],['../group__ICM45686__GYRO__DATA__RATE.html',1,'Gyroscope data rate options'],['../group__ICM42686__GYRO__DATA__RATE.html',1,'Gyroscope data rate options'],['../group__icm42688__gyro__data__rate.html',1,'Gyroscope data rate options'],['../group__ICM4268X__GYRO__DATA__RATE.html',1,'Gyroscope data rate options'],['../group__ICM45686__GYRO__LPF.html',1,'Gyroscope Low-pass Filtering options'],['../group__icm42688__gyro__scale.html',1,'Gyroscope scale options'],['../group__ICM45686__GYRO__SCALE.html',1,'Gyroscope scale options'],['../group__ICM42686__GYRO__SCALE.html',1,'Gyroscope scale options'],['../group__adxl355__hpf__corner.html',1,'High Pass Filter corner options'],['../group__bmp581__iir__filter.html',1,'IIR Filter options.'],['../group__ICM42686.html',1,'Invensense (TDK) ICM42686 DT Options'],['../group__icm42688.html',1,'Invensense (TDK) ICM42688 DT Options'],['../group__ICM4268X.html',1,'Invensense (TDK) ICM4268X DT Options'],['../group__ICM45686.html',1,'Invensense (TDK) ICM45686 DT Options'],['../group__mcp9600.html',1,'MCP9600 DT Options'],['../group__mc3419.html',1,'Memsic DT Options'],['../group__RM3100__ODR.html',1,'Output data rate options'],['../group__bmp581__output__data__rate.html',1,'Output data rate options'],['../group__adxl355__odr.html',1,'Output Rate options'],['../group__adxl345__odr.html',1,'Output Rate options'],['../group__bmp581__oversampling.html',1,'Oversampling options.'],['../group__RM3100.html',1,'PNI DT Options'],['../group__adxl345__range.html',1,'Select range options'],['../group__adxl355__range.html',1,'Select range options'],['../group__sensor__axis__align.html',1,'Sensor axis alignment DT Options'],['../group__tmp114.html',1,'Texas Instruments (TI) TMP114 DT Options'],['../group__tmp11x.html',1,'Texas Instruments (TI) TMP11X DT Options']]],
  ['options_20for_20tls_29',['Socket options for TLS',['../group__secure__sockets__options.html',1,'']]],
  ['or_30',['Vector bitwise OR',['../group__math__dsp__basic__or.html',1,'']]],
  ['os_20management_31',['OS Management',['../group__mcumgr__os__mgmt.html',1,'']]],
  ['os_20management_20callbacks_32',['OS Management Callbacks',['../group__mcumgr__callback__api__os__mgmt.html',1,'']]],
  ['os_20management_20client_33',['OS Management Client',['../group__mcumgr__os__mgmt__client.html',1,'']]],
  ['otp_20driver_20backend_20api_34',['OTP Driver Backend API',['../group__otp__interface__backend.html',1,'']]],
  ['ots_35',['Object Transfer Service (OTS)',['../group__bt__ots.html',1,'']]],
  ['out_36',['Bouffalolab BL61x GPIO FIFO / Wire Out',['../group__gpio__bl61x__wo__interface.html',1,'']]],
  ['output_20api_37',['Log output API',['../group__log__output.html',1,'']]],
  ['output_20apis_38',['Formatted Output APIs',['../group__cbprintf__apis.html',1,'']]],
  ['output_20data_20rate_39',['output data rate',['../group__tmp114__odr.html',1,'Temperature output data rate'],['../group__tmp11x__odr.html',1,'Temperature output data rate']]],
  ['output_20data_20rate_20options_40',['output data rate options',['../group__RM3100__ODR.html',1,'Output data rate options'],['../group__bmp581__output__data__rate.html',1,'Output data rate options']]],
  ['output_20formatting_20flags_41',['Log output formatting flags.',['../group__LOG__OUTPUT__FLAGS.html',1,'']]],
  ['output_20rate_20options_42',['output rate options',['../group__adxl345__odr.html',1,'Output Rate options'],['../group__adxl355__odr.html',1,'Output Rate options']]],
  ['over_20the_20air_43',['over the air',['../group__hawkbit.html',1,'hawkBit Firmware Over-the-Air'],['../group__updatehub.html',1,'UpdateHub Firmware Over-the-Air']]],
  ['overhead_20byte_20stuffing_44',['COBS (Consistent Overhead Byte Stuffing)',['../group__cobs.html',1,'']]],
  ['oversampling_20options_45',['Oversampling options.',['../group__bmp581__oversampling.html',1,'']]]
];
