var searchData=
[
  ['package_20convert_20flags_0',['Package convert flags',['../group__CBPRINTF__PACKAGE__CONVERT__FLAGS.html',1,'']]],
  ['package_20flags_1',['Package flags',['../group__CBPRINTF__PACKAGE__FLAGS.html',1,'']]],
  ['packed_20buffer_20api_2',['Packed Buffer API',['../group__pbuf.html',1,'']]],
  ['packet_20buffer_20api_3',['packet buffer api',['../group__mpsc__buf.html',1,'MPSC (Multi producer, single consumer) packet buffer API'],['../group__spsc__buf.html',1,'SPSC (Single producer, single consumer) packet buffer API']]],
  ['packet_20buffer_20flags_4',['packet buffer flags',['../group__MPSC__PBUF__FLAGS.html',1,'MPSC packet buffer flags'],['../group__SPSC__PBUF__FLAGS.html',1,'SPSC packet buffer flags']]],
  ['packet_20capture_5',['Network packet capture',['../group__net__capture.html',1,'']]],
  ['packet_20definitions_6',['MIDI2 Universal MIDI Packet definitions',['../group__midi__ump.html',1,'']]],
  ['packet_20filter_20api_7',['Network Packet Filter API',['../group__net__pkt__filter.html',1,'']]],
  ['packet_20header_8',['MPSC (Multi producer, single consumer) packet header',['../group__mpsc__packet.html',1,'']]],
  ['packet_20library_9',['Network Packet Library',['../group__net__pkt.html',1,'']]],
  ['packet_20ump_20format_20and_20midi_202_200_20protocol_10',['Universal MIDI Packet (UMP) Format and MIDI 2.0 Protocol',['../group__ump112.html',1,'']]],
  ['packets_11',['User Datagram Protocol for Universal MIDI Packets',['../group__netmidi10.html',1,'']]],
  ['pacs_12',['Published Audio Capabilities Service (PACS)',['../group__bt__pacs.html',1,'']]],
  ['paging_13',['Demand Paging',['../group__demand__paging.html',1,'']]],
  ['paging_20apis_14',['Demand Paging APIs',['../group__mem-demand-paging.html',1,'']]],
  ['paj7620_15',['PAJ7620',['../group__paj7620__interface.html',1,'']]],
  ['parent_20interface_16',['Regulator Parent Interface',['../group__regulator__parent__interface.html',1,'']]],
  ['parsing_20apis_17',['parsing apis',['../group__bt__audio__codec__cap.html',1,'Codec capability parsing APIs'],['../group__bt__audio__codec__cfg.html',1,'Codec config parsing APIs']]],
  ['partition_20api_18',['partition api',['../group__devicetree-fixed-partition.html',1,'Devicetree Fixed Partition API'],['../group__devicetree-mapped-partition.html',1,'Devicetree Mapped Partition API'],['../group__devicetree-partition.html',1,'Devicetree Partition API']]],
  ['party_19',['Third-party',['../group__third__party.html',1,'']]],
  ['pass_20filter_20configurations_20',['Lowe pass filter configurations',['../group__mc3419__lpf__configs.html',1,'']]],
  ['pass_20filter_20corner_20options_21',['High Pass Filter corner options',['../group__adxl355__hpf__corner.html',1,'']]],
  ['pass_20filtering_20options_22',['pass filtering options',['../group__ICM45686__ACCEL__LPF.html',1,'Accelerometer Low-pass Filtering options'],['../group__ICM45686__GYRO__LPF.html',1,'Gyroscope Low-pass Filtering options']]],
  ['pat912x_23',['PAT912x',['../group__pat912x__interface.html',1,'']]],
  ['pat9136_24',['PAT9136',['../group__pat9136__interface.html',1,'']]],
  ['path_20controller_25',['USB Type-C Power Path Controller',['../group__usb__type__c__power__path__controller.html',1,'']]],
  ['path_20helper_20macros_26',['LwM2M path helper macros',['../group__lwm2m__path__helpers.html',1,'']]],
  ['paw32xx_27',['PAW32xx',['../group__paw32xx__interface.html',1,'']]],
  ['pbp_28',['Public Broadcast Profile (PBP)',['../group__bt__pbp.html',1,'']]],
  ['pca9420_20utilities_29',['PCA9420 Utilities.',['../group__regulator__parent__pca9420.html',1,'']]],
  ['pca9422_20interface_30',['MFD PCA9422 Interface',['../group__mdf__interface__pca9422.html',1,'']]],
  ['pcal64xxa_31',['NXP PCAL64XXA',['../group__gpio__pcal64xxa__interface.html',1,'']]],
  ['pcie_32',['PCIe',['../group__pcie__interface.html',1,'']]],
  ['pcie_20capabilities_33',['PCIe Capabilities',['../group__pcie__capabilities.html',1,'']]],
  ['pcie_20controller_34',['PCIe Controller',['../group__pcie__controller__interface.html',1,'']]],
  ['pcie_20host_35',['PCIe Host',['../group__pcie__host__interface.html',1,'']]],
  ['pcie_20host_20msi_20interface_36',['PCIe Host MSI Interface',['../group__pcie__host__msi__interface.html',1,'']]],
  ['pcie_20host_20ptm_20interface_37',['PCIe Host PTM Interface',['../group__pcie__host__ptm__interface.html',1,'']]],
  ['pcie_20virtual_20channel_20host_20interface_38',['PCIe Virtual Channel Host Interface',['../group__pcie__vc__host__interface.html',1,'']]],
  ['pdu_20rpl_20client_39',['Bluetooth Mesh Solicitation PDU RPL Client',['../group__bt__mesh__sol__pdu__rpl__cli.html',1,'']]],
  ['pdu_20rpl_20server_40',['Bluetooth Mesh Solicitation PDU RPL Server',['../group__bt__mesh__sol__pdu__rpl__srv.html',1,'']]],
  ['peci_41',['PECI',['../group__peci__interface.html',1,'']]],
  ['phy_20interface_42',['Ethernet PHY Interface',['../group__ethernet__phy.html',1,'']]],
  ['pi_20csi_20connector_43',['Raspberry Pi CSI connector',['../group__raspberrypi-csi-connector.html',1,'']]],
  ['pi_20pico_20pio_44',['Raspberry Pi Pico PIO',['../group__pio__rpi__pico__interface.html',1,'']]],
  ['pico_20pio_45',['Raspberry Pi Pico PIO',['../group__pio__rpi__pico__interface.html',1,'']]],
  ['pin_20camera_20connector_46',['ArduCam FFC 40-pin camera connector.',['../group__arducam-ffc-40pin.html',1,'']]],
  ['pin_20connector_47',['Arducam DVP 20-pin connector',['../group__dvp-20pin-connector.html',1,'']]],
  ['pin_20control_48',['pin control',['../group__pinctrl__interface__dynamic.html',1,'Dynamic Pin Control'],['../group__focaltech__pinctrl__macros.html',1,'FocalTech IOCTRL Pin Control'],['../group__pinctrl__interface.html',1,'Pin Control'],['../group__devicetree-pinctrl.html',1,'Pin control']]],
  ['pin_20control_20helpers_49',['pin control helpers',['../group__pinctrl__esp32.html',1,'Espressif ESP32 pin control helpers'],['../group__pinctrl__esp32c2.html',1,'Espressif ESP32C2 pin control helpers'],['../group__pinctrl__esp32c3.html',1,'Espressif ESP32C3 pin control helpers'],['../group__pinctrl__esp32c5.html',1,'Espressif ESP32C5 pin control helpers'],['../group__pinctrl__esp32c6.html',1,'Espressif ESP32C6 pin control helpers'],['../group__pinctrl__esp32h2.html',1,'Espressif ESP32H2 pin control helpers'],['../group__pinctrl__esp32s2.html',1,'Espressif ESP32S2 pin control helpers'],['../group__pinctrl__esp32s3.html',1,'Espressif ESP32S3 pin control helpers'],['../group__espressif__pinctrl.html',1,'Espressif pin control helpers'],['../group__sifli__pinctrl.html',1,'SiFli pin control helpers'],['../group__pinctrl__sf32lb52x.html',1,'SiFli SF32LB52x pin control helpers'],['../group__silabs__pinctrl.html',1,'Silicon Labs pin control helpers'],['../group__pinctrl__xg21.html',1,'Silicon Labs xG21 pin control helpers'],['../group__pinctrl__xg22.html',1,'Silicon Labs xG22 pin control helpers'],['../group__pinctrl__xg23.html',1,'Silicon Labs xG23 pin control helpers'],['../group__pinctrl__xg24.html',1,'Silicon Labs xG24 pin control helpers'],['../group__pinctrl__xg26.html',1,'Silicon Labs xG26 pin control helpers'],['../group__pinctrl__xg27.html',1,'Silicon Labs xG27 pin control helpers'],['../group__pinctrl__xg28.html',1,'Silicon Labs xG28 pin control helpers'],['../group__pinctrl__xg29.html',1,'Silicon Labs xG29 pin control helpers']]],
  ['pin_20control_20protocol_50',['Pin Control Protocol',['../group__scmi__pinctrl.html',1,'']]],
  ['pin_20headers_51',['GPIO pin headers',['../group__devicetree-gpio-pin-headers.html',1,'']]],
  ['pio_52',['Raspberry Pi Pico PIO',['../group__pio__rpi__pico__interface.html',1,'']]],
  ['pipe_53',['pipe',['../group__modem__pipe.html',1,'Modem Pipe'],['../group__subsys__tracing__apis__pipe.html',1,'Pipe']]],
  ['pipe_20apis_54',['Pipe APIs',['../group__pipe__apis.html',1,'']]],
  ['pipelink_55',['Modem pipelink',['../group__modem__pipelink.html',1,'']]],
  ['pixel_20formats_56',['Video pixel formats',['../group__video__pixel__formats.html',1,'']]],
  ['pm_57',['pm',['../group__subsys__pm.html',1,'Power Management (PM)'],['../group__subsys__tracing__apis__pm__system.html',1,'System PM']]],
  ['pm_20device_20runtime_58',['PM Device Runtime',['../group__subsys__tracing__apis__pm__device__runtime.html',1,'']]],
  ['pmw3610_59',['PMW3610',['../group__pmw3610__interface.html',1,'']]],
  ['pni_20dt_20options_60',['PNI DT Options',['../group__RM3100.html',1,'']]],
  ['point_20apis_61',['Floating Point APIs',['../group__float__apis.html',1,'']]],
  ['point_20conversions_62',['point conversions',['../group__math__dsp__basic__conv__to__float.html',1,'Fixed to Float point conversions'],['../group__math__dsp__basic__conv__to__fixed.html',1,'Float to Fixed point conversions']]],
  ['point_20shift_20conversion_20functions_63',['Float/Fixed point shift conversion functions',['../group__math__dsp__utils__shifts.html',1,'']]],
  ['policy_64',['policy',['../group__subsys__cpu__freq__policy.html',1,'CPU Frequency Policy'],['../group__subsys__pm__sys__policy.html',1,'Policy']]],
  ['polling_65',['Polling',['../group__subsys__tracing__apis__poll.html',1,'']]],
  ['polling_20apis_66',['Async polling APIs',['../group__poll__apis.html',1,'']]],
  ['polling_20uart_20api_67',['Polling UART API',['../group__uart__polling.html',1,'']]],
  ['port_20controller_20api_68',['USB Type-C Port Controller API',['../group__usb__type__c__port__controller__api.html',1,'']]],
  ['port_20controller_20driver_20backend_20api_69',['USB Type-C Port Controller Driver Backend API',['../group__usb__type__c__port__controller__api__backend.html',1,'']]],
  ['port_20endpoint_20api_70',['Devicetree Port Endpoint API',['../group__devicetree-port-endpoint.html',1,'']]],
  ['power_20companion_20interface_71',['System Timer Low-power Companion Interface',['../group__clock__lpm.html',1,'']]],
  ['power_20delivery_72',['USB Power Delivery',['../group__usb__power__delivery.html',1,'']]],
  ['power_20domain_20protocol_73',['Power Domain Protocol',['../group__scmi__power.html',1,'']]],
  ['power_20management_74',['CPU Power Management',['../group__power__management__cpu__api.html',1,'']]],
  ['power_20management_20apis_75',['Architecture-specific power management APIs',['../group__arch-pm.html',1,'']]],
  ['power_20management_20pm_76',['Power Management (PM)',['../group__subsys__pm.html',1,'']]],
  ['power_20modes_77',['power modes',['../group__ICM42686__ACCEL__POWER__MODES.html',1,'Accelerometer power modes'],['../group__ICM45686__ACCEL__POWER__MODES.html',1,'Accelerometer power modes'],['../group__ICM4268X__ACCEL__POWER__MODES.html',1,'Accelerometer power modes'],['../group__icm42688__accel__power__modes.html',1,'Accelerometer power modes'],['../group__ICM4268X__GYRO__POWER__MODES.html',1,'Gyroscope power modes'],['../group__ICM42686__GYRO__POWER__MODES.html',1,'Gyroscope power modes'],['../group__ICM45686__GYRO__POWER__MODES.html',1,'Gyroscope power modes'],['../group__icm42688__gyro__power__modes.html',1,'Gyroscope power modes'],['../group__bmp581__power__modes.html',1,'Sensor power modes']]],
  ['power_20off_78',['System power off',['../group__sys__poweroff.html',1,'']]],
  ['power_20path_20controller_79',['USB Type-C Power Path Controller',['../group__usb__type__c__power__path__controller.html',1,'']]],
  ['power_20protocol_80',['System Power Protocol',['../group__scmi__system.html',1,'']]],
  ['ppp_81',['Modem PPP',['../group__modem__ppp.html',1,'']]],
  ['ppp_20l2_20driver_20support_20functions_82',['PPP L2/driver Support Functions',['../group__ppp.html',1,'']]],
  ['presets_83',['presets',['../group__bt__bap__lc3__preset.html',1,'Basic Audio Profile (BAP) LC3 Presets'],['../group__bt__gmap__lc3__preset.html',1,'Gaming Audio Profile (GMAP) LC3 Presets']]],
  ['primitives_20and_20helpers_84',['primitives and helpers',['../group__ip__4__6.html',1,'IPv4/IPv6 primitives and helpers'],['../group__net__timeout.html',1,'Network long timeout primitives and helpers']]],
  ['printing_20q_20values_85',['Helper macros for printing Q values.',['../group__math__printing.html',1,'']]],
  ['priorities_86',['RTIO Priorities',['../group__rtio__sqe__prio.html',1,'']]],
  ['private_20beacon_20client_87',['Bluetooth Mesh Private Beacon Client',['../group__bt__mesh__priv__beacon__cli.html',1,'']]],
  ['private_20beacon_20server_88',['Bluetooth Mesh Private Beacon Server',['../group__bt__mesh__priv__beacon__srv.html',1,'']]],
  ['private_20gatt_20proxy_20client_89',['Bluetooth Mesh On-Demand Private GATT Proxy Client',['../group__bt__mesh__od__priv__proxy__cli.html',1,'']]],
  ['private_20gatt_20proxy_20server_90',['Bluetooth Mesh On-Demand Private GATT Proxy Server',['../group__bt__mesh__od__priv__proxy__srv.html',1,'']]],
  ['processing_91',['processing',['../group__math__dsp.html',1,'DSP (Digital Signal Processing)'],['../group__settings__name__proc.html',1,'Settings name processing']]],
  ['processing_20flags_92',['cbvprintf processing flags.',['../group__Z__CBVPRINTF__PROCESS__FLAGS.html',1,'']]],
  ['processor_93',['FT8xx co-processor',['../group__ft8xx__copro.html',1,'']]],
  ['producer_20single_20consumer_20packet_20buffer_20api_94',['producer single consumer packet buffer api',['../group__mpsc__buf.html',1,'MPSC (Multi producer, single consumer) packet buffer API'],['../group__spsc__buf.html',1,'SPSC (Single producer, single consumer) packet buffer API']]],
  ['producer_20single_20consumer_20packet_20header_95',['MPSC (Multi producer, single consumer) packet header',['../group__mpsc__packet.html',1,'']]],
  ['product_96',['Vector Dot Product',['../group__math__dsp__basic__dot.html',1,'']]],
  ['profile_97',['profile',['../group__bt__avrcp__cover__art.html',1,'Audio Video Remote Control Cover Art Profile'],['../group__bt__bap.html',1,'Bluetooth Basic Audio Profile'],['../group__bt__gmap.html',1,'Bluetooth Gaming Audio Profile']]],
  ['profile_20a2dp_98',['Advanced Audio Distribution Profile (A2DP)',['../group__bt__a2dp.html',1,'']]],
  ['profile_20audio_20gateway_20hfp_20ag_99',['Hands Free Profile - Audio Gateway (HFP-AG)',['../group__bt__hfp__ag.html',1,'']]],
  ['profile_20avrcp_100',['Audio Video Remote Control Profile (AVRCP)',['../group__bt__avrcp.html',1,'']]],
  ['profile_20bap_20lc3_20presets_101',['Basic Audio Profile (BAP) LC3 Presets',['../group__bt__bap__lc3__preset.html',1,'']]],
  ['profile_20bip_102',['Basic Imaging Profile (BIP)',['../group__bt__bip.html',1,'']]],
  ['profile_20cap_103',['Common Audio Profile (CAP)',['../group__bt__cap.html',1,'']]],
  ['profile_20ccp_104',['Call Control Profile (CCP)',['../group__bt__ccp.html',1,'']]],
  ['profile_20csip_105',['Coordinated Set Identification Profile (CSIP)',['../group__bt__csip.html',1,'']]],
  ['profile_20gap_106',['Generic Access Profile (GAP)',['../group__bt__gap.html',1,'']]],
  ['profile_20gatt_107',['Generic Attribute Profile (GATT)',['../group__bt__gatt.html',1,'']]],
  ['profile_20gmap_20lc3_20presets_108',['Gaming Audio Profile (GMAP) LC3 Presets',['../group__bt__gmap__lc3__preset.html',1,'']]],
  ['profile_20goep_109',['Generic Object Exchange Profile (GOEP)',['../group__bt__goep.html',1,'']]],
  ['profile_20hfp_110',['Hands Free Profile (HFP)',['../group__bt__hfp.html',1,'']]],
  ['profile_20micp_111',['Microphone Control Profile (MICP)',['../group__bt__micp.html',1,'']]],
  ['profile_20pbp_112',['Public Broadcast Profile (PBP)',['../group__bt__pbp.html',1,'']]],
  ['profile_20tmap_113',['Telephone and Media Audio Profile (TMAP)',['../group__bt__tmap.html',1,'']]],
  ['profile_20vcp_114',['Volume Control Profile (VCP)',['../group__bt__vcp.html',1,'']]],
  ['programmable_20memory_115',['One Time Programmable Memory',['../group__otp__interface.html',1,'']]],
  ['prometheus_20api_116',['Prometheus API',['../group__prometheus.html',1,'']]],
  ['promiscuous_20mode_117',['Promiscuous mode',['../group__promiscuous.html',1,'']]],
  ['property_118',['property',['../group__devicetree-interrupts-prop.html',1,'interrupts property'],['../group__devicetree-ranges-prop.html',1,'ranges property'],['../group__devicetree-reg-prop.html',1,'reg property']]],
  ['property_20accessors_119',['Property accessors',['../group__devicetree-generic-prop.html',1,'']]],
  ['protection_20unit_20mpu_20apis_120',['Xtensa Memory Protection Unit (MPU) APIs',['../group__xtensa__mpu__apis.html',1,'']]],
  ['protocol_121',['protocol',['../group__can__isotp.html',1,'CAN ISO-TP Protocol'],['../group__scmi__clk.html',1,'Clock Protocol'],['../group__dsa__tag.html',1,'DSA tag protocol'],['../group__scmi__pinctrl.html',1,'Pin Control Protocol'],['../group__scmi__power.html',1,'Power Domain Protocol'],['../group__scmi__system.html',1,'System Power Protocol'],['../group__ump112.html',1,'Universal MIDI Packet (UMP) Format and MIDI 2.0 Protocol']]],
  ['protocol_20att_122',['Attribute Protocol (ATT)',['../group__bt__att.html',1,'']]],
  ['protocol_20definitions_20and_20helpers_123',['Link Layer Discovery Protocol definitions and helpers',['../group__lldp.html',1,'']]],
  ['protocol_20for_20universal_20midi_20packets_124',['User Datagram Protocol for Universal MIDI Packets',['../group__netmidi10.html',1,'']]],
  ['protocol_20l2cap_20for_20br_20edr_125',['Bluetooth Logical Link Control and Adaptation Protocol (L2CAP) for BR/EDR',['../group__bt__l2cap__br.html',1,'']]],
  ['protocol_20obex_126',['IrDA Oject Exchange Protocol (OBEX)',['../group__bt__obex.html',1,'']]],
  ['protocol_20sdp_127',['Service Discovery Protocol (SDP)',['../group__bt__sdp.html',1,'']]],
  ['protocols_128',['Protocols',['../group__scmi__protocols.html',1,'']]],
  ['prototypes_129',['fcb non-API prototypes',['../group__fcb__internal.html',1,'']]],
  ['provided_20rate_130',['decimate sampling rate by provided rate',['../group__mc3419__decimation__rates.html',1,'']]],
  ['provisioning_131',['Provisioning',['../group__bt__mesh__prov.html',1,'']]],
  ['provisioning_20client_20model_132',['Remote Provisioning Client model',['../group__bt__mesh__rpr__cli.html',1,'']]],
  ['provisioning_20models_133',['Remote Provisioning models',['../group__bt__mesh__rpr.html',1,'']]],
  ['provisioning_20server_134',['Remote provisioning server',['../group__bt__mesh__rpr__srv.html',1,'']]],
  ['proxy_135',['proxy',['../group__bt__media__proxy.html',1,'Media Proxy'],['../group__bt__mesh__proxy.html',1,'Proxy']]],
  ['proxy_20agent_20api_136',['Zbus Proxy Agent API',['../group__zbus__proxy__agent.html',1,'']]],
  ['proxy_20agent_20ipc_20backend_137',['Zbus Proxy Agent IPC Backend',['../group__zbus__proxy__agent__ipc__backend.html',1,'']]],
  ['proxy_20client_138',['Bluetooth Mesh On-Demand Private GATT Proxy Client',['../group__bt__mesh__od__priv__proxy__cli.html',1,'']]],
  ['proxy_20server_139',['Bluetooth Mesh On-Demand Private GATT Proxy Server',['../group__bt__mesh__od__priv__proxy__srv.html',1,'']]],
  ['ps_202_140',['PS/2',['../group__ps2__interface.html',1,'']]],
  ['psa_20secure_20storage_20api_141',['PSA Secure Storage API',['../group__psa__secure__storage.html',1,'']]],
  ['pseudo_20device_142',['Coredump pseudo-device',['../group__coredump__device__interface.html',1,'']]],
  ['psi5_143',['PSI5',['../group__psi5__interface.html',1,'']]],
  ['pstate_144',['CPU Frequency pstate',['../group__subsys__cpu__freq__pstate.html',1,'']]],
  ['ptm_20interface_145',['PCIe Host PTM Interface',['../group__pcie__host__ptm__interface.html',1,'']]],
  ['ptp_20clock_146',['PTP Clock',['../group__ptp__clock__interface.html',1,'']]],
  ['ptp_20support_147',['PTP support',['../group__ptp.html',1,'']]],
  ['ptp_20time_148',['PTP time',['../group__ptp__time.html',1,'']]],
  ['public_20broadcast_20profile_20pbp_149',['Public Broadcast Profile (PBP)',['../group__bt__pbp.html',1,'']]],
  ['published_20audio_20capabilities_20service_20pacs_150',['Published Audio Capabilities Service (PACS)',['../group__bt__pacs.html',1,'']]],
  ['pwm_151',['pwm',['../group__pwm__max2221x__interface.html',1,'MAX2221X PWM'],['../group__pwm__interface.html',1,'PWM']]],
  ['pwm_20api_20extensions_152',['Device-specific PWM API extensions',['../group__pwm__interface__ext.html',1,'']]],
  ['pwm_20driver_20backend_20api_153',['PWM Driver Backend API',['../group__pwm__interface__backend.html',1,'']]],
  ['pwms_20api_154',['Devicetree PWMs API',['../group__devicetree-pwms.html',1,'']]]
];
