var searchData=
[
  ['f75303_0',['F75303',['../group__f75303__interface.html',1,'']]],
  ['fatal_20error_20apis_1',['Fatal error APIs',['../group__fatal__apis.html',1,'']]],
  ['fatal_20error_20base_20types_2',['Fatal error base types',['../group__fatal__types.html',1,'']]],
  ['faults_3',['Health faults',['../group__bt__mesh__health__faults.html',1,'']]],
  ['fcb_4',['Flash Circular Buffer (FCB)',['../group__fcb.html',1,'']]],
  ['fcb_20api_5',['fcb API',['../group__fcb__api.html',1,'']]],
  ['fcb_20non_20api_20prototypes_6',['fcb non-API prototypes',['../group__fcb__internal.html',1,'']]],
  ['fcx_20mldx5_7',['FCX-MLDX5',['../group__fcx__mldx5__interface.html',1,'']]],
  ['fdb_8',['Ethernet bridge FDB',['../group__eth__bridge__fdb.html',1,'']]],
  ['fdc2x1x_9',['FDC2X1X',['../group__fdc2x1x__interface.html',1,'']]],
  ['ffc_2040_20pin_20camera_20connector_10',['ArduCam FFC 40-pin camera connector.',['../group__arducam-ffc-40pin.html',1,'']]],
  ['fff_20extensions_11',['FFF extensions',['../group__fff__extensions.html',1,'']]],
  ['fi_20credentials_20library_12',['Wi-Fi credentials library',['../group__wifi__credentials.html',1,'']]],
  ['fi_20management_13',['Wi-Fi Management',['../group__wifi__mgmt.html',1,'']]],
  ['fi_20network_20manager_20api_14',['Wi-Fi Network Manager API',['../group__wifi__nm.html',1,'']]],
  ['fields_15',['UMP Stream specific fields',['../group__midi__ump__stream.html',1,'']]],
  ['fifo_16',['FIFO',['../group__subsys__tracing__apis__fifo.html',1,'']]],
  ['fifo_20apis_17',['FIFO APIs',['../group__fifo__apis.html',1,'']]],
  ['fifo_20mode_20options_18',['fifo mode options',['../group__ADXL372__FIFO__MODE.html',1,'FIFO mode options'],['../group__adxl362__fifo__mode.html',1,'FIFO mode options'],['../group__adxl367__fifo__mode.html',1,'FIFO mode options']]],
  ['fifo_20wire_20out_19',['Bouffalolab BL61x GPIO FIFO / Wire Out',['../group__gpio__bl61x__wo__interface.html',1,'']]],
  ['file_20system_20apis_20',['File System APIs',['../group__file__system__api.html',1,'']]],
  ['file_20system_20management_21',['File System Management',['../group__mcumgr__fs__mgmt.html',1,'']]],
  ['file_20system_20management_20callbacks_22',['File System Management Callbacks',['../group__mcumgr__callback__api__fs__mgmt.html',1,'']]],
  ['file_20system_20storage_23',['File System Storage',['../group__file__system__storage.html',1,'']]],
  ['filter_20api_24',['Network Packet Filter API',['../group__net__pkt__filter.html',1,'']]],
  ['filter_20bits_25',['filter bits',['../group__midi__ump__ep__disc.html',1,'UMP Stream endpoint discovery message filter bits'],['../group__midi__ump__fb__disc.html',1,'UMP Stream Function Block discovery message filter bits']]],
  ['filter_20conditions_26',['filter conditions',['../group__npf__basic__cond.html',1,'Basic Filter Conditions'],['../group__npf__eth__cond.html',1,'Ethernet Filter Conditions']]],
  ['filter_20configurations_27',['Lowe pass filter configurations',['../group__mc3419__lpf__configs.html',1,'']]],
  ['filter_20corner_20options_28',['High Pass Filter corner options',['../group__adxl355__hpf__corner.html',1,'']]],
  ['filter_20options_29',['IIR Filter options.',['../group__bmp581__iir__filter.html',1,'']]],
  ['filtering_20options_30',['filtering options',['../group__ICM45686__ACCEL__LPF.html',1,'Accelerometer Low-pass Filtering options'],['../group__ICM45686__GYRO__LPF.html',1,'Gyroscope Low-pass Filtering options']]],
  ['firmware_20distribution_20models_31',['Firmware Distribution models',['../group__bt__mesh__dfd.html',1,'']]],
  ['firmware_20distribution_20server_20model_32',['Firmware Distribution Server model',['../group__bt__mesh__dfd__srv.html',1,'']]],
  ['firmware_20over_20the_20air_33',['firmware over the air',['../group__hawkbit.html',1,'hawkBit Firmware Over-the-Air'],['../group__updatehub.html',1,'UpdateHub Firmware Over-the-Air']]],
  ['firmware_20update_34',['Bluetooth Mesh Device Firmware Update',['../group__bt__mesh__dfu.html',1,'']]],
  ['firmware_20update_20dfu_20metadata_35',['Bluetooth Mesh Device Firmware Update (DFU) metadata',['../group__bt__mesh__dfu__metadata.html',1,'']]],
  ['firmware_20update_20server_20model_36',['Firmware Update Server model',['../group__bt__mesh__dfu__srv.html',1,'']]],
  ['firmware_20uppdate_20client_20model_37',['Firmware Uppdate Client model',['../group__bt__mesh__dfu__cli.html',1,'']]],
  ['fixed_20partition_20api_38',['Devicetree Fixed Partition API',['../group__devicetree-fixed-partition.html',1,'']]],
  ['fixed_20point_20conversions_39',['Float to Fixed point conversions',['../group__math__dsp__basic__conv__to__fixed.html',1,'']]],
  ['fixed_20point_20shift_20conversion_20functions_40',['Float/Fixed point shift conversion functions',['../group__math__dsp__utils__shifts.html',1,'']]],
  ['fixed_20to_20float_20point_20conversions_41',['Fixed to Float point conversions',['../group__math__dsp__basic__conv__to__float.html',1,'']]],
  ['flagged_20single_20linked_20list_42',['Flagged Single-linked list',['../group__flagged-single-linked-list__apis.html',1,'']]],
  ['flags_43',['flags',['../group__Z__CBVPRINTF__PROCESS__FLAGS.html',1,'cbvprintf processing flags.'],['../group__LOG__OUTPUT__FLAGS.html',1,'Log output formatting flags.'],['../group__gpio__interface__max32.html',1,'MAX32-specific GPIO Flags'],['../group__MPSC__PBUF__FLAGS.html',1,'MPSC packet buffer flags'],['../group__gpio__interface__npm13xx.html',1,'nPM13xx-specific GPIO Flags'],['../group__gpio__interface__npm2100.html',1,'nPM2100-specific GPIO Flags'],['../group__gpio__interface__npm6001.html',1,'nPM6001-specific GPIO Flags'],['../group__gpio__interface__nrf.html',1,'nRF-specific GPIO Flags'],['../group__CBPRINTF__PACKAGE__CONVERT__FLAGS.html',1,'Package convert flags'],['../group__CBPRINTF__PACKAGE__FLAGS.html',1,'Package flags'],['../group__rtio__cqe__flags.html',1,'RTIO CQE Flags'],['../group__rtio__i2c__flags.html',1,'RTIO I2C IODEV Flags'],['../group__rtio__i3c__flags.html',1,'RTIO I3C IODEV Flags'],['../group__rtio__sqe__flags.html',1,'RTIO SQE Flags'],['../group__SPSC__PBUF__FLAGS.html',1,'SPSC packet buffer flags'],['../group__gpio__interface__stm32.html',1,'STM32 GPIO specific flags']]],
  ['flash_44',['Flash',['../group__flash__interface.html',1,'']]],
  ['flash_20area_20interface_45',['flash area Interface',['../group__flash__area__api.html',1,'']]],
  ['flash_20circular_20buffer_20data_20structures_46',['Flash Circular Buffer Data Structures',['../group__fcb__data__structures.html',1,'']]],
  ['flash_20circular_20buffer_20fcb_47',['Flash Circular Buffer (FCB)',['../group__fcb.html',1,'']]],
  ['flash_20image_20api_48',['Flash image API',['../group__flash__img__api.html',1,'']]],
  ['flash_20interface_49',['Stream to flash interface',['../group__stream__flash.html',1,'']]],
  ['flash_20internal_50',['Flash Internal',['../group__flash__internal__interface.html',1,'']]],
  ['flash_20stream_51',['Bluetooth Mesh BLOB flash stream',['../group__bt__mesh__blob__io__flash.html',1,'']]],
  ['flexio_52',['NXP FlexIO',['../group__nxp__flexio__interface.html',1,'']]],
  ['float_20fixed_20point_20shift_20conversion_20functions_53',['Float/Fixed point shift conversion functions',['../group__math__dsp__utils__shifts.html',1,'']]],
  ['float_20point_20conversions_54',['Fixed to Float point conversions',['../group__math__dsp__basic__conv__to__float.html',1,'']]],
  ['float_20to_20fixed_20point_20conversions_55',['Float to Fixed point conversions',['../group__math__dsp__basic__conv__to__fixed.html',1,'']]],
  ['floating_20point_20apis_56',['Floating Point APIs',['../group__float__apis.html',1,'']]],
  ['focaltech_20ft9001_20clock_20identifiers_57',['FocalTech FT9001 clock identifiers',['../group__focaltech__ft9001__clocks.html',1,'']]],
  ['focaltech_20ioctrl_20pin_20control_58',['FocalTech IOCTRL Pin Control',['../group__focaltech__pinctrl__macros.html',1,'']]],
  ['focaltech_20reset_20configuration_20macros_59',['FocalTech Reset Configuration Macros',['../group__focaltech__reset__macros.html',1,'']]],
  ['focaltech_20reset_20control_20module_20registers_60',['FocalTech Reset Control Module Registers',['../group__focaltech__reset__regs.html',1,'']]],
  ['focaltech_20reset_20enable_20disable_20definitions_61',['FocalTech Reset Enable/Disable Definitions',['../group__focaltech__reset__enables.html',1,'']]],
  ['for_20br_20edr_62',['Bluetooth Logical Link Control and Adaptation Protocol (L2CAP) for BR/EDR',['../group__bt__l2cap__br.html',1,'']]],
  ['for_20each_20macros_63',['&quot;For-each&quot; macros',['../group__devicetree-generic-foreach.html',1,'']]],
  ['for_20printing_20q_20values_64',['Helper macros for printing Q values.',['../group__math__printing.html',1,'']]],
  ['for_20sensor_20alignment_65',['for sensor alignment',['../group__sensor__axis__align__dt.html',1,'Axis description for sensor alignment'],['../group__sensor__axis__align__index__dt.html',1,'Axis description for sensor alignment']]],
  ['for_20tls_66',['Socket options for TLS',['../group__secure__sockets__options.html',1,'']]],
  ['for_20universal_20midi_20packets_67',['User Datagram Protocol for Universal MIDI Packets',['../group__netmidi10.html',1,'']]],
  ['format_68',['format',['../group__subsys__tracing__format__apis.html',1,'Tracing format'],['../group__midi__ump__stream__format.html',1,'UMP Stream format']]],
  ['format_20and_20midi_202_200_20protocol_69',['Universal MIDI Packet (UMP) Format and MIDI 2.0 Protocol',['../group__ump112.html',1,'']]],
  ['formats_70',['Video pixel formats',['../group__video__pixel__formats.html',1,'']]],
  ['formatted_20output_20apis_71',['Formatted Output APIs',['../group__cbprintf__apis.html',1,'']]],
  ['formatting_20flags_72',['Log output formatting flags.',['../group__LOG__OUTPUT__FLAGS.html',1,'']]],
  ['fpga_73',['FPGA',['../group__fpga__interface.html',1,'']]],
  ['fpga_20driver_20backend_20api_74',['FPGA Driver Backend API',['../group__fpga__interface__backend.html',1,'']]],
  ['framebuffer_75',['Monochrome Character Framebuffer',['../group__monochrome__character__framebuffer.html',1,'']]],
  ['framework_76',['Zephyr Benchmarking Framework',['../group__ztest__benchmark.html',1,'']]],
  ['framework_20api_77',['State Machine Framework API',['../group__smf.html',1,'']]],
  ['framework_20ztest_78',['Zephyr Testing Framework (ZTest)',['../group__ztest.html',1,'']]],
  ['free_20profile_20audio_20gateway_20hfp_20ag_79',['Hands Free Profile - Audio Gateway (HFP-AG)',['../group__bt__hfp__ag.html',1,'']]],
  ['free_20profile_20hfp_80',['Hands Free Profile (HFP)',['../group__bt__hfp.html',1,'']]],
  ['frequency_20cpufreq_81',['CPU Frequency (CPUFreq)',['../group__subsys__cpu__freq.html',1,'']]],
  ['frequency_20policy_82',['CPU Frequency Policy',['../group__subsys__cpu__freq__policy.html',1,'']]],
  ['frequency_20pstate_83',['CPU Frequency pstate',['../group__subsys__cpu__freq__pstate.html',1,'']]],
  ['frontend_20stmesp_20demultiplexer_20api_84',['Logging frontend STMESP Demultiplexer API',['../group__log__frontend__stpesp__demux__apis.html',1,'']]],
  ['ft8xx_85',['FTDI FT8xx',['../group__ft8xx__interface.html',1,'']]],
  ['ft8xx_20co_20processor_86',['FT8xx co-processor',['../group__ft8xx__copro.html',1,'']]],
  ['ft8xx_20common_20functions_87',['FT8xx common functions',['../group__ft8xx__common.html',1,'']]],
  ['ft8xx_20display_20list_88',['FT8xx display list',['../group__ft8xx__dl.html',1,'']]],
  ['ft8xx_20memory_20map_89',['FT8xx memory map',['../group__ft8xx__memory.html',1,'']]],
  ['ft8xx_20reference_20api_90',['FT8xx reference API',['../group__ft8xx__reference__api.html',1,'']]],
  ['ft9001_20clock_20identifiers_91',['FocalTech FT9001 clock identifiers',['../group__focaltech__ft9001__clocks.html',1,'']]],
  ['ftdi_20ft8xx_92',['FTDI FT8xx',['../group__ft8xx__interface.html',1,'']]],
  ['ftp_20client_20library_20api_93',['FTP client library API',['../group__ftp__client.html',1,'']]],
  ['fuel_20gauge_94',['Fuel Gauge',['../group__fuel__gauge__interface.html',1,'']]],
  ['fuel_20gauge_20backend_20emulator_20apis_95',['Fuel gauge backend emulator APIs',['../group__fuel__gauge__emulator__backend.html',1,'']]],
  ['function_20apis_96',['Random Function APIs',['../group__random__api.html',1,'']]],
  ['function_20block_20discovery_20message_20filter_20bits_97',['UMP Stream Function Block discovery message filter bits',['../group__midi__ump__fb__disc.html',1,'']]],
  ['function_20devices_98',['Multi-function Devices',['../group__mfd__interfaces.html',1,'']]],
  ['functions_99',['functions',['../group__math__dsp__basic.html',1,'Basic Math Functions'],['../group__dummy.html',1,'Dummy L2/driver Support Functions'],['../group__ethernet__mii.html',1,'Ethernet MII Support Functions'],['../group__ethernet.html',1,'Ethernet Support Functions'],['../group__math__dsp__utils__shifts.html',1,'Float/Fixed point shift conversion functions'],['../group__ft8xx__common.html',1,'FT8xx common functions'],['../group__hash__functions.html',1,'Hash Functions'],['../group__math__ilog2.html',1,'Math Ilog2 Functions'],['../group__math__interpolation.html',1,'Math Interpolation Functions'],['../group__ppp.html',1,'PPP L2/driver Support Functions'],['../group__sys-util.html',1,'Utility Functions'],['../group__virtual.html',1,'Virtual Network Interface Support Functions']]],
  ['futex_20apis_100',['FUTEX APIs',['../group__futex__apis.html',1,'']]],
  ['fw_5fcfg_101',['QEMU fw_cfg',['../group__qemu__fwcfg__interface.html',1,'']]]
];
