var searchData=
[
  ['name_20helpers_0',['Vendor and model name helpers',['../group__devicetree-generic-vendor.html',1,'']]],
  ['name_20processing_1',['Settings name processing',['../group__settings__name__proc.html',1,'']]],
  ['named_20mmio_20region_20macros_2',['Named MMIO region macros',['../group__device-mmio-named.html',1,'']]],
  ['namespace_20compatibility_20mode_20symbols_3',['Network namespace compatibility mode symbols',['../group__net__compat.html',1,'']]],
  ['nano_20header_4',['Arduino Nano header',['../group__arduino-nano-header.html',1,'']]],
  ['navigation_5',['Navigation',['../group__navigation.html',1,'']]],
  ['nct38xx_6',['NCT38XX',['../group__gpio__nct38xx__interface.html',1,'']]],
  ['negate_7',['Vector Negate',['../group__math__dsp__basic__negate.html',1,'']]],
  ['net_20devices_8',['Offloaded Net Devices',['../group__offloaded__netdev.html',1,'']]],
  ['net_20management_9',['IEEE 802.15.4 Net Management',['../group__ieee802154__mgmt.html',1,'']]],
  ['net_5fmgmt_20library_10',['Socket NET_MGMT library',['../group__socket__net__mgmt.html',1,'']]],
  ['network_11',['Network',['../group__subsys__tracing__apis__net.html',1,'']]],
  ['network_20buffer_20library_12',['Network Buffer Library',['../group__net__buf.html',1,'']]],
  ['network_20configuration_20library_13',['Network Configuration Library',['../group__net__config.html',1,'']]],
  ['network_20context_14',['Application network context',['../group__net__context.html',1,'']]],
  ['network_20core_20library_15',['Network Core Library',['../group__net__core.html',1,'']]],
  ['network_20hostname_20library_16',['Network Hostname Library',['../group__net__hostname.html',1,'']]],
  ['network_20interface_20abstraction_20layer_17',['Network Interface abstraction layer',['../group__net__if.html',1,'']]],
  ['network_20interface_20support_20functions_18',['Virtual Network Interface Support Functions',['../group__virtual.html',1,'']]],
  ['network_20l2_20abstraction_20layer_19',['Network L2 Abstraction Layer',['../group__net__l2.html',1,'']]],
  ['network_20layer_20',['1-Wire network layer',['../group__w1__network.html',1,'']]],
  ['network_20link_20address_20library_21',['Network Link Address Library',['../group__net__linkaddr.html',1,'']]],
  ['network_20log_20backend_20api_22',['Network log backend API',['../group__log__backend__net.html',1,'']]],
  ['network_20long_20timeout_20primitives_20and_20helpers_23',['Network long timeout primitives and helpers',['../group__net__timeout.html',1,'']]],
  ['network_20management_24',['Network Management',['../group__net__mgmt.html',1,'']]],
  ['network_20manager_20api_25',['Wi-Fi Network Manager API',['../group__wifi__nm.html',1,'']]],
  ['network_20midi_202_200_26',['Network MIDI 2.0',['../group__net__midi2.html',1,'']]],
  ['network_20namespace_20compatibility_20mode_20symbols_27',['Network namespace compatibility mode symbols',['../group__net__compat.html',1,'']]],
  ['network_20offloading_20interface_28',['Network Offloading Interface',['../group__net__offload.html',1,'']]],
  ['network_20packet_20capture_29',['Network packet capture',['../group__net__capture.html',1,'']]],
  ['network_20packet_20filter_20api_30',['Network Packet Filter API',['../group__net__pkt__filter.html',1,'']]],
  ['network_20packet_20library_31',['Network Packet Library',['../group__net__pkt.html',1,'']]],
  ['network_20socket_32',['Network socket',['../group__subsys__tracing__apis__socket.html',1,'']]],
  ['network_20statistics_20library_33',['Network Statistics Library',['../group__net__stats.html',1,'']]],
  ['network_20time_20representation_34',['Network time representation.',['../group__net__time.html',1,'']]],
  ['networking_35',['Networking',['../group__networking.html',1,'']]],
  ['node_20identifiers_20and_20helpers_36',['Node identifiers and helpers',['../group__devicetree-generic-id.html',1,'']]],
  ['nodes_37',['Chosen nodes',['../group__devicetree-generic-chosen.html',1,'']]],
  ['non_20api_20prototypes_38',['fcb non-API prototypes',['../group__fcb__internal.html',1,'']]],
  ['non_20volatile_20storage_20apis_39',['Non-volatile Storage APIs',['../group__nvs__high__level__api.html',1,'']]],
  ['non_20volatile_20storage_20data_20structures_40',['Non-volatile Storage Data Structures',['../group__nvs__data__structures.html',1,'']]],
  ['non_20volatile_20storage_20nvs_41',['Non-volatile Storage (NVS)',['../group__nvs.html',1,'']]],
  ['nor_20xip_42',['Andes QSPI-NOR XIP',['../group__andes__flash__xip__ex__op.html',1,'']]],
  ['not_43',['Vector bitwise NOT',['../group__math__dsp__basic__not.html',1,'']]],
  ['notification_20apis_44',['Asynchronous Notification APIs',['../group__sys__notify__apis.html',1,'']]],
  ['notification_20service_20ans_45',['Alert Notification Service (ANS)',['../group__bt__ans.html',1,'']]],
  ['npcx_46',['NPCX',['../group__npcx__flash__ex__op.html',1,'']]],
  ['npm10xx_20charger_20interface_47',['nPM10xx Charger interface',['../group__charger__interface__npm10xx.html',1,'']]],
  ['npm10xx_20devicetree_20helpers_48',['nPM10xx Devicetree helpers.',['../group__regulator__npm10xx.html',1,'']]],
  ['npm10xx_20interface_49',['MFD NPM10XX Interface',['../group__mfd__interface__npm10xx.html',1,'']]],
  ['npm10xx_20sensor_20interface_50',['nPM10xx Sensor interface',['../group__sensor__interface__npm10xx.html',1,'']]],
  ['npm1100_20devicetree_20helpers_51',['NPM1100 Devicetree helpers.',['../group__regulator__npm1100.html',1,'']]],
  ['npm13xx_20devicetree_20helpers_52',['nPM13xx Devicetree helpers.',['../group__regulator__npm13xx.html',1,'']]],
  ['npm13xx_20interface_53',['MFD NPM13XX Interface',['../group__mfd__interface__npm13xx.html',1,'']]],
  ['npm13xx_20specific_20gpio_20flags_54',['nPM13xx-specific GPIO Flags',['../group__gpio__interface__npm13xx.html',1,'']]],
  ['npm2100_20devicetree_20helpers_55',['NPM2100 Devicetree helpers.',['../group__regulator__npm2100.html',1,'']]],
  ['npm2100_20interface_56',['MFD NPM2100 Interface',['../group__mdf__interface__npm2100.html',1,'']]],
  ['npm2100_20specific_20gpio_20flags_57',['nPM2100-specific GPIO Flags',['../group__gpio__interface__npm2100.html',1,'']]],
  ['npm6001_20devicetree_20helpers_58',['NPM6001 Devicetree helpers.',['../group__regulator__npm6001.html',1,'']]],
  ['npm6001_20specific_20gpio_20flags_59',['nPM6001-specific GPIO Flags',['../group__gpio__interface__npm6001.html',1,'']]],
  ['nrf_20specific_20gpio_20flags_60',['nRF-specific GPIO Flags',['../group__gpio__interface__nrf.html',1,'']]],
  ['nrf5x_20regulator_20devicetree_20helpers_61',['nRF5X regulator devicetree helpers.',['../group__regulator__nrf5x.html',1,'']]],
  ['numaker_20controller_20devicetree_20helpers_62',['numaker controller devicetree helpers',['../group__clock__controller__nuvoton__m335x.html',1,'Nuvoton NuMaker controller Devicetree helpers'],['../group__reset__controller__nuvoton__m335x.html',1,'Nuvoton NuMaker controller Devicetree helpers']]],
  ['numbers_63',['numbers',['../group__bt__assigned__numbers.html',1,'Assigned Numbers.'],['../group__bt__assigned__numbers__mesh.html',1,'Bluetooth Mesh Assigned Numbers'],['../group__bt__assigned__numbers__core.html',1,'Core Specification Assigned Numbers'],['../group__bt__gap__defines.html',1,'Defines and Assigned Numbers'],['../group__system__errno.html',1,'Error numbers'],['../group__bt__assigned__numbers__audio.html',1,'Generic Audio Assigned Numbers']]],
  ['numbers_20to_20string_20api_64',['Assigned numbers to string API',['../group__bt__audio__to__str.html',1,'']]],
  ['nuvoton_20m48x_20reset_20controller_20devicetree_20helpers_65',['Nuvoton M48X Reset controller Devicetree helpers',['../group__reset__controller__nuvoton__m48x.html',1,'']]],
  ['nuvoton_20numaker_20controller_20devicetree_20helpers_66',['nuvoton numaker controller devicetree helpers',['../group__clock__controller__nuvoton__m335x.html',1,'Nuvoton NuMaker controller Devicetree helpers'],['../group__reset__controller__nuvoton__m335x.html',1,'Nuvoton NuMaker controller Devicetree helpers']]],
  ['nvmctrl_20g1_67',['Microchip NVMCTRL G1',['../group__mchp__nvmctrl__g1__flash__ex__op.html',1,'']]],
  ['nvmem_68',['NVMEM',['../group__nvmem__interface.html',1,'']]],
  ['nvmem_20devicetree_20helpers_69',['NVMEM Devicetree Helpers',['../group__devicetree-nvmem.html',1,'']]],
  ['nvs_70',['Non-volatile Storage (NVS)',['../group__nvs.html',1,'']]],
  ['nxp_20erm_20edac_71',['NXP ERM EDAC',['../group__edac__nxp__erm__interface.html',1,'']]],
  ['nxp_20flexio_72',['NXP FlexIO',['../group__nxp__flexio__interface.html',1,'']]],
  ['nxp_20mcux_20lpc_73',['NXP MCUX LPC',['../group__gpio__mcux__lpc__interface.html',1,'']]],
  ['nxp_20pcal64xxa_74',['NXP PCAL64XXA',['../group__gpio__pcal64xxa__interface.html',1,'']]]
];
