var searchData=
[
  ['uart_0',['UART',['../group__uart__interface.html',1,'']]],
  ['uart_20api_1',['uart api',['../group__uart__async.html',1,'Async UART API'],['../group__uart__interrupt.html',1,'Interrupt-driven UART API'],['../group__uart__polling.html',1,'Polling UART API']]],
  ['uart_20emulation_20interface_2',['UART Emulation Interface',['../group__uart__emul__interface.html',1,'']]],
  ['ubx_3',['Modem Ubx',['../group__modem__ubx.html',1,'']]],
  ['udp_20transport_4',['UDP transport',['../group__mcumgr__transport__udp.html',1,'']]],
  ['ump_20format_20and_20midi_202_200_20protocol_5',['Universal MIDI Packet (UMP) Format and MIDI 2.0 Protocol',['../group__ump112.html',1,'']]],
  ['ump_20stream_20endpoint_20discovery_20message_20filter_20bits_6',['UMP Stream endpoint discovery message filter bits',['../group__midi__ump__ep__disc.html',1,'']]],
  ['ump_20stream_20format_7',['UMP Stream format',['../group__midi__ump__stream__format.html',1,'']]],
  ['ump_20stream_20function_20block_20discovery_20message_20filter_20bits_8',['UMP Stream Function Block discovery message filter bits',['../group__midi__ump__fb__disc.html',1,'']]],
  ['ump_20stream_20responder_9',['UMP Stream Responder',['../group__ump__stream__responder.html',1,'']]],
  ['ump_20stream_20specific_20fields_10',['UMP Stream specific fields',['../group__midi__ump__stream.html',1,'']]],
  ['ump_20stream_20status_11',['UMP Stream status',['../group__midi__ump__stream__status.html',1,'']]],
  ['unicast_20client_20apis_12',['BAP Unicast Client APIs',['../group__bt__bap__unicast__client.html',1,'']]],
  ['unicast_20server_20apis_13',['BAP Unicast Server APIs',['../group__bt__bap__unicast__server.html',1,'']]],
  ['unit_20mmu_20apis_14',['Xtensa Memory Management Unit (MMU) APIs',['../group__xtensa__mmu__apis.html',1,'']]],
  ['unit_20mpu_20apis_15',['Xtensa Memory Protection Unit (MPU) APIs',['../group__xtensa__mpu__apis.html',1,'']]],
  ['units_20helpers_16',['Time Units Helpers',['../group__timeutil__unit__apis.html',1,'']]],
  ['universal_20midi_20packet_20definitions_17',['MIDI2 Universal MIDI Packet definitions',['../group__midi__ump.html',1,'']]],
  ['universal_20midi_20packet_20ump_20format_20and_20midi_202_200_20protocol_18',['Universal MIDI Packet (UMP) Format and MIDI 2.0 Protocol',['../group__ump112.html',1,'']]],
  ['universal_20midi_20packets_19',['User Datagram Protocol for Universal MIDI Packets',['../group__netmidi10.html',1,'']]],
  ['uno_20r3_20header_20',['Arduino Uno (R3) header',['../group__arduino-header-r3.html',1,'']]],
  ['update_21',['Bluetooth Mesh Device Firmware Update',['../group__bt__mesh__dfu.html',1,'']]],
  ['update_20api_22',['USB DFU device update API',['../group__usbd__dfu.html',1,'']]],
  ['update_20dfu_20metadata_23',['Bluetooth Mesh Device Firmware Update (DFU) metadata',['../group__bt__mesh__dfu__metadata.html',1,'']]],
  ['update_20server_20model_24',['Firmware Update Server model',['../group__bt__mesh__dfu__srv.html',1,'']]],
  ['updatehub_20firmware_20over_20the_20air_25',['UpdateHub Firmware Over-the-Air',['../group__updatehub.html',1,'']]],
  ['uppdate_20client_20model_26',['Firmware Uppdate Client model',['../group__bt__mesh__dfu__cli.html',1,'']]],
  ['usb_27',['usb',['../group__usb.html',1,'USB'],['../group__usb__interfaces.html',1,'USB']]],
  ['usb_20audio_20class_202_20device_20api_28',['USB Audio Class 2 device API',['../group__uac2__device.html',1,'']]],
  ['usb_20bos_20support_29',['USB BOS support',['../group__usb__bos.html',1,'']]],
  ['usb_20buffer_20macros_20and_20definitions_30',['USB buffer macros and definitions',['../group__usb__buf.html',1,'']]],
  ['usb_20c_20device_20api_31',['USB-C Device API',['../group____usbc__device__api.html',1,'']]],
  ['usb_20c_20vbus_20api_32',['USB-C VBUS API',['../group__usbc__vbus__api.html',1,'']]],
  ['usb_20device_20controller_33',['USB Device Controller',['../group__udc__api.html',1,'']]],
  ['usb_20device_20controller_20api_34',['USB Device Controller API',['../group____usb__device__controller__api.html',1,'']]],
  ['usb_20device_20core_20api_35',['usb device core api',['../group____usb__device__core__api.html',1,'USB Device Core API'],['../group__usbd__api.html',1,'USB device core API'],['../group__usbd__msg__api.html',1,'USB device core API']]],
  ['usb_20dfu_20device_20update_20api_36',['USB DFU device update API',['../group__usbd__dfu.html',1,'']]],
  ['usb_20hid_20class_20api_37',['USB HID class API',['../group__usb__hid__class.html',1,'']]],
  ['usb_20hid_20common_20definitions_38',['USB HID common definitions',['../group__usb__hid__definitions.html',1,'']]],
  ['usb_20hid_20item_20helpers_39',['USB HID Item helpers',['../group__usb__hid__items.html',1,'']]],
  ['usb_20host_20controller_40',['USB Host Controller',['../group__uhc__api.html',1,'']]],
  ['usb_20host_20core_20api_41',['USB Host Core API',['../group__usb__host__core__api.html',1,'']]],
  ['usb_20mass_20storage_20class_20device_20api_42',['USB Mass Storage Class device API',['../group__usbd__msc__device.html',1,'']]],
  ['usb_20midi_202_200_20class_20device_20api_43',['USB MIDI 2.0 Class device API',['../group__usbd__midi2.html',1,'']]],
  ['usb_20power_20delivery_44',['USB Power Delivery',['../group__usb__power__delivery.html',1,'']]],
  ['usb_20specific_20definitions_45',['HID class USB specific definitions',['../group__usb__hid__device__api.html',1,'']]],
  ['usb_20type_20c_46',['USB Type-C',['../group__usb__type__c.html',1,'']]],
  ['usb_20type_20c_20port_20controller_20api_47',['USB Type-C Port Controller API',['../group__usb__type__c__port__controller__api.html',1,'']]],
  ['usb_20type_20c_20port_20controller_20driver_20backend_20api_48',['USB Type-C Port Controller Driver Backend API',['../group__usb__type__c__port__controller__api__backend.html',1,'']]],
  ['usb_20type_20c_20power_20path_20controller_49',['USB Type-C Power Path Controller',['../group__usb__type__c__power__path__controller.html',1,'']]],
  ['usb_20video_20class_20uvc_20device_20api_50',['USB Video Class (UVC) device API',['../group__usbd__uvc.html',1,'']]],
  ['usbd_20hid_20device_20api_51',['USBD HID device API',['../group__usbd__hid__device.html',1,'']]],
  ['user_20datagram_20protocol_20for_20universal_20midi_20packets_52',['User Datagram Protocol for Universal MIDI Packets',['../group__netmidi10.html',1,'']]],
  ['user_20defined_20event_53',['User-defined event',['../group__subsys__tracing__apis__named.html',1,'']]],
  ['user_20mode_20and_20syscall_20apis_54',['User mode and Syscall APIs',['../group__syscall__apis.html',1,'']]],
  ['user_20mode_20apis_55',['User Mode APIs',['../group__usermode__apis.html',1,'']]],
  ['user_20mode_20internal_20apis_56',['User Mode Internal APIs',['../group__usermode__internal__apis.html',1,'']]],
  ['user_20mode_20mutex_20apis_57',['User mode mutex APIs',['../group__user__mutex__apis.html',1,'']]],
  ['user_20mode_20semaphore_20apis_58',['User mode semaphore APIs',['../group__user__semaphore__apis.html',1,'']]],
  ['userspace_20apis_59',['Architecture-specific userspace APIs',['../group__arch-userspace.html',1,'']]],
  ['utilities_60',['utilities',['../group__input__keymap.html',1,'Keymap utilities'],['../group__regulator__parent__pca9420.html',1,'PCA9420 Utilities.'],['../group__utilities.html',1,'Utilities'],['../group__scmi__util.html',1,'Utilities']]],
  ['utility_20apis_61',['utility apis',['../group__timeutil__apis.html',1,'Time Utility APIs'],['../group__timeutil__timespec__apis.html',1,'Timespec Utility APIs']]],
  ['utility_20functions_62',['Utility Functions',['../group__sys-util.html',1,'']]],
  ['utility_20macros_63',['Tracing utility macros',['../group__subsys__tracing__macros.html',1,'']]],
  ['uuid_64',['UUID',['../group__uuid.html',1,'']]],
  ['uuids_65',['UUIDs',['../group__bt__uuid.html',1,'']]],
  ['uvc_20device_20api_66',['USB Video Class (UVC) device API',['../group__usbd__uvc.html',1,'']]]
];
