var searchData=
[
  ['m_0',['ExplorIR-M',['../group__explorir__m__interface.html',1,'']]],
  ['m48x_20reset_20controller_20devicetree_20helpers_1',['Nuvoton M48X Reset controller Devicetree helpers',['../group__reset__controller__nuvoton__m48x.html',1,'']]],
  ['machine_20framework_20api_2',['State Machine Framework API',['../group__smf.html',1,'']]],
  ['macros_3',['macros',['../group__devicetree-generic-foreach.html',1,'&quot;For-each&quot; macros'],['../group__focaltech__reset__macros.html',1,'FocalTech Reset Configuration Macros'],['../group__hl78xx__constants.html',1,'HL78xx Constants and Macros'],['../group__lwm2m__path__helpers.html',1,'LwM2M path helper macros'],['../group__mspi__devicetree.html',1,'MSPI Devicetree related macros'],['../group__device-mmio-named.html',1,'Named MMIO region macros'],['../group__device-mmio-single.html',1,'Single MMIO region macros'],['../group__device-mmio-toplevel.html',1,'Top-level MMIO region macros'],['../group__subsys__tracing__macros.html',1,'Tracing utility macros'],['../group__ztest__assert.html',1,'Ztest assertion macros'],['../group__ztest__assume.html',1,'Ztest assumption macros'],['../group__ztest__expect.html',1,'Ztest expectation macros'],['../group__ztest__test.html',1,'Ztest testing macros'],['../group__ztest__ztress.html',1,'Ztest ztress macros']]],
  ['macros_20and_20definitions_4',['USB buffer macros and definitions',['../group__usb__buf.html',1,'']]],
  ['macros_20for_20printing_20q_20values_5',['Helper macros for printing Q values.',['../group__math__printing.html',1,'']]],
  ['mailbox_6',['Mailbox',['../group__subsys__tracing__apis__mbox.html',1,'']]],
  ['mailbox_20apis_7',['Mailbox APIs',['../group__mailbox__apis.html',1,'']]],
  ['management_8',['management',['../group__bt__conn.html',1,'Connection management'],['../group__power__management__cpu__api.html',1,'CPU Power Management'],['../group__device__mgmt.html',1,'Device Management'],['../group__device-mmio.html',1,'Device memory-mapped IO management'],['../group__mcumgr__enum__mgmt.html',1,'Enumeration Management'],['../group__mcumgr__fs__mgmt.html',1,'File System Management'],['../group__heaps.html',1,'Heap Management'],['../group__ieee802154__mgmt.html',1,'IEEE 802.15.4 Net Management'],['../group__mcumgr__img__mgmt.html',1,'Image Management'],['../group__kernel__memory__management.html',1,'Kernel Memory Management'],['../group__mcumgr__mgmt__api.html',1,'Management'],['../group__memory__management.html',1,'Memory Management'],['../group__net__mgmt.html',1,'Network Management'],['../group__mcumgr__os__mgmt.html',1,'OS Management'],['../group__mcumgr__settings__mgmt.html',1,'Settings Management'],['../group__mcumgr__shell__mgmt.html',1,'Shell Management'],['../group__mcumgr__stat__mgmt.html',1,'Statistics Management'],['../group__tls__credentials.html',1,'TLS credentials management'],['../group__wifi__mgmt.html',1,'Wi-Fi Management'],['../group__mcumgr__zephyr__basic__mgmt.html',1,'Zephyr Basic Management']]],
  ['management_20apis_9',['management apis',['../group__arch-pm.html',1,'Architecture-specific power management APIs'],['../group__mem__mgmt.html',1,'Memory Management APIs']]],
  ['management_20callbacks_10',['management callbacks',['../group__mcumgr__callback__api__enum__mgmt.html',1,'Enumeration Management Callbacks'],['../group__mcumgr__callback__api__fs__mgmt.html',1,'File System Management Callbacks'],['../group__mcumgr__callback__api__img__mgmt.html',1,'Image Management Callbacks'],['../group__mcumgr__callback__api__os__mgmt.html',1,'OS Management Callbacks'],['../group__mcumgr__callback__api__settings__mgmt.html',1,'Settings Management Callbacks']]],
  ['management_20client_11',['management client',['../group__mcumgr__img__mgmt__client.html',1,'Image Management Client'],['../group__mcumgr__os__mgmt__client.html',1,'OS Management Client']]],
  ['management_20driver_20apis_12',['Memory Management Driver APIs',['../group__mm__drv__apis.html',1,'']]],
  ['management_20interface_13',['IEEE 802.3 management interface',['../group__ethernet__mdio.html',1,'']]],
  ['management_20internal_20apis_14',['Kernel Memory Management Internal APIs',['../group__kernel__mm__internal__apis.html',1,'']]],
  ['management_20pm_15',['Power Management (PM)',['../group__subsys__pm.html',1,'']]],
  ['management_20unit_20mmu_20apis_16',['Xtensa Memory Management Unit (MMU) APIs',['../group__xtensa__mmu__apis.html',1,'']]],
  ['manager_20api_17',['manager api',['../group__conn__mgr.html',1,'Connection Manager API'],['../group__wifi__nm.html',1,'Wi-Fi Network Manager API']]],
  ['manager_20connectivity_20api_18',['Connection Manager Connectivity API',['../group__conn__mgr__connectivity.html',1,'']]],
  ['manager_20connectivity_20bulk_20api_19',['Connection Manager Connectivity Bulk API',['../group__conn__mgr__connectivity__bulk.html',1,'']]],
  ['manager_20connectivity_20implementation_20api_20',['Connection Manager Connectivity Implementation API',['../group__conn__mgr__connectivity__impl.html',1,'']]],
  ['manager_20events_21',['CoAP Manager Events',['../group__coap__mgmt.html',1,'']]],
  ['map_22',['FT8xx memory map',['../group__ft8xx__memory.html',1,'']]],
  ['map_20helpers_23',['Map helpers',['../group__devicetree-map.html',1,'']]],
  ['mapped_20io_20management_24',['Device memory-mapped IO management',['../group__device-mmio.html',1,'']]],
  ['mapped_20partition_20api_25',['Devicetree Mapped Partition API',['../group__devicetree-mapped-partition.html',1,'']]],
  ['mapping_20apis_26',['Architecture-specific memory-mapping APIs',['../group__arch-mmu.html',1,'']]],
  ['mass_20storage_20class_20device_20api_27',['USB Mass Storage Class device API',['../group__usbd__msc__device.html',1,'']]],
  ['math_20extras_28',['Math extras',['../group__math__extras.html',1,'']]],
  ['math_20functions_29',['Basic Math Functions',['../group__math__dsp__basic.html',1,'']]],
  ['math_20ilog2_20functions_30',['Math Ilog2 Functions',['../group__math__ilog2.html',1,'']]],
  ['math_20interpolation_20functions_31',['Math Interpolation Functions',['../group__math__interpolation.html',1,'']]],
  ['matrix_32',['Keyboard Matrix',['../group__input__kbd__matrix.html',1,'']]],
  ['max17055_33',['MAX17055',['../group__max17055__interface.html',1,'']]],
  ['max20335_20devicetree_20helpers_34',['MAX20335 Devicetree helpers.',['../group__regulator__max20335.html',1,'']]],
  ['max22017_20interface_35',['MFD MAX22017 interface',['../group__mdf__interface__max22017.html',1,'']]],
  ['max2221x_36',['MFD MAX2221X',['../group__mfd__interface__max2221x.html',1,'']]],
  ['max2221x_20misc_37',['MAX2221X MISC',['../group__max2221x__interface.html',1,'']]],
  ['max2221x_20pwm_38',['MAX2221X PWM',['../group__pwm__max2221x__interface.html',1,'']]],
  ['max30210_39',['MAX30210',['../group__max30210__interface.html',1,'']]],
  ['max31790_40',['max31790',['../group__pwm__max31790__interface.html',1,'MAX31790'],['../group__max31790__interface.html',1,'MAX31790']]],
  ['max32_20specific_20gpio_20flags_41',['MAX32-specific GPIO Flags',['../group__gpio__interface__max32.html',1,'']]],
  ['max32664c_42',['MAX32664C',['../group__max32664c__interface.html',1,'']]],
  ['mbox_43',['MBOX',['../group__mbox__interface.html',1,'']]],
  ['mbox_20api_44',['Devicetree MBOX API',['../group__devicetree-mbox.html',1,'']]],
  ['mcc_45',['Media Control Client (MCC)',['../group__bt__mcc.html',1,'']]],
  ['mcp9600_46',['MCP9600',['../group__mcp9600__interface.html',1,'']]],
  ['mcp9600_20dt_20options_47',['MCP9600 DT Options',['../group__mcp9600.html',1,'']]],
  ['mcs_48',['Media Control Service (MCS)',['../group__bt__mcs.html',1,'']]],
  ['mcuboot_20image_20control_20api_49',['MCUboot image control API',['../group__mcuboot__api.html',1,'']]],
  ['mcumgr_50',['MCUmgr',['../group__mcumgr.html',1,'']]],
  ['mcux_51',['QDEC MCUX',['../group__sensor__qdec__mcux.html',1,'']]],
  ['mcux_20lpc_52',['NXP MCUX LPC',['../group__gpio__mcux__lpc__interface.html',1,'']]],
  ['mdio_53',['MDIO',['../group__mdio__interface.html',1,'']]],
  ['measurement_20apis_54',['measurement apis',['../group__timing__api__arch.html',1,'Arch specific Timing Measurement APIs'],['../group__timing__api__board.html',1,'Board specific Timing Measurement APIs'],['../group__timing__api__soc.html',1,'SoC specific Timing Measurement APIs'],['../group__timing__api.html',1,'Timing Measurement APIs']]],
  ['media_20audio_20profile_20tmap_55',['Telephone and Media Audio Profile (TMAP)',['../group__bt__tmap.html',1,'']]],
  ['media_20control_20client_20mcc_56',['Media Control Client (MCC)',['../group__bt__mcc.html',1,'']]],
  ['media_20control_20service_20mcs_57',['Media Control Service (MCS)',['../group__bt__mcs.html',1,'']]],
  ['media_20proxy_58',['Media Proxy',['../group__bt__media__proxy.html',1,'']]],
  ['memory_59',['memory',['../group__ivshmem.html',1,'Inter-VM Shared Memory'],['../group__otp__interface.html',1,'One Time Programmable Memory'],['../group__retained__mem__interface.html',1,'Retained memory'],['../group__scmi__shmem.html',1,'Shared Memory']]],
  ['memory_20attribute_20interface_60',['Memory Attribute Interface',['../group__memory__attr__interface.html',1,'']]],
  ['memory_20banks_20driver_20apis_61',['Memory Banks Driver APIs',['../group__mm__drv__bank__apis.html',1,'']]],
  ['memory_20blocks_20apis_62',['Memory Blocks APIs',['../group__mem__blocks__apis.html',1,'']]],
  ['memory_20domain_20apis_63',['memory domain apis',['../group__mem__domain__apis__app.html',1,'Application memory domain APIs'],['../group__mem__domain__apis.html',1,'Memory domain APIs']]],
  ['memory_20driver_20backend_20api_64',['Retained Memory Driver Backend API',['../group__retained__mem__interface__backend.html',1,'']]],
  ['memory_20heaps_20based_20on_20memory_20attributes_65',['Memory heaps based on memory attributes',['../group__memory__attr__heap.html',1,'']]],
  ['memory_20management_66',['memory management',['../group__kernel__memory__management.html',1,'Kernel Memory Management'],['../group__memory__management.html',1,'Memory Management']]],
  ['memory_20management_20apis_67',['Memory Management APIs',['../group__mem__mgmt.html',1,'']]],
  ['memory_20management_20driver_20apis_68',['Memory Management Driver APIs',['../group__mm__drv__apis.html',1,'']]],
  ['memory_20management_20internal_20apis_69',['Kernel Memory Management Internal APIs',['../group__kernel__mm__internal__apis.html',1,'']]],
  ['memory_20management_20unit_20mmu_20apis_70',['Xtensa Memory Management Unit (MMU) APIs',['../group__xtensa__mmu__apis.html',1,'']]],
  ['memory_20map_71',['FT8xx memory map',['../group__ft8xx__memory.html',1,'']]],
  ['memory_20mapped_20io_20management_72',['Device memory-mapped IO management',['../group__device-mmio.html',1,'']]],
  ['memory_20mapping_20apis_73',['Architecture-specific memory-mapping APIs',['../group__arch-mmu.html',1,'']]],
  ['memory_20protection_20unit_20mpu_20apis_74',['Xtensa Memory Protection Unit (MPU) APIs',['../group__xtensa__mpu__apis.html',1,'']]],
  ['memory_20slab_75',['Memory slab',['../group__subsys__tracing__apis__mslab.html',1,'']]],
  ['memory_20slab_20apis_76',['Memory Slab APIs',['../group__mem__slab__apis.html',1,'']]],
  ['memory_20storage_20zms_77',['Zephyr Memory Storage (ZMS)',['../group__zms.html',1,'']]],
  ['memsic_20dt_20options_78',['Memsic DT Options',['../group__mc3419.html',1,'']]],
  ['mesh_79',['Bluetooth Mesh',['../group__bt__mesh.html',1,'']]],
  ['mesh_20assigned_20numbers_80',['Bluetooth Mesh Assigned Numbers',['../group__bt__assigned__numbers__mesh.html',1,'']]],
  ['mesh_20blob_20flash_20stream_81',['Bluetooth Mesh BLOB flash stream',['../group__bt__mesh__blob__io__flash.html',1,'']]],
  ['mesh_20blob_20model_20api_82',['Bluetooth Mesh BLOB model API',['../group__bt__mesh__blob.html',1,'']]],
  ['mesh_20blob_20transfer_20client_20model_20api_83',['Bluetooth Mesh BLOB Transfer Client model API',['../group__bt__mesh__blob__cli.html',1,'']]],
  ['mesh_20blob_20transfer_20server_20model_20api_84',['Bluetooth Mesh BLOB Transfer Server model API',['../group__bt__mesh__blob__srv.html',1,'']]],
  ['mesh_20device_20firmware_20update_85',['Bluetooth Mesh Device Firmware Update',['../group__bt__mesh__dfu.html',1,'']]],
  ['mesh_20device_20firmware_20update_20dfu_20metadata_86',['Bluetooth Mesh Device Firmware Update (DFU) metadata',['../group__bt__mesh__dfu__metadata.html',1,'']]],
  ['mesh_20on_20demand_20private_20gatt_20proxy_20client_87',['Bluetooth Mesh On-Demand Private GATT Proxy Client',['../group__bt__mesh__od__priv__proxy__cli.html',1,'']]],
  ['mesh_20on_20demand_20private_20gatt_20proxy_20server_88',['Bluetooth Mesh On-Demand Private GATT Proxy Server',['../group__bt__mesh__od__priv__proxy__srv.html',1,'']]],
  ['mesh_20private_20beacon_20client_89',['Bluetooth Mesh Private Beacon Client',['../group__bt__mesh__priv__beacon__cli.html',1,'']]],
  ['mesh_20private_20beacon_20server_90',['Bluetooth Mesh Private Beacon Server',['../group__bt__mesh__priv__beacon__srv.html',1,'']]],
  ['mesh_20sar_20configuration_20client_20model_91',['Bluetooth Mesh SAR Configuration Client Model',['../group__bt__mesh__sar__cfg__cli.html',1,'']]],
  ['mesh_20sar_20configuration_20server_20model_92',['Bluetooth Mesh SAR Configuration Server Model',['../group__bt__mesh__sar__cfg__srv.html',1,'']]],
  ['mesh_20solicitation_20pdu_20rpl_20client_93',['Bluetooth Mesh Solicitation PDU RPL Client',['../group__bt__mesh__sol__pdu__rpl__cli.html',1,'']]],
  ['mesh_20solicitation_20pdu_20rpl_20server_94',['Bluetooth Mesh Solicitation PDU RPL Server',['../group__bt__mesh__sol__pdu__rpl__srv.html',1,'']]],
  ['message_95',['Message',['../group__bt__mesh__msg.html',1,'']]],
  ['message_20api_96',['Log message API',['../group__log__msg.html',1,'']]],
  ['message_20filter_20bits_97',['message filter bits',['../group__midi__ump__ep__disc.html',1,'UMP Stream endpoint discovery message filter bits'],['../group__midi__ump__fb__disc.html',1,'UMP Stream Function Block discovery message filter bits']]],
  ['message_20queue_98',['Message queue',['../group__subsys__tracing__apis__msgq.html',1,'']]],
  ['message_20queue_20apis_99',['Message Queue APIs',['../group__msgq__apis.html',1,'']]],
  ['message_20status_100',['System common and System Real Time message status',['../group__midi__ump__sys.html',1,'']]],
  ['message_20types_101',['Message types',['../group__midi__ump__mt.html',1,'']]],
  ['metadata_102',['Bluetooth Mesh Device Firmware Update (DFU) metadata',['../group__bt__mesh__dfu__metadata.html',1,'']]],
  ['methods_103',['HTTP request methods',['../group__http__methods.html',1,'']]],
  ['mfd_20ad559x_20interface_104',['MFD AD559X interface',['../group__mdf__interface__ad559x.html',1,'']]],
  ['mfd_20axp192_20interface_105',['MFD AXP192 interface',['../group__mdf__interface__axp192.html',1,'']]],
  ['mfd_20bd8lb600fs_20interface_106',['MFD BD8LB600FS interface',['../group__mdf__interface__bd8lb600fs.html',1,'']]],
  ['mfd_20max22017_20interface_107',['MFD MAX22017 interface',['../group__mdf__interface__max22017.html',1,'']]],
  ['mfd_20max2221x_108',['MFD MAX2221X',['../group__mfd__interface__max2221x.html',1,'']]],
  ['mfd_20npm10xx_20interface_109',['MFD NPM10XX Interface',['../group__mfd__interface__npm10xx.html',1,'']]],
  ['mfd_20npm13xx_20interface_110',['MFD NPM13XX Interface',['../group__mfd__interface__npm13xx.html',1,'']]],
  ['mfd_20npm2100_20interface_111',['MFD NPM2100 Interface',['../group__mdf__interface__npm2100.html',1,'']]],
  ['mfd_20pca9422_20interface_112',['MFD PCA9422 Interface',['../group__mdf__interface__pca9422.html',1,'']]],
  ['mh_20z19b_113',['MH-Z19B',['../group__mhz19b__interface.html',1,'']]],
  ['micp_114',['Microphone Control Profile (MICP)',['../group__bt__micp.html',1,'']]],
  ['micro_3abit_20display_20apis_115',['BBC micro:bit display APIs',['../group__mb__display.html',1,'']]],
  ['microchip_116',['Microchip',['../group__mchp__flash__interface.html',1,'']]],
  ['microchip_20nvmctrl_20g1_117',['Microchip NVMCTRL G1',['../group__mchp__nvmctrl__g1__flash__ex__op.html',1,'']]],
  ['microphone_20control_20profile_20micp_118',['Microphone Control Profile (MICP)',['../group__bt__micp.html',1,'']]],
  ['microphone_20interface_119',['Digital Microphone Interface',['../group__audio__dmic__interface.html',1,'']]],
  ['midi_202_200_120',['Network MIDI 2.0',['../group__net__midi2.html',1,'']]],
  ['midi_202_200_20class_20device_20api_121',['USB MIDI 2.0 Class device API',['../group__usbd__midi2.html',1,'']]],
  ['midi_20commands_122',['MIDI commands',['../group__midi__ump__cmd.html',1,'']]],
  ['midi_20packet_20definitions_123',['MIDI2 Universal MIDI Packet definitions',['../group__midi__ump.html',1,'']]],
  ['midi_20packet_20ump_20format_20and_20midi_202_200_20protocol_124',['Universal MIDI Packet (UMP) Format and MIDI 2.0 Protocol',['../group__ump112.html',1,'']]],
  ['midi_20packets_125',['User Datagram Protocol for Universal MIDI Packets',['../group__netmidi10.html',1,'']]],
  ['midi2_20universal_20midi_20packet_20definitions_126',['MIDI2 Universal MIDI Packet definitions',['../group__midi__ump.html',1,'']]],
  ['mii_20support_20functions_127',['Ethernet MII Support Functions',['../group__ethernet__mii.html',1,'']]],
  ['min_20heap_20service_128',['Min-Heap service',['../group__min__heap__apis.html',1,'']]],
  ['mipi_20dbi_129',['MIPI-DBI',['../group__mipi__dbi__interface.html',1,'']]],
  ['mipi_20dbi_20driver_20backend_20api_130',['MIPI-DBI Driver Backend API',['../group__mipi__dbi__interface__backend.html',1,'']]],
  ['mipi_20display_20interface_131',['MIPI Display interface',['../group__mipi__interface.html',1,'']]],
  ['mipi_20dsi_132',['MIPI-DSI',['../group__mipi__dsi__interface.html',1,'']]],
  ['misc_133',['MAX2221X MISC',['../group__max2221x__interface.html',1,'']]],
  ['miscellaneous_20architecture_20apis_134',['Miscellaneous architecture APIs',['../group__arch-misc.html',1,'']]],
  ['miscellaneous_20devices_135',['Miscellaneous Devices',['../group__misc__interfaces.html',1,'']]],
  ['mkr_20header_136',['Arduino MKR header',['../group__arduino-mkr-header.html',1,'']]],
  ['mldx5_137',['FCX-MLDX5',['../group__fcx__mldx5__interface.html',1,'']]],
  ['mlx90394_138',['MLX90394',['../group__mlx90394__interface.html',1,'']]],
  ['mmc56x3_139',['MMC56X3',['../group__mmc56x3__interface.html',1,'']]],
  ['mmio_20region_20macros_140',['mmio region macros',['../group__device-mmio-named.html',1,'Named MMIO region macros'],['../group__device-mmio-single.html',1,'Single MMIO region macros'],['../group__device-mmio-toplevel.html',1,'Top-level MMIO region macros']]],
  ['mmu_20apis_141',['Xtensa Memory Management Unit (MMU) APIs',['../group__xtensa__mmu__apis.html',1,'']]],
  ['mocking_20support_142',['Ztest mocking support',['../group__ztest__mock.html',1,'']]],
  ['modbus_143',['MODBUS',['../group__modbus.html',1,'']]],
  ['mode_144',['Promiscuous mode',['../group__promiscuous.html',1,'']]],
  ['mode_20and_20syscall_20apis_145',['User mode and Syscall APIs',['../group__syscall__apis.html',1,'']]],
  ['mode_20apis_146',['User Mode APIs',['../group__usermode__apis.html',1,'']]],
  ['mode_20interface_147',['Boot mode interface',['../group__boot__mode__interface.html',1,'']]],
  ['mode_20internal_20apis_148',['User Mode Internal APIs',['../group__usermode__internal__apis.html',1,'']]],
  ['mode_20mutex_20apis_149',['User mode mutex APIs',['../group__user__mutex__apis.html',1,'']]],
  ['mode_20options_150',['mode options',['../group__ADXL372__FIFO__MODE.html',1,'FIFO mode options'],['../group__adxl362__fifo__mode.html',1,'FIFO mode options'],['../group__adxl367__fifo__mode.html',1,'FIFO mode options']]],
  ['mode_20semaphore_20apis_151',['User mode semaphore APIs',['../group__user__semaphore__apis.html',1,'']]],
  ['mode_20symbols_152',['Network namespace compatibility mode symbols',['../group__net__compat.html',1,'']]],
  ['model_153',['model',['../group__bt__mesh__sar__cfg__cli.html',1,'Bluetooth Mesh SAR Configuration Client Model'],['../group__bt__mesh__sar__cfg__srv.html',1,'Bluetooth Mesh SAR Configuration Server Model'],['../group__bt__mesh__brg__cfg__cli.html',1,'Bridge Configuration Client Model'],['../group__bt__mesh__brg__cfg__srv.html',1,'Bridge Configuration Server Model'],['../group__bt__mesh__cfg__cli.html',1,'Configuration Client Model'],['../group__bt__mesh__cfg__srv.html',1,'Configuration Server Model'],['../group__device__model.html',1,'Device Model'],['../group__bt__mesh__dfd__srv.html',1,'Firmware Distribution Server model'],['../group__bt__mesh__dfu__srv.html',1,'Firmware Update Server model'],['../group__bt__mesh__dfu__cli.html',1,'Firmware Uppdate Client model'],['../group__bt__mesh__health__cli.html',1,'Health Client Model'],['../group__bt__mesh__health__srv.html',1,'Health Server Model'],['../group__bt__mesh__large__comp__data__cli.html',1,'Large Composition Data Client model'],['../group__bt__mesh__large__comp__data__srv.html',1,'Large Composition Data Server model'],['../group__bt__mesh__op__agg__cli.html',1,'Opcodes Aggregator Client model'],['../group__bt__mesh__op__agg__srv.html',1,'Opcodes Aggregator Server model'],['../group__bt__mesh__rpr__cli.html',1,'Remote Provisioning Client model']]],
  ['model_20api_154',['model api',['../group__bt__mesh__blob.html',1,'Bluetooth Mesh BLOB model API'],['../group__bt__mesh__blob__cli.html',1,'Bluetooth Mesh BLOB Transfer Client model API'],['../group__bt__mesh__blob__srv.html',1,'Bluetooth Mesh BLOB Transfer Server model API']]],
  ['model_20name_20helpers_155',['Vendor and model name helpers',['../group__devicetree-generic-vendor.html',1,'']]],
  ['models_156',['models',['../group__bt__mesh__dfd.html',1,'Firmware Distribution models'],['../group__bt__mesh__rpr.html',1,'Remote Provisioning models']]],
  ['modem_20apis_157',['Modem APIs',['../group__modem.html',1,'']]],
  ['modem_20chat_158',['Modem Chat',['../group__modem__chat.html',1,'']]],
  ['modem_20cmux_159',['Modem CMUX',['../group__modem__cmux.html',1,'']]],
  ['modem_20pipe_160',['Modem Pipe',['../group__modem__pipe.html',1,'']]],
  ['modem_20pipelink_161',['Modem pipelink',['../group__modem__pipelink.html',1,'']]],
  ['modem_20ppp_162',['Modem PPP',['../group__modem__ppp.html',1,'']]],
  ['modem_20ubx_163',['Modem Ubx',['../group__modem__ubx.html',1,'']]],
  ['modes_164',['modes',['../group__ICM42686__ACCEL__POWER__MODES.html',1,'Accelerometer power modes'],['../group__icm42688__accel__power__modes.html',1,'Accelerometer power modes'],['../group__ICM4268X__ACCEL__POWER__MODES.html',1,'Accelerometer power modes'],['../group__ICM45686__ACCEL__POWER__MODES.html',1,'Accelerometer power modes'],['../group__ICM45686__GYRO__POWER__MODES.html',1,'Gyroscope power modes'],['../group__icm42688__gyro__power__modes.html',1,'Gyroscope power modes'],['../group__ICM42686__GYRO__POWER__MODES.html',1,'Gyroscope power modes'],['../group__ICM4268X__GYRO__POWER__MODES.html',1,'Gyroscope power modes'],['../group__bmp581__power__modes.html',1,'Sensor power modes']]],
  ['module_20registers_165',['FocalTech Reset Control Module Registers',['../group__focaltech__reset__regs.html',1,'']]],
  ['monitor_166',['monitor',['../group__cpu__load.html',1,'CPU load monitor'],['../group__latmon.html',1,'Latency Monitor']]],
  ['monochrome_20character_20framebuffer_167',['Monochrome Character Framebuffer',['../group__monochrome__character__framebuffer.html',1,'']]],
  ['morpho_20header_168',['ST Morpho header',['../group__st-morpho-header.html',1,'']]],
  ['motion_20controller_169',['Stepper Motion Controller',['../group__stepper__ctrl.html',1,'']]],
  ['motion_20controller_20driver_20backend_20api_170',['Stepper Motion Controller Driver Backend API',['../group__stepper__ctrl__backend.html',1,'']]],
  ['mouse_20and_20keyboard_20report_20descriptors_171',['Mouse and keyboard report descriptors',['../group__usb__hid__mk__report__desc.html',1,'']]],
  ['mpsc_20lockfree_20queue_20api_172',['MPSC Lockfree Queue API',['../group__mpsc__lockfree.html',1,'']]],
  ['mpsc_20multi_20producer_20single_20consumer_20packet_20buffer_20api_173',['MPSC (Multi producer, single consumer) packet buffer API',['../group__mpsc__buf.html',1,'']]],
  ['mpsc_20multi_20producer_20single_20consumer_20packet_20header_174',['MPSC (Multi producer, single consumer) packet header',['../group__mpsc__packet.html',1,'']]],
  ['mpsc_20packet_20buffer_20flags_175',['MPSC packet buffer flags',['../group__MPSC__PBUF__FLAGS.html',1,'']]],
  ['mpu_20apis_176',['Xtensa Memory Protection Unit (MPU) APIs',['../group__xtensa__mpu__apis.html',1,'']]],
  ['mqtt_20client_20library_177',['MQTT Client library',['../group__mqtt__socket.html',1,'']]],
  ['mqtt_20log_20backend_20api_178',['MQTT log backend API',['../group__log__backend__mqtt.html',1,'']]],
  ['mqtt_20sn_20client_20library_179',['MQTT-SN Client library',['../group__mqtt__sn__socket.html',1,'']]],
  ['msi_20interface_180',['PCIe Host MSI Interface',['../group__pcie__host__msi__interface.html',1,'']]],
  ['mspi_181',['MSPI',['../group__mspi__interface.html',1,'']]],
  ['mspi_20callback_20api_182',['MSPI callback API',['../group__mspi__callback__api.html',1,'']]],
  ['mspi_20configure_20api_183',['MSPI Configure API',['../group__mspi__configure__api.html',1,'']]],
  ['mspi_20devicetree_20related_20macros_184',['MSPI Devicetree related macros',['../group__mspi__devicetree.html',1,'']]],
  ['mspi_20emulation_20interface_185',['MSPI Emulation Interface',['../group__mspi__emul__interface.html',1,'']]],
  ['mspi_20transfer_20api_186',['MSPI Transfer API',['../group__mspi__transfer__api.html',1,'']]],
  ['mspi_5futil_187',['Mspi_util',['../group__mspi__util.html',1,'']]],
  ['mtrace_20log_20backend_20api_188',['Intel ADSP mtrace log backend API',['../group__log__backend__adsp__mtrace.html',1,'']]],
  ['multi_20endpoint_20ipc_20library_20api_189',['Icmsg multi-endpoint IPC library API',['../group__ipc__icmsg__me__api.html',1,'']]],
  ['multi_20function_20devices_190',['Multi-function Devices',['../group__mfd__interfaces.html',1,'']]],
  ['multi_20heap_20interface_191',['Shared multi-heap interface',['../group__shared__multi__heap.html',1,'']]],
  ['multi_20heap_20wrapper_192',['Multi-Heap Wrapper',['../group__multi__heap__wrapper.html',1,'']]],
  ['multi_20producer_20single_20consumer_20packet_20buffer_20api_193',['MPSC (Multi producer, single consumer) packet buffer API',['../group__mpsc__buf.html',1,'']]],
  ['multi_20producer_20single_20consumer_20packet_20header_194',['MPSC (Multi producer, single consumer) packet header',['../group__mpsc__packet.html',1,'']]],
  ['multicast_20listener_20discovery_20api_195',['Multicast Listener Discovery API',['../group__mld.html',1,'']]],
  ['multidomain_20backend_20helpers_196',['Logger multidomain backend helpers',['../group__log__backend__multidomain.html',1,'']]],
  ['multiplication_197',['Vector Multiplication',['../group__math__dsp__basic__mult.html',1,'']]],
  ['multirstcr_20reset_20control_198',['MULTIRSTCR Reset Control',['../group__focaltech__multirstcr__resets.html',1,'']]],
  ['mutex_199',['Mutex',['../group__subsys__tracing__apis__mutex.html',1,'']]],
  ['mutex_20apis_200',['mutex apis',['../group__mutex__apis.html',1,'Mutex APIs'],['../group__user__mutex__apis.html',1,'User mode mutex APIs']]]
];
