var searchData=
[
  ['g1_0',['Microchip NVMCTRL G1',['../group__mchp__nvmctrl__g1__flash__ex__op.html',1,'']]],
  ['gaming_20audio_20profile_1',['Bluetooth Gaming Audio Profile',['../group__bt__gmap.html',1,'']]],
  ['gaming_20audio_20profile_20gmap_20lc3_20presets_2',['Gaming Audio Profile (GMAP) LC3 Presets',['../group__bt__gmap__lc3__preset.html',1,'']]],
  ['gap_3',['Generic Access Profile (GAP)',['../group__bt__gap.html',1,'']]],
  ['gateway_20hfp_20ag_4',['Hands Free Profile - Audio Gateway (HFP-AG)',['../group__bt__hfp__ag.html',1,'']]],
  ['gatt_5',['Generic Attribute Profile (GATT)',['../group__bt__gatt.html',1,'']]],
  ['gatt_20client_20apis_6',['GATT Client APIs',['../group__bt__gatt__client.html',1,'']]],
  ['gatt_20proxy_20client_7',['Bluetooth Mesh On-Demand Private GATT Proxy Client',['../group__bt__mesh__od__priv__proxy__cli.html',1,'']]],
  ['gatt_20proxy_20server_8',['Bluetooth Mesh On-Demand Private GATT Proxy Server',['../group__bt__mesh__od__priv__proxy__srv.html',1,'']]],
  ['gatt_20server_20apis_9',['GATT Server APIs',['../group__bt__gatt__server.html',1,'']]],
  ['gauge_10',['Fuel Gauge',['../group__fuel__gauge__interface.html',1,'']]],
  ['gauge_20backend_20emulator_20apis_11',['Fuel gauge backend emulator APIs',['../group__fuel__gauge__emulator__backend.html',1,'']]],
  ['gdbstub_20apis_12',['Architecture-specific gdbstub APIs',['../group__arch-gdbstub.html',1,'']]],
  ['generators_13',['Renesas RA Clock Divider Generators',['../group__ra__cgc__div.html',1,'']]],
  ['generic_20access_20profile_20gap_14',['Generic Access Profile (GAP)',['../group__bt__gap.html',1,'']]],
  ['generic_20attribute_20profile_20gatt_15',['Generic Attribute Profile (GATT)',['../group__bt__gatt.html',1,'']]],
  ['generic_20audio_20assigned_20numbers_16',['Generic Audio Assigned Numbers',['../group__bt__assigned__numbers__audio.html',1,'']]],
  ['generic_20object_20exchange_20profile_20goep_17',['Generic Object Exchange Profile (GOEP)',['../group__bt__goep.html',1,'']]],
  ['gmap_20lc3_20presets_18',['Gaming Audio Profile (GMAP) LC3 Presets',['../group__bt__gmap__lc3__preset.html',1,'']]],
  ['gnss_19',['GNSS',['../group__gnss__interface.html',1,'']]],
  ['gnss_20configuration_20',['GNSS configuration',['../group__st87mxx__gnss__configuration.html',1,'']]],
  ['gnss_20driver_20backend_20api_21',['GNSS Driver Backend API',['../group__gnss__interface__backend.html',1,'']]],
  ['goep_22',['Generic Object Exchange Profile (GOEP)',['../group__bt__goep.html',1,'']]],
  ['goep_20transport_20l2cap_23',['GOEP transport L2CAP',['../group__bt__goep__transport__l2cap.html',1,'']]],
  ['goep_20transport_20rfcomm_24',['GOEP transport RFCOMM',['../group__bt__goep__transport__rfcomm.html',1,'']]],
  ['gpio_25',['gpio',['../group__gpio__emul.html',1,'Emulated GPIO'],['../group__subsys__tracing__apis__gpio.html',1,'GPIO'],['../group__gpio__interface.html',1,'GPIO'],['../group__tgpio__interface.html',1,'Time-aware GPIO']]],
  ['gpio_20api_26',['Devicetree GPIO API',['../group__devicetree-gpio.html',1,'']]],
  ['gpio_20api_20extensions_27',['Device-specific GPIO API extensions',['../group__gpio__interface__ext.html',1,'']]],
  ['gpio_20fifo_20wire_20out_28',['Bouffalolab BL61x GPIO FIFO / Wire Out',['../group__gpio__bl61x__wo__interface.html',1,'']]],
  ['gpio_20flags_29',['gpio flags',['../group__gpio__interface__max32.html',1,'MAX32-specific GPIO Flags'],['../group__gpio__interface__npm13xx.html',1,'nPM13xx-specific GPIO Flags'],['../group__gpio__interface__npm2100.html',1,'nPM2100-specific GPIO Flags'],['../group__gpio__interface__npm6001.html',1,'nPM6001-specific GPIO Flags'],['../group__gpio__interface__nrf.html',1,'nRF-specific GPIO Flags']]],
  ['gpio_20pin_20headers_30',['GPIO pin headers',['../group__devicetree-gpio-pin-headers.html',1,'']]],
  ['gpio_20specific_20flags_31',['STM32 GPIO specific flags',['../group__gpio__interface__stm32.html',1,'']]],
  ['gptp_20support_32',['gPTP support',['../group__gptp.html',1,'']]],
  ['grove_20display_33',['Grove display',['../group__grove__display.html',1,'']]],
  ['grow_20r502a_34',['Grow R502A',['../group__grow__r502a__interface.html',1,'']]],
  ['gyroscope_20data_20rate_20options_35',['gyroscope data rate options',['../group__ICM4268X__GYRO__DATA__RATE.html',1,'Gyroscope data rate options'],['../group__icm42688__gyro__data__rate.html',1,'Gyroscope data rate options'],['../group__ICM42686__GYRO__DATA__RATE.html',1,'Gyroscope data rate options'],['../group__ICM45686__GYRO__DATA__RATE.html',1,'Gyroscope data rate options']]],
  ['gyroscope_20low_20pass_20filtering_20options_36',['Gyroscope Low-pass Filtering options',['../group__ICM45686__GYRO__LPF.html',1,'']]],
  ['gyroscope_20power_20modes_37',['gyroscope power modes',['../group__ICM42686__GYRO__POWER__MODES.html',1,'Gyroscope power modes'],['../group__ICM4268X__GYRO__POWER__MODES.html',1,'Gyroscope power modes'],['../group__ICM45686__GYRO__POWER__MODES.html',1,'Gyroscope power modes'],['../group__icm42688__gyro__power__modes.html',1,'Gyroscope power modes']]],
  ['gyroscope_20scale_20options_38',['gyroscope scale options',['../group__ICM45686__GYRO__SCALE.html',1,'Gyroscope scale options'],['../group__icm42688__gyro__scale.html',1,'Gyroscope scale options'],['../group__ICM42686__GYRO__SCALE.html',1,'Gyroscope scale options']]]
];
